Transport:
    type: object
    inherits:
        - 'TransportDecorator'
    config:
        fields:
            daysUntilDelivery:
                type: "Int!"
                description: "Number of days until goods are delivered"
            stores:
                type: "StoreConnection"
                argsBuilder: "Relay::Connection"
                description: "Stores available for personal pickup"
                resolve: "@=query('storesByTransportQuery', value, args)"
                complexity: "@=dynamicPaginationComplexity(args)"
                args:
                    searchText:
                        type: "String"
                        defaultValue: null
                        description: "Search for city or post code"
                    coordinates:
                        type: "Coordinates"
                        defaultValue: null
                        description: "Returns stores with distance from given coordinates"
            mainImage:
                type: "Image"
                description: "Transport image by params"
                resolve: '@=query("mainImageByEntityPromiseQuery", value, args["type"])'
                args:
                    type:
                        type: "String"
                        defaultValue: null
            isPersonalPickup:
                type: "Boolean!"
                description: "Pointer telling if the transport is of type personal pickup"
