export const VALIDATION_CONSTANTS = {
    streetMaxLength: 100,
    cityMaxLength: 100,
    emailMaxLength: 255,
    telephoneMinLength: 9,
    telephoneMaxLength: 30,
    postcodeLength: 5,
    firstNameMaxLength: 100,
    lastNameMaxLength: 100,
    companyNameMaxLength: 100,
    companyNumberExactLength: 8,
    companyTaxNumberMaxLength: 50,
    passwordMinLength: 6,
    fileMaxSize: 10485760,
    maxFilesCount: 10,
    complaintManualDocumentNumberMaxLength: 255,
    manualComplaintItemNameMaxLength: 255,
    manualComplaintItemCatnumMaxLength: 255,
    maxBankAccountNumberLength: 34,
    maxCartItemQuantity: 1000,
} as const;
