fragment ListedVariantFragment on Variant {
    __typename
    uuid
    slug
    name
    fullName
    stockQuantity
    flags {
        ...SimpleFlagFragment
    }
    ...ProductImagesThumbnailFragment
    ...ProductPriceFragment
    availability {
        ...AvailabilityFragment
    }
    availableStoresCount
    exposedStoresCount
    catalogNumber
    storeAvailabilities {
        ...StoreAvailabilityFragment
    }
    brand {
        ...SimpleBrandFragment
    }
    categories {
        name
    }
}
