fragment ProductDetailInterfaceFragment on Product {
    __typename
    id
    uuid
    slug
    fullName
    name
    namePrefix
    nameSuffix
    ...BreadcrumbFragment
    catalogNumber
    description
    ...ProductDetailImagesFragment
    ...ProductPriceFragment
    parameters {
        ...ParameterFragment
    }
    stockQuantity
    accessories {
        ...SliderProductFragment
    }
    brand {
        ...SimpleBrandFragment
    }
    categories {
        name
    }
    flags {
        ...SimpleFlagFragment
    }
    isSellingDenied
    availability {
        ...AvailabilityFragment
    }
    seoTitle
    seoMetaDescription
}
