fragment ProductFilterOptionsFragment on ProductFilterOptions {
    __typename
    minimalPrice
    maximalPrice
    brands {
        __typename
        count
        brand {
            __typename
            uuid
            name
        }
    }
    inStock
    flags {
        __typename
        count
        flag {
            ...SimpleFlagFragment
        }
        isSelected
    }
    parameters {
        ... on ParameterCheckboxFilterOption {
            name
            uuid
            __typename
            values {
                __typename
                uuid
                text
                count
                isSelected
            }
            isCollapsed
        }
        ... on ParameterColorFilterOption {
            name
            uuid
            __typename
            values {
                __typename
                uuid
                text
                count
                rgbHex
                isSelected
                colorIcon {
                    url
                }
            }
            isCollapsed
        }
        ... on ParameterSliderFilterOption {
            name
            uuid
            __typename
            minimalValue
            maximalValue
            unit {
                __typename
                name
            }
            isCollapsed
            selectedValue
            isSelectable
        }
    }
}
