PaymentSetupCreationDataDecorator:
    type: object
    decorator: true
    config:
        fields:
            goPayCreatePaymentSetup:
                type: "GoPayCreatePaymentSetup"
                description: "Identifiers of GoPay payment method"
            orderPaymentStatusPageValidityHash:
                type: "String"
                description: "Hash for validating payment status page"
