services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Shopsys\FrameworkBundle\Model\Pricing\Vat\VatDeletionCronModule:
        tags:
            - { name: shopsys.cron, hours: '*', minutes: '*', readableName: 'Delete vats' }

    Shopsys\FrameworkBundle\Model\Product\ProductVisibilityImmediateCronModule:
        tags:
            - { name: shopsys.cron, hours: '*', minutes: '*', readableName: 'Recalculate immediate product visibilities' }

    Shopsys\FrameworkBundle\Model\Product\ProductVisibilityMidnightCronModule:
        tags:
            - { name: shopsys.cron, hours: '0', minutes: '0', readableName: 'Recalculate midnight product visibilities' }

    Shopsys\FrameworkBundle\Model\Product\Availability\ProductAvailabilityCronModule:
        tags:
            - { name: shopsys.cron, hours: '*', minutes: '*', readableName: 'Recalculate product availabilities' }

    Shopsys\FrameworkBundle\Model\Cart\Item\DeleteOldCartsCronModule:
        tags:
            - { name: shopsys.cron, hours: '0', minutes: '0', readableName: 'Delete old customer carts' }

    Shopsys\FrameworkBundle\Model\Feed\DailyFeedCronModule:
        tags:
            - { name: shopsys.cron, hours: '*/6', minutes: '0', readableName: 'Generate daily feeds' }

    Shopsys\FrameworkBundle\Model\Feed\HourlyFeedCronModule:
        tags:
            - { name: shopsys.cron, hours: '*', minutes: '10', readableName: 'Generate hourly feeds' }

    Shopsys\FrameworkBundle\Model\Sitemap\SitemapCronModule:
        tags:
            - { name: shopsys.cron, hours: '4', minutes: '0', readableName: 'Generate Sitemap' }

    Shopsys\FrameworkBundle\Component\FileUpload\DeleteOldUploadedFilesCronModule:
        tags:
            - { name: shopsys.cron, hours: '5', minutes: '0', readableName: 'Delete old temporary uploaded files' }

    App\Model\Category\Transfer\Akeneo\AkeneoImportCategoryCronModule:
        tags:
            - { name: shopsys.cron, hours: '*', minutes: '*/5', readableName: 'Import stromu kategorií z Akeneo' }

    App\Model\Product\Parameter\Transfer\Akeneo\AkeneoImportProductParameterCronModule:
        tags:
            - { name: shopsys.cron, hours: '01', minutes: '30', readableName: 'Import číselníku parametrů z Akeneo' }

    App\Model\Product\Transfer\Akeneo\AkeneoImportProductCronModule:
        tags:
            - { name: shopsys.cron, hours: '*', minutes: '*/5', readableName: 'Import produktů z Akeneo' }

    App\Model\Product\Transfer\Akeneo\AkeneoImportFlagCronModule:
        tags:
            - { name: shopsys.cron, hours: '*', minutes: '*/5', readableName: 'Import číselníku příznaků z Akeneo' }

    App\Model\Customer\Transfer\ScontoBridge\ScontoBridgeImportCustomerCronModule:
        tags:
            - { name: shopsys.cron, hours: '*', minutes: '*/5', readableName: 'Import zákazníků z IM' }

    App\Model\Product\Transfer\ScontoBridge\ScontoBridgeImportProductStockCronModule:
        tags:
            - { name: shopsys.cron, hours: '*', minutes: '*/5', readableName: 'Import skladovách zásob z IM' }

    App\Model\Product\Transfer\ScontoBridge\ScontoBridgeImportFutureProductStockCronModule:
        tags:
            - { name: shopsys.cron, hours: '*', minutes: '*/5', readableName: 'Import budoucích skladovách zásob z IM' }

    App\Model\Product\Transfer\ScontoBridge\ScontoBridgeImportExposedProductCronModule:
        tags:
            - { name: shopsys.cron, hours: '*', minutes: '*/5', readableName: 'Import vystavených produktů z IM' }

    App\Model\Transfer\Issue\TransferIssueLogCleanerCronModule:
        tags:
            - { name: shopsys.cron, hours: '23', minutes: '10', readableName: 'Mazání starých problémů v přenosech' }

    App\Model\Product\Elasticsearch\ProductExportCronModule:
        tags:
            - { name: shopsys.cron, hours: '0', minutes: '0', readableName: "Export products to Elasticsearch" }

    App\Model\Product\Elasticsearch\ProductExportChangedCronModule:
        tags:
            - { name: shopsys.cron, hours: '*', minutes: '*', readableName: "Export changed products to Elasticsearch" }

    App\Model\Product\Transfer\Akeneo\AkeneoImportProductFilesCronModule:
        tags:
            - { name: shopsys.cron, hours: '*', minutes: '*/5', readableName: 'Import souborů k produktům z Akeneo' }

    App\Model\Product\Series\Transfer\Akeneo\AkeneoImportProductSeriesCronModule:
        tags:
            - { name: shopsys.cron, hours: '23', minutes: '10', readableName: 'Import nábytkových programů z Akeneo' }

    App\Model\Newsletter\Synchronization\TargitoSynchronizationCronModule:
        tags:
            - { name: shopsys.cron, hours: '*', minutes: '*/5', readableName: 'Synchronizace odběratelů v Targitu' }

    App\Model\GoPay\GoPayAvailablePaymentsCronModule:
        arguments:
            - '%gopay.config%'
        tags:
            - { name: shopsys.cron, hours: '3', minutes: '50', readableFrequency: '1x za den' }

    App\Model\GoPay\OrderGoPayStatusUpdateCronModule:
        tags:
            - { name: shopsys.cron, hours: '*', minutes: '15', readableFrequency: '1x za hodinu' }

    App\Component\Image\Kraken\KrakenImageOptimizationCronModule:
        tags:
            - { name: shopsys.cron, hours: '*', minutes: '*/5', readableName: 'Optimalizace obrázků Kraken.io' }

    App\Component\FileUpload\DeleteOldUploadedFilesCronModule:
        tags:
            - { name: shopsys.cron, hours: '2', minutes: '50', readableName: 'Promazání pozůstalých uploadovaných souborů' }

    # This module should run as last because it creates multiple kernels and fake requests.
    Shopsys\FrameworkBundle\Component\Error\ErrorPageCronModule:
        tags:
            - { name: shopsys.cron, hours: '21', minutes: '10', readableName: 'Generate Error pages' }
