services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

#   Example:
#   Shopsys\FrameworkBundle\Model\Product\Elasticsearch\ProductExportCronModule:
#       tags:
#           - { name: shopsys.cron, hours: '*', minutes: '*', readableName: 'Product search export' }

    # Error pages are not generated in production because https://github.com/shopsys/shopsys/issues/1628 Cron
    Shopsys\FrameworkBundle\Component\Error\ErrorPageCronModule: ~

    App\Model\Category\Transfer\Akeneo\AkeneoImportCategoryCronModule:
        tags:
            - { name: shopsys.cron, hours: '*', minutes: '*/5' }

    App\Model\Product\Transfer\Akeneo\AkeneoImportProductCronModule:
        tags:
            - { name: shopsys.cron, hours: '*', minutes: '*/5' }

    # disabled because ProductCalculatesPrice is in this project turned off.
    # Form prices are used just product_domain.low/high_price....
    Shopsys\FrameworkBundle\Model\Product\Pricing\ProductPriceCronModule: ~

    App\Model\Customer\Transfer\ScontoBridge\ScontoBridgeImportCustomerCronModule:
        tags:
            - { name: shopsys.cron, hours: '*', minutes: '*/5' }

    App\Model\Transfer\Issue\TransferIssueLogCleanerCronModule:
        tags:
            - { name: shopsys.cron, hours: '23', minutes: '10' }

    App\Model\Product\Transfer\Akeneo\AkeneoImportProductFilesCronModule:
        tags:
            - { name: shopsys.cron, hours: '*', minutes: '*/5' }