services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    #   Example:
    #   Shopsys\FrameworkBundle\Model\Product\Elasticsearch\ProductExportCronModule:
    #       tags:
    #           - { name: shopsys.cron, hours: '*', minutes: '*' }

    # Error pages are not generated in production because https://github.com/shopsys/shopsys/issues/1628 Cron
    Shopsys\FrameworkBundle\Component\Error\ErrorPageCronModule: ~

    App\Model\Category\Transfer\Akeneo\AkeneoImportCategoryCronModule:
        tags:
            - { name: shopsys.cron, hours: '*', minutes: '*/5' }

    App\Model\Product\Transfer\Akeneo\AkeneoImportProductCronModule:
        tags:
            - { name: shopsys.cron, hours: '*', minutes: '*/5' }

    App\Model\Customer\Transfer\ScontoBridge\ScontoBridgeImportCustomerCronModule:
        tags:
            - { name: shopsys.cron, hours: '*', minutes: '*/5' }

    App\Model\Transfer\Issue\TransferIssueLogCleanerCronModule:
        tags:
            - { name: shopsys.cron, hours: '23', minutes: '10' }
