services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Shopsys\FrameworkBundle\Model\Pricing\Vat\VatDeletionCronModule:
        tags:
            - { name: shopsys.cron, hours: '*', minutes: '*', instanceName: service, readableName: 'Delete vats' }

    Shopsys\FrameworkBundle\Model\Product\ProductVisibilityImmediateCronModule:
        tags:
            - { name: shopsys.cron, hours: '*', minutes: '*', instanceName: service, readableName: 'Recalculate immediate product visibilities' }

    Shopsys\FrameworkBundle\Model\Product\ProductVisibilityMidnightCronModule:
        tags:
            - { name: shopsys.cron, hours: '0', minutes: '0', instanceName: service, readableName: 'Recalculate midnight product visibilities' }

    Shopsys\FrameworkBundle\Model\Cart\Item\DeleteOldCartsCronModule:
        tags:
            - { name: shopsys.cron, hours: '0', minutes: '0', instanceName: service, readableName: 'Delete old customer carts' }

    Shopsys\FrameworkBundle\Model\Feed\DailyFeedCronModule:
        tags:
            - { name: shopsys.cron, hours: '*/6', minutes: '0', instanceName: export, readableName: 'Generate daily feeds' }

    Shopsys\FrameworkBundle\Model\Sitemap\SitemapCronModule:
        tags:
            - { name: shopsys.cron, hours: '4', minutes: '0', instanceName: export, readableName: 'Generate Sitemap' }

    Shopsys\FrameworkBundle\Component\FileUpload\DeleteOldUploadedFilesCronModule:
        tags:
            - { name: shopsys.cron, hours: '5', minutes: '0', instanceName: service, readableName: 'Delete old temporary uploaded files' }

    App\Model\Category\Transfer\Akeneo\AkeneoImportCategoryCronModule:
        tags:
            - { name: shopsys.cron, hours: '*', minutes: '15', instanceName: importAkeneoProduct, readableName: 'Import stromu kategorií z Akeneo' }

    App\Model\Product\Transfer\Akeneo\AkeneoImportProductCronModule:
        tags:
            - { name: shopsys.cron, hours: '*', minutes: '*/5', instanceName: importAkeneoProduct, readableName: 'Import produktů z Akeneo' }

    App\Model\Product\Transfer\Akeneo\AkeneoImportFlagCronModule:
        tags:
            - { name: shopsys.cron, hours: '*', minutes: '20', instanceName: importAkeneoProduct, readableName: 'Import číselníku příznaků z Akeneo' }

    App\Model\Customer\Transfer\ScontoBridge\ScontoBridgeImportCustomerCronModule:
        tags:
            - { name: shopsys.cron, hours: '*', minutes: '*/5', instanceName: importIM, readableName: 'Import zákazníků z IM' }

    App\Model\Product\Transfer\ScontoBridge\ScontoBridgeImportProductStockCronModule:
        tags:
            - { name: shopsys.cron, hours: '*', minutes: '*/5', instanceName: importIM, readableName: 'Import skladovách zásob z IM' }

    App\Model\Product\Transfer\ScontoBridge\ScontoBridgeImportFutureProductStockCronModule:
        tags:
            - { name: shopsys.cron, hours: '*', minutes: '*/5', instanceName: importIM, readableName: 'Import budoucích skladovách zásob z IM' }

    App\Model\Product\Transfer\ScontoBridge\ScontoBridgeImportExposedProductCronModule:
        tags:
            - { name: shopsys.cron, hours: '*', minutes: '*/5', instanceName: importIM, readableName: 'Import vystavených produktů z IM' }

    App\Model\Transfer\Issue\TransferIssueLogCleanerCronModule:
        tags:
            - { name: shopsys.cron, hours: '23', minutes: '10', instanceName: service, readableName: 'Mazání starých problémů v přenosech' }

    App\Model\Product\Elasticsearch\ProductExportCronModule:
        tags:
            - { name: shopsys.cron, hours: '0', minutes: '0', instanceName: service, readableName: "Export products to Elasticsearch" }

    App\Model\Product\Elasticsearch\ProductExportChangedCronModule:
        tags:
            - { name: shopsys.cron, hours: '*', minutes: '*', instanceName: service, readableName: "Export changed products to Elasticsearch" }

    App\Model\Product\Transfer\Akeneo\AkeneoImportProductFilesCronModule:
        tags:
            - { name: shopsys.cron, hours: '*', minutes: '*/5', instanceName: importAkeneoProduct, readableName: 'Import souborů k produktům z Akeneo' }

    App\Model\Product\Series\Transfer\Akeneo\AkeneoImportProductSeriesCronModule:
        tags:
            - { name: shopsys.cron, hours: '23', minutes: '10', instanceName: importAkeneoOther, readableName: 'Import nábytkových programů z Akeneo' }

    App\Model\Newsletter\Synchronization\TargitoSynchronizationCronModule:
        tags:
            - { name: shopsys.cron, hours: '*', minutes: '*/5', instanceName: export, readableName: 'Synchronizace odběratelů v Targitu' }

    App\Model\GoPay\GoPayAvailablePaymentsCronModule:
        arguments:
            - '%gopay_config%'
        tags:
            - { name: shopsys.cron, hours: '3', minutes: '50', instanceName: gopay, readableName: 'Import dostupných platebních metod z GoPay', readableFrequency: '1x za den' }

    App\Model\GoPay\OrderGoPayStatusUpdateCronModule:
        tags:
            - { name: shopsys.cron, hours: '*', minutes: '15', instanceName: gopay, readableName: 'Import stavu plateb objednávek z GoPay', readableFrequency: '1x za hodinu' }

    App\Component\Image\Kraken\KrakenImageOptimizationCronModule:
        tags:
            - { name: shopsys.cron, hours: '*', minutes: '*/5', instanceName: export, readableName: 'Optimalizace obrázků Kraken.io' }

    App\Component\FileUpload\DeleteOldUploadedFilesCronModule:
        tags:
            - { name: shopsys.cron, hours: '2', minutes: '50', instanceName: service, readableName: 'Promazání pozůstalých uploadovaných souborů' }

    # This module should run as last because it creates multiple kernels and fake requests.
    Shopsys\FrameworkBundle\Component\Error\ErrorPageCronModule:
        tags:
            - { name: shopsys.cron, hours: '21', minutes: '10', instanceName: service, readableName: 'Generate Error pages' }
