services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\Twig\:
        resource: '../../src/Twig/'

    App\Twig\LocalizationExtension:
        arguments:
            - '%shopsys.web_dir%'

    App\Twig\PriceExtension: ~

    Shopsys\FrameworkBundle\Twig\LocalizationExtension: '@App\Twig\LocalizationExtension'
    Shopsys\FrameworkBundle\Twig\PriceExtension: '@App\Twig\PriceExtension'
