parameters:
    fp_js_form_validator.twig_extension.class: 'App\Twig\JsFormValidatorTwigExtension'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\Twig\:
        resource: '../../src/Twig/'
        exclude: '../../src/Twig/{JsFormValidatorTwigExtension.php}'

    App\Twig\LocalizationExtension:
        arguments:
            - '%shopsys.web_dir%'

    App\Twig\PriceExtension: ~

    Shopsys\FrameworkBundle\Twig\LocalizationExtension: '@App\Twig\LocalizationExtension'
    Shopsys\FrameworkBundle\Twig\PriceExtension: '@App\Twig\PriceExtension'
