<?php

declare(strict_types=1);

namespace Shopsys\FrameworkBundle\Model\Security\AccessControl;

use ReflectionClass;
use ReflectionMethod;
use RuntimeException;
use Shopsys\FrameworkBundle\Component\AttributeRouteControllerLoader;
use Symfony\Component\Finder\Finder;
use Symfony\Component\Routing\Attribute\Route;

class AccessControlRulesAttributeFinder
{
    protected const string CONTROLLER_DIRECTORY = __DIR__ . '/../../../Controller/Admin';

    /**
     * @param string[] $additionalDirectories
     * @return \Shopsys\FrameworkBundle\Model\Security\AccessControl\RouteAccessControlData[]
     */
    public function findAll(array $additionalDirectories = []): array
    {
        $finder = new Finder();
        $finder->files()
            ->in(array_merge([self::CONTROLLER_DIRECTORY], $additionalDirectories))
            ->name('*.php');

        $rules = [];

        foreach ($finder as $file) {
            $className = $this->getClassFullNameFromFile($file->getRealPath());
            $reflectionClass = new ReflectionClass($className);

            foreach ($reflectionClass->getMethods() as $reflectionMethod) {
                foreach ($reflectionMethod->getAttributes(AccessControlRule::class) as $accessControlAttribute) {
                    $rules[] = new RouteAccessControlData($this->getRouteName($reflectionClass, $reflectionMethod), $accessControlAttribute->newInstance());
                }
            }
        }

        return $rules;
    }

    /**
     * @param string $filePath
     * @return string
     */
    protected function getClassFullNameFromFile(string $filePath): string
    {
        $fileContent = file_get_contents($filePath);

        if ($fileContent === false) {
            throw new RuntimeException('Failed to read file content');
        }

        preg_match('/namespace\s+([^;]+);/', $fileContent, $namespaceMatches);
        preg_match('/class\s+(\w+)/', $fileContent, $classMatches);

        if ($namespaceMatches === [] || $classMatches === []) {
            throw new RuntimeException('Failed to parse class name from file');
        }

        return trim($namespaceMatches[1]) . '\\' . trim($classMatches[1]);
    }

    /**
     * If the action has exactly one #[Route] attribute, use its name if defined.
     * Otherwise, use the default route name generated by the AttributeRouteControllerLoader.
     *
     * @param \ReflectionClass $class
     * @param \ReflectionMethod $method
     * @return string
     */
    protected function getRouteName(ReflectionClass $class, ReflectionMethod $method): string
    {
        $routeAttributes = $method->getAttributes(Route::class);

        if (count($routeAttributes) === 1) {
            /** @var \Symfony\Component\Routing\Attribute\Route $routeAttribute */
            $routeAttribute = $routeAttributes[0]->newInstance();

            if ($routeAttribute->getName() !== null) {
                return $routeAttribute->getName();
            }
        }

        return (new AttributeRouteControllerLoader())->getRouteName($class, $method);
    }
}
