ParameterValueDecorator:
    type: object
    decorator: true
    config:
        description: "Represents a parameter value"
        fields:
            uuid:
                type: "Uuid!"
                description: "UUID"
            text:
                type: "String!"
                description: "Parameter value"
            rgbHex:
                type: "String"
                description: "Parameter value RGB value if set (for color parameters only)"
            colorIcon:
                type: "File"
                description: "Uploaded file for color parameter value"
