ParameterDecorator:
    type: object
    decorator: true
    config:
        description: "Represents a parameter"
        fields:
            uuid:
                type: "Uuid!"
                description: "UUID"
            name:
                type: "String!"
                description: "Parameter name"
            type:
                type: "ParameterTypeEnum!"
                description: "Parameter type"
            values:
                type: "[ParameterValue!]!"
            unit:
                type: "Unit"
                description: "Unit of the parameter"
            group:
                type: "String"
                description: "Parameter group to which the parameter is assigned"
