mutation AddToCartMutation (
    $cartUuid: Uuid
    $payment: PaymentInput
    $isAbsoluteQuantity: Boolean
    $productUuid: Uuid!
    $quantity: Int!
) {
    AddToCart(input: {
        cartUuid: $cartUuid,
        payment: $payment,
        isAbsoluteQuantity: $isAbsoluteQuantity,
        productUuid: $productUuid,
        quantity: $quantity
    }) {
        ...CartFragment
        addProductResult {
            addedQuantity
            isNew
            isQuantityOverLimit
            notOnStockQuantity
            overLimitQuantity
        }
    }
}
