SlugDecorator:
    type: interface
    decorator: true
    config:
        description: "Represents entity retrievable by slug"
        fields:
            uuid:
                type: "Uuid!"
                description: "UUID"
            name:
                type: "String"
            slug:
                type: "String!"
