SettingsQuery:
    type: object
    config:
        fields:
            settings:
                type: 'Settings'
                resolve: "@=resolver('resolveSettings')"
                description: "Returns current setting"
