<?php

declare(strict_types=1);

namespace Shopsys\AdministrationBundle\Component\Attributes;

use Attribute;

/**
 * Declares a custom action of a CRUD controller. Can be placed on a method of the CRUD controller itself,
 * of its extension, of any other controller, or on an invokable class (applies to __invoke()).
 *
 * The route is generated by CrudRouteProvider under the CRUD controller URL, access control uses the permission
 * attributes (CanView, CanEdit, ...) of the method the same way as for the built-in actions.
 */
#[Attribute(Attribute::TARGET_METHOD | Attribute::TARGET_CLASS)]
final readonly class CrudAction
{
    /**
     * @param string|null $name action name in snake_case, defaults to the method name without the "Action" suffix (required for __invoke())
     * @param class-string|null $crudController target CRUD controller (validated at build time), inferred for methods of a CRUD controller or its extension
     * @param string|null $path route path appended after the CRUD controller URL, defaults to "/<name>" followed by a placeholder for every required scalar parameter of the method (e.g. "/<name>/{id}")
     * @param string[] $methods allowed HTTP methods
     * @param array<string, string> $requirements route requirements
     * @param array<string, mixed> $defaults route defaults
     * @param string|null $condition route condition expression
     */
    public function __construct(
        public ?string $name = null,
        public ?string $crudController = null,
        public ?string $path = null,
        public array $methods = [],
        public array $requirements = [],
        public array $defaults = [],
        public ?string $condition = null,
    ) {
    }
}
