#!/bin/sh

DIST_DOCKER_COMPOSE_FILE=$1
DOCKER_COMPOSE_FILE=$2
PHP_FPM_IMAGE=$3
STOREFRONT_IMAGE=$4
ELASTICSEARCH_IMAGE=$5

cp -f "$DIST_DOCKER_COMPOSE_FILE" "$DOCKER_COMPOSE_FILE"

sed -i "s#php-fpm-image#$PHP_FPM_IMAGE#" "$DOCKER_COMPOSE_FILE"

sed -i "s#storefront-image#$STOREFRONT_IMAGE#" "$DOCKER_COMPOSE_FILE"

if [ -n "$ELASTICSEARCH_IMAGE" ]; then
    sed -i "s#elasticsearch-image#$ELASTICSEARCH_IMAGE#" "$DOCKER_COMPOSE_FILE"
fi
