StoreAvailability:
    type: object
    config:
        description: "Represents an availability in an individual store"
        fields:
            storeName:
                type: "String!"
                description: "Name of the store"
            exposed:
                type: "Boolean!"
                description: "Is product exposed on this store"
            availabilityInformation:
                type: "String!"
                description: "Detailed information about availability"
            availabilityStatus:
                type: "String!"
                description: "Availability status in a format suitable for usage in the code"
