overblog_graphql:
    definitions:
        schema:
            query: Query
            mutation: Mutation
        mappings:
            types:
                -   type: yaml
                    dir: "%shopsys.root_dir%/config/graphql/types"
        builders:
            args:
                -   alias: "PaginatorArgumentsBuilder"
                    class: Shopsys\FrontendApiBundle\Component\Arguments\PaginatorArgumentsBuilder
                -   alias: "BlogArticlePaginatorArgumentsBuilder"
                    class: App\FrontendApi\Model\BlogArticle\BlogArticlePaginatorArgumentsBuilder
    security:
        handle_cors: true
        query_max_complexity: 1000
