twig:
    debug: "%kernel.debug%"
    exception_controller: null
    form_themes:
        - '@ShopsysFramework/Common/Form/theme.html.twig'
        - '@ShopsysFramework/Admin/Form/colorpickerFields.html.twig'
        - '@ShopsysFramework/Admin/Form/abstractFileuploadFields.html.twig'
        - '@ShopsysFramework/Admin/Form/fileuploadFields.html.twig'
        - '@ShopsysFramework/Admin/Form/imageuploadFields.html.twig'
        - '@ShopsysFramework/Admin/Form/priceandvattableByDomainsFields.html.twig'
        - '@ShopsysFramework/Admin/Form/orderItems.html.twig'
        - '@ShopsysFramework/Admin/Form/orderlistFields.html.twig'
        - '@ShopsysFramework/Admin/Form/displayOnlyCustomer.html.twig'
        - '@ShopsysFramework/Admin/Form/displayOnlyDomainIconFields.html.twig'
        - '@ShopsysFramework/Admin/Form/displayOnlyFields.html.twig'
        - '@ShopsysFramework/Admin/Form/warningMessage.html.twig'
        - '@ShopsysFramework/Admin/Form/displayOnlyUrl.html.twig'
        - '@ShopsysFramework/Admin/Form/localizedFullWidth.html.twig'
        - '@ShopsysFramework/Admin/Form/productParameterValue.html.twig'
        - '@ShopsysFramework/Admin/Form/productCalculatedPrices.html.twig'
        - '@ShopsysFramework/Front/Form/deliveryAddressChoiceFields.html.twig'
        - '@ShopsysFramework/Admin/Form/deliveryAddressListFields.html.twig'
        - 'Admin/Form/Transport/transportPackageType.html.twig'
        - 'Admin/Form/blogCategoriesType.html.twig'
        - 'Admin/Form/blogCategoryCheckboxType.html.twig'
        - 'Admin/Form/productDetailFormTheme.html.twig'
        - 'Admin/Form/blogArticleFormTheme.html.twig'
        - 'Admin/Form/productsFormTheme.html.twig'
        - 'Front/Form/sliderFormTheme.html.twig'
        - 'Admin/Form/promoCodeLimitFormTheme.html.twig'
        - 'Admin/Form/imageuploadFields.html.twig'
    strict_variables: true
    globals:
        globalMultipleFormSetting: '@Shopsys\FrameworkBundle\Component\Form\MultipleFormSetting'
        parameterDisableFormFieldsFromTransfer: '%disable_form_fields_from_transfer%'
        imgSrcsetMobileBreakpoint: '600px'
        imgSrcsetDesktopBreakpoint: '601px'
        imgLazyloadPlaceholder: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+ip1sAAAAASUVORK5CYII='
        googleMapApiKey: 'AIzaSyCkbxpC65m4vJAoWjioff5kYktYQDiEtiE&amp;token=38432'
