query SlugQuery(
    $slug: String!
    $sortingMode: ProductOrderingModeEnum
    $endCursorForPagination: String
    $pageSize: Int
) {
    slug(slug: $slug) {
        __typename
        ... on Product {
            ...ProductDetailFragment
        }
        ... on Category {
            ...CategoryDetailFragment
        }
        ... on Store {
            ...StoreDetailFragment
        }
        ... on Article {
            ...ArticleDetailFragment
        }
        ... on BlogArticle {
            ...BlogArticleDetailFragment
        }
        ... on Brand {
            ...BrandDetailFragment
        }
        ... on Flag {
            ...FlagDetailFragment
        }
    }
}
