RecoverPasswordInput:
    type: input-object
    config:
        validation:
            - App\FrontendApi\Model\Component\Constraints\ResetPasswordHash: ~
        fields:
            email:
                type: 'String!'
                description: 'Customer user email.'
                validation:
                    - NotBlank:
                          message: 'Please enter your email address'
                    - Email:
                          message: 'Please enter valid email'
                    - App\FrontendApi\Model\Component\Constraints\ExistingEmail: ~
            hash:
                type: 'String!'
                description: 'Hash'
                validation:
                    - Length:
                          min: 50
                          max: 50
            newPassword:
                type: 'Password!'
                description: 'New customer user password.'
                validation:
                    - NotBlank:
                          message: 'Please enter new password'
                    - Length:
                          min: 6
                          minMessage: 'New password must be at least {{ limit }} characters long'
            cartUuid:
                type: 'Uuid'
                description: 'Uuid of the cart that should be merged to the cart of the user'
                defaultValue: null
            productListsUuids:
                type: '[Uuid!]!'
                description: 'Uuids of product lists that should be merged to the product lists of the user'
                defaultValue: []
            shouldOverwriteCustomerUserCart:
                type: 'Boolean!'
                description: 'A boolean pointer to indicate if the current customer user cart should be overwritten by the cart with cartUuid'
                defaultValue: false
