TelephoneInputObjectDecorator:
    type: input-object
    decorator: true
    config:
        fields:
            telephone:
                type: "PhoneDataInput!"
                description: "The customer's telephone"
                validation: cascade
