<?xml version="1.0" encoding="UTF-8"?>
<project name="Shopsys Framework" default="list">

    <property file="${project.basedir}/build/build.local.properties"/>

    <property name="check-and-fix-annotations" value="true"/>
    <property name="path.root" value="${project.basedir}"/>
    <property name="path.vendor" value="${path.root}/vendor"/>
    <property name="path.framework" value="${path.vendor}/shopsys/framework"/>

    <property name="phpstan.level" value="4"/>

    <import file="${path.framework}/build.xml"/>

    <!-- Remove dependency `clean-redis-old` because old redis is used by live container during deployment. -->
    <target name="build-deploy-part-2-db-dependent" depends="product-search-migrate-structure,redis-check,db-migrations,domains-data-create,friendly-urls-generate,domains-urls-replace,error-pages-generate,warmup" description="Second part of application build for production preserving your DB (must be run with maintenance page when containing DB migrations)."/>

    <target name="maintenance-off" description="Turns the maintenance page off.">
        <exec executable="${path.php.executable}" passthru="true" checkreturn="true">
            <arg value="${path.bin-console}" />
            <arg value="app:maintenance" />
            <arg value="disable" />
        </exec>
    </target>

    <target name="maintenance-on" description="Turns the maintenance page on.">
        <exec executable="${path.php.executable}" passthru="true" checkreturn="true">
            <arg value="${path.bin-console}" />
            <arg value="app:maintenance" />
            <arg value="enable" />
        </exec>
    </target>

    <target name="db-migrations-count-with-maintenance" description="Get count of database migrations to execute and enable maintenance mode if needed.">
        <exec executable="${path.php.executable}" checkreturn="true" outputProperty="migrationCounts">
            <arg value="${path.bin-console}"/>
            <arg value="shopsys:migrations:count"/>
        </exec>
        <if>
            <contains string="${migrationCounts}" substring="Count of migrations to execute: 0" />
            <then>
                <echo message="There is no need to enable maintenance mode" />
            </then>
            <else>
                <phingcall target="maintenance-on" />
            </else>
        </if>
    </target>

</project>
