<?xml version="1.0" encoding="UTF-8"?>
<project name="Shopsys Framework" default="list">

    <property file="${project.basedir}/build/build.local.properties"/>

    <property name="check-and-fix-annotations" value="true"/>
    <property name="path.root" value="${project.basedir}"/>
    <property name="path.vendor" value="${path.root}/vendor"/>
    <property name="path.framework" value="${path.vendor}/shopsys/framework"/>
    <property name="path.framework.assets" value="${path.root}/node_modules/@shopsys/framework"/>
    <property name="path.frontend-api" value="${path.vendor}/shopsys/frontend-api"/>

    <property name="phpstan.level" value="5"/>

    <import file="${path.vendor}/devops/kubernetes-deployment/build.xml"/>
    <import file="${path.framework}/build.xml"/>
    <import file="${path.frontend-api}/build.xml"/>

    <target name="acceptance-elasticsearch-export" description="Exports indexes data into elasticsearch for acceptance environment.">
        <property name="elasticsearch.index" value=""/>
        <exec executable="${path.php.executable}" passthru="true" checkreturn="true">
            <arg value="${path.bin-console}"/>
            <arg value="--env=acc"/>
            <arg value="shopsys:elasticsearch:data-export"/>
            <arg value="${elasticsearch.index}"/>
        </exec>
    </target>

    <target name="build-dev" depends="build-version-generate,clean,composer-dev,timezones-check,dirs-create,test-dirs-create,assets,npm,db-migrations,domains-data-create,friendly-urls-generate,friendly-url-entity-mapping-check,domains-urls-replace,elasticsearch-index-recreate,elasticsearch-export,error-pages-generate,tests-acceptance-build,clean-redis-old,checks" description="Builds application for development preserving your DB and runs checks on changed files."/>

    <target name="build-dev-quick" depends="build-version-generate,clean,composer-dev,dirs-create,test-dirs-create,assets,npm,db-migrations,domains-data-create,friendly-urls-generate,friendly-url-entity-mapping-check,domains-urls-replace,elasticsearch-index-migrate,clean-redis-old" description="Builds application for development preserving your DB while skipping nonessential steps."/>

    <target name="db-demo" depends="production-protection,db-wipe-public-schema,db-import-basic-structure,db-migrations,domains-data-create,db-fixtures-demo,plugin-demo-data-load,friendly-urls-generate,friendly-url-entity-mapping-check,domains-urls-replace" description="Creates DB and fills it with demo data"/>

    <target name="db-rebuild" depends="production-protection,db-wipe-public-schema,db-import-basic-structure,db-migrations,domains-data-create,friendly-urls-generate,friendly-url-entity-mapping-check,domains-urls-replace" description="Drops all data in database and creates a new one with base data only."/>

    <target name="test-db-demo" depends="production-protection,clean,test-clean-redis,test-db-wipe-public-schema,test-db-import-basic-structure,test-db-migrations,test-domains-data-create,test-db-fixtures-demo,test-friendly-urls-generate,friendly-url-entity-mapping-check,test-plugin-demo-data-load,test-domains-urls-replace" description="Drops all data in test database and creates a new one with demo data." hidden="true"/>

    <target name="maintenance-off" description="Turns the maintenance page off.">
        <exec executable="${path.php.executable}" passthru="true" checkreturn="true">
            <arg value="${path.bin-console}" />
            <arg value="app:maintenance" />
            <arg value="disable" />
        </exec>
    </target>

    <target name="maintenance-on" description="Turns the maintenance page on.">
        <exec executable="${path.php.executable}" passthru="true" checkreturn="true">
            <arg value="${path.bin-console}" />
            <arg value="app:maintenance" />
            <arg value="enable" />
        </exec>
    </target>

    <target name="db-migrations-count-with-maintenance" description="Get count of database migrations to execute and enable maintenance mode if needed.">
        <exec executable="${path.php.executable}" checkreturn="true" outputProperty="migrationCounts">
            <arg value="${path.bin-console}"/>
            <arg value="shopsys:migrations:count"/>
        </exec>
        <if>
            <contains string="${migrationCounts}" substring="Count of migrations to execute: 0" />
            <then>
                <echo message="There is no need to enable maintenance mode" />
            </then>
            <else>
                <phingcall target="maintenance-on" />
            </else>
        </if>
    </target>

    <target name="assets" description="Installs web assets from external bundles into a public web directory.">
        <delete failonerror="false" includeemptydirs="true">
            <fileset dir="${path.root}/web/bundles/">
                <exclude name="/"/>
            </fileset>
        </delete>
        <exec executable="${path.php.executable}" passthru="true" checkreturn="true">
            <arg value="${path.bin-console}"/>
            <arg value="assets:install"/>
            <arg value="${path.root}/web/"/>
        </exec>
        <exec executable="${path.php.executable}" passthru="true" checkreturn="true">
            <arg value="${path.bin-console}"/>
            <arg value="elfinder:install"/>
            <arg value="--docroot"/>
            <arg value="web"/>
        </exec>
    </target>

    <target name="build-review-ci" depends="production-protection,wipe,build-version-generate,redis-check,db-demo,error-pages-generate,warmup,elasticsearch-index-recreate,elasticsearch-export,frontend-api-generate-new-keys,clean-redis-old" description="Builds application for review with clean demo DB."/>

    <target name="cron" description="Disabled - use new cron instances instead.">
        <fail message="Default cron instance is disabled. All modules are in new instances."/>
    </target>

    <target name="cron-service" description="Runs SERVICE background jobs. Should be executed periodically by system Cron every 5 minutes.">
        <exec executable="${path.php.executable}" passthru="true" checkreturn="true">
            <arg value="${path.bin-console}" />
            <arg value="shopsys:cron" />
            <arg value="--instance-name=service" />
        </exec>
    </target>

    <target name="cron-export" description="Runs EXPORT background jobs. Should be executed periodically by system Cron every 5 minutes.">
        <exec executable="${path.php.executable}" passthru="true" checkreturn="true">
            <arg value="${path.bin-console}" />
            <arg value="shopsys:cron" />
            <arg value="--instance-name=export" />
        </exec>
    </target>

    <target name="cron-import-akeneo-product" description="Runs Import Akeneo Product background jobs. Should be executed periodically by system Cron every 5 minutes.">
        <exec executable="${path.php.executable}" passthru="true" checkreturn="true">
            <arg value="${path.bin-console}" />
            <arg value="shopsys:cron" />
            <arg value="--instance-name=importAkeneoProduct" />
        </exec>
    </target>

    <target name="cron-import-im" description="Runs Import Akeneo IM jobs. Should be executed periodically by system Cron every 5 minutes.">
        <exec executable="${path.php.executable}" passthru="true" checkreturn="true">
            <arg value="${path.bin-console}" />
            <arg value="shopsys:cron" />
            <arg value="--instance-name=importIM" />
        </exec>
    </target>

    <target name="cron-import-akeneo-other" description="Runs Import Akeneo Other background jobs. Should be executed periodically by system Cron every 5 minutes.">
        <exec executable="${path.php.executable}" passthru="true" checkreturn="true">
            <arg value="${path.bin-console}" />
            <arg value="shopsys:cron" />
            <arg value="--instance-name=importAkeneoOther" />
        </exec>
    </target>

    <target name="cron-import-akeneo-files" description="Runs Import Akeneo Files background jobs. Should be executed periodically by system Cron every 5 minutes.">
        <exec executable="${path.php.executable}" passthru="true" checkreturn="true">
            <arg value="${path.bin-console}" />
            <arg value="shopsys:cron" />
            <arg value="--instance-name=importAkeneoFiles" />
        </exec>
    </target>

    <target name="cron-gopay" description="Runs GoPay background jobs. Should be executed periodically by system Cron every 5 minutes.">
        <exec executable="${path.php.executable}" passthru="true" checkreturn="true">
            <arg value="${path.bin-console}" />
            <arg value="shopsys:cron" />
            <arg value="--instance-name=gopay" />
        </exec>
    </target>

    <target name="cron-orders" description="Run crons regarding order sync (to bridge, from bridge...). Runs every minute.">
        <exec executable="${path.php.executable}" passthru="true" checkreturn="true">
            <arg value="${path.bin-console}" />
            <arg value="shopsys:cron" />
            <arg value="--instance-name=orders" />
        </exec>
    </target>

    <target name="cron-lock" description="This command will lock cron command so crons will not run until this command is terminated.">
        <exec executable="${path.php.executable}" passthru="true" checkreturn="true">
            <arg value="${path.bin-console}" />
            <arg value="devops:cron:lock" />
        </exec>
    </target>

    <target name="cron-watch" description="Cron Watcher waits until all cron instances are finished.">
        <exec executable="${path.php.executable}" passthru="true" checkreturn="true">
            <arg value="${path.bin-console}" />
            <arg value="devops:cron:watch" />
        </exec>
    </target>


    <target name="clean-opcache" description="Clear PHP Opcache.">
        <exec executable="${path.php.executable}" passthru="true" checkreturn="true">
            <arg value="${path.bin-console}" />
            <arg value="shopsys:clean-opcache" />
        </exec>
    </target>

    <target name="clean-cache" depends="shopsys_framework.clean-cache,environment-load" description="Cleans up all application cache.">
        <if>
            <equals arg1="${environment}" arg2="prod"/>
            <then>
                <phingcall target="clean-opcache" />
            </then>
        </if>
    </target>

    <target name="friendly-url-entity-mapping-check" description="Checks completeness of entity mapping by route name">
        <exec executable="${path.php.executable}" passthru="true" checkreturn="true">
            <arg value="${path.bin-console}"/>
            <arg value="shopsys:friendly-urls:check-entity-mapping"/>
        </exec>
    </target>

    <target name="frontend-api-generate-graphql-schema" description="Generates schema.graphql in root directory">
        <exec executable="${path.php.executable}" passthru="true" checkreturn="true">
            <arg value="${path.bin-console}"/>
            <arg value="graphql:dump-schema"/>
            <arg value="--file"/>
            <arg value="${path.root}/schema.graphql"/>
            <arg value="--format"/>
            <arg value="graphql"/>
            <arg value="--modern"/>
        </exec>
    </target>

    <target name="tests-acceptance-after" description="Actions necessary to run after acceptance tests." hidden="true">
        <available file="${path.env.acc}" type="file" property="path.env.acc.existed"/>
        <if>
            <equals arg1="${path.env.acc.existed}" arg2="true"/>
            <then>
                <delete file="${path.root}/ACCEPTANCE"/>
            </then>
        </if>
        <phingcall target="test-elasticsearch-export"/>
    </target>

    <target name="tests-acceptance-before" description="Actions necessary to run before acceptance tests." hidden="true">
        <available file="${path.env.acc}" type="file" property="path.env.acc.existed"/>
        <if>
            <not>
                <equals arg1="${path.env.acc.existed}" arg2="true"/>
            </not>
            <then>
                <touch file="${path.root}/ACCEPTANCE"/>
            </then>
        </if>
        <phingcall target="test-db-dump"/>
        <phingcall target="acceptance-elasticsearch-export"/>
    </target>

    <target name="tests-functional-single" depends="production-protection,clean,test-clean-redis,domains-info-load" description="Runs functional test.">
        <if>
            <not><isset property="test"/></not>
            <then>
                <input propertyName="test" message="Enter class test name (e.g. ProductFacadeTest) or specific test name (e.g. ProductFacadeTest::testEditSchedulesPriceRecalculation)"/>
            </then>
        </if>
        <if>
            <equals arg1="${test}" arg2=""/>
            <then>
                <fail message="Test name not provided"/>
            </then>
        </if>
        <if>
            <istrue value="${domains-info.is-multidomain}"/>
            <then>
                <exec executable="${path.phpunit.executable}" logoutput="true" passthru="true" checkreturn="true">
                    <arg value="--colors=always"/>
                    <arg value="--testsuite"/>
                    <arg value="Functional"/>
                    <arg value="--exclude-group"/>
                    <arg value="singledomain"/>
                    <arg value="--configuration"/>
                    <arg value="${path.root}/phpunit.xml"/>
                    <arg value="--filter"/>
                    <arg value="${test}"/>
                </exec>
            </then>
            <else>
                <exec executable="${path.phpunit.executable}" logoutput="true" passthru="true" checkreturn="true">
                    <arg value="--colors=always"/>
                    <arg value="--testsuite"/>
                    <arg value="Functional"/>
                    <arg value="--exclude-group"/>
                    <arg value="multidomain"/>
                    <arg value="--configuration"/>
                    <arg value="${path.root}/phpunit.xml"/>
                    <arg value="--filter"/>
                    <arg value="${test}"/>
                </exec>
            </else>
        </if>
    </target>

    <target name="translations-frontend-dump" depends="domains-info-load" description="Extracts translatable messages from front-end source files in your project.">
        <phingcall target="npm-translations-dump"/>
        <exec executable="${path.php.executable}" passthru="true" checkreturn="true" >
            <arg value="${path.bin-console}"/>
            <arg value="translation:extract"/>
            <arg value="--dir=${path.src}"/>
            <arg value="--dir=${path.templates}"/>
            <arg value="--dir=${path.var}/translations/projectBase"/>
            <arg value="--exclude-dir=admin/plugins" />
            <arg value="--exclude-dir=frontend/plugins"/>
            <arg value="--exclude-name=*GridFactory.php" />
            <arg value="--exclude-dir=styleguide/plugins"/>
            <arg value="--exclude-dir=${path.templates}/Admin" />
            <arg value="--exclude-dir=admin" />
            <arg value="--exclude-dir=Admin" />
            <arg value="--exclude-dir=DataFixtures/Demo"/>
            <arg value="--exclude-dir=Transfer/Akeneo"/>
            <arg value="--output-format=po"/>
            <arg value="--output-dir=${path.root}/translations-frontend"/>
            <arg line="${translations.dump.flags}"/>
            <arg line="${domains-info.locales}"/>
        </exec>
    </target>

    <target name="translations-import" description="Import translatable messages from front-end source files in your project.">
        <exec executable="${path.php.executable}" passthru="true" checkreturn="true">
            <arg value="${path.bin-console}"/>
            <arg value="translation:import"/>
            <arg value="${path.root}/translations-update/"/>
            <arg value="${path.root}/translations/"/>
            <arg value="messages" />
            <arg value="validators" />
        </exec>
    </target>

    <target name="npm-install-dependencies" description="Installs node modules dependencies." hidden="true">
        <exec executable="${path.npm.executable}" dir="${path.root}" logoutput="true" passthru="true" checkreturn="true">
            <arg value="ci"/>
        </exec>
    </target>

</project>
