Article:
    type: object
    inherits:
        - 'ArticleDecorator'
    config:
        interfaces:
            - 'Breadcrumb'
            - 'Slug'
            - 'ArticleInterface'
        fields:
            slug:
                type: "String!"
                description: "Article URL slug"
            breadcrumb:
                type: "[Link!]!"
                description: "Hierarchy of the current element in relation to the structure"
            external:
                type: "Boolean!"
                description: "If the the article should be open in a new tab"
            createdAt:
                type: "DateTime!"
                description: "Date and time of the article creation"
