fragment BaseCustomerUserFragment on BaseCustomerUser {
    __typename
    uuid
    firstName
    lastName
    email
    telephone
    telephoneData {
        prefix
        countryCode
        number
    }
    billingAddressUuid
    street
    city
    postcode
    country {
        ...CountryFragment
    }
    newsletterSubscription
    defaultDeliveryAddress {
        ...DeliveryAddressFragment
    }
    deliveryAddresses {
        ...DeliveryAddressFragment
    }
    ... on CompanyCustomerUser {
        companyName
        companyNumber
        companyTaxNumber
    }
    pricingGroup
    hasPasswordSet
    roles
    roleGroup {
        ...CustomerUserRoleGroupFragment
    }
    salesRepresentative {
        __typename
        email
        firstName
        image {
            url
            name
        }
        lastName
        telephone
        telephoneData {
            prefix
            countryCode
            number
        }
        uuid
    }
}
