apiVersion: batch/v1
kind: Job
metadata:
    name: migration
spec:
    template:
        spec:
            volumes:
            -   name: domains-urls
                configMap:
                    name: domains-urls
            -   name: parameters
                configMap:
                    name: parameters

            containers:
            -   name: migration
                image: "{{TAG}}"
                volumeMounts:
                    -   name: domains-urls
                        mountPath: /var/www/html/config/domains_urls.yaml
                        subPath: domains_urls.yaml
                    -   name: parameters
                        mountPath: /var/www/html/config/parameters.yaml
                        subPath: parameters.yaml
                env:
                    -   name: S3_API_HOST
                        value: "{{S3_API_HOST}}"
                    -   name: S3_API_USERNAME
                        value: "{{S3_API_USERNAME}}"
                    -   name: S3_API_PASSWORD
                        value: "{{S3_API_PASSWORD}}"
                    -   name: S3_API_BUCKET_NAME
                        value: "{{S3_API_BUCKET_NAME}}"
                    -   name: CDN_DOMAIN
                        value: "{{CDN_DOMAIN}}"
                    -   name: REDIS_PREFIX
                        value: "{{REDIS_PREFIX}}"
                    -   name: ELASTIC_SEARCH_INDEX_PREFIX
                        value: "{{ELASTIC_SEARCH_INDEX_PREFIX}}"
                command: ["sh", "-c", "cd /var/www/html && ./phing db-migrations-count-with-maintenance build-deploy-part-2-db-dependent"]
            restartPolicy: Never
            imagePullSecrets:
                -   name: dockerregistry
    backoffLimit: 1
