GoPayQuery:
    type: object
    config:
        fields:
            GoPaySwifts:
                type: "[GoPayBankSwift!]!"
                description: "List of available banks for GoPay bank transfer payment"
                resolve: "@=resolver('getGoPaySwifts', [args['currencyCode']])"
                args:
                    currencyCode:
                        type: "String!"
