fragment CartFragment on Cart {
    __typename
    uuid
    items {
        ...CartItemFragment
    }
    totalPrice {
        ...PriceFragment
    }
    totalItemsPrice {
        ...PriceFragment
    }
    totalItemsPriceBeforeDiscount {
        ...PriceFragment
    }
    totalProductPriceAdjustmentsDiscount {
        ...PriceFragment
    }
    totalDiscountPrice {
        ...PriceFragment
    }
    modifications {
        ...CartModificationsFragment
    }
    remainingAmountForFreeTransport
    transport {
        ...TransportWithAvailablePaymentsAndStoresFragment
    }
    payment {
        ...SimplePaymentFragment
    }
    promoCodes {
        ...PromoCodeFragment
    }
    giftVouchers {
        ...AppliedGiftVoucherFragment
    }
    remainingAmountToPay
    remainingItemsAmountToPay
    isNothingLeftToPay
    giftVouchersExceedPayableAmount
    selectedPickupPlaceIdentifier
    paymentGoPayBankSwift
    roundingPrice {
        ...PriceFragment
    }
}
