fragment CartItemFragment on CartItem {
    __typename
    uuid
    quantity
    type
    freeQuantity
    product {
        __typename
        id
        uuid
        slug
        ... on Variant {
            mainVariant {
                slug
                reviewsSummary {
                    __typename
                    averageRating
                    totalCount
                }
            }
        }
        fullName
        catalogNumber
        isInquiryType
        flags {
            ...SimpleFlagFragment
        }
        mainImage {
            ...ImageFragment
        }
        stockQuantity
        isAllowedNegativeStock
        expectedRestockingDate
        availability {
            ...AvailabilityFragment
        }
        promotionBuyQuantity
        promotionFreeQuantity
        price {
            ...ProductPriceFragment
        }
        giftPrice {
            ...ProductPriceFragment
        }
        availableStoresCount
        unit {
            name
        }
        brand {
            ...SimpleBrandFragment
        }
        categories {
            name
        }
        reviewsSummary {
            __typename
            averageRating
            totalCount
        }
        parameters {
            ...ParameterFragment
        }
        vatPercent
    }
}
