fragment CartModificationsFragment on CartModificationsResult {
    __typename
    itemModifications {
        ...CartItemModificationsFragment
    }
    transportModifications {
        ...CartTransportModificationsFragment
    }
    paymentModifications {
        ...CartPaymentModificationsFragment
    }
    promoCodeModifications {
        ...CartPromoCodeModificationsFragment
    }
    giftVoucherModifications {
        ...CartGiftVoucherModificationsFragment
    }
    someProductWasRemovedFromEshop
    multipleAddedProductModifications {
        notAddedProducts {
            fullName
        }
    }
}
