fragment CartItemModificationsFragment on CartItemModificationsResult {
    __typename
    noLongerListableCartItems {
        ...CartItemModificationFragment
    }
    cartItemsWithModifiedPrice {
        ...CartItemModificationFragment
    }
    cartItemsWithChangedQuantity {
        ...CartItemModificationFragment
    }
    cartItemsWithRemovedAdditionalServices {
        ...CartItemModificationFragment
    }
    cartItemsWithModifiedAdditionalServicePrices {
        ...CartItemModificationFragment
    }
}
