CurrentRegularCustomerUserDecorator:
    type: object
    decorator: true
    inherits:
        - 'RegularCustomerUserDecorator'
        - 'CurrentCustomerUserDecorator'
    config:
        description: "Represents a currently logged regular customer user"
        interfaces:
            - 'CurrentCustomerUser'
