CurrentCustomerUserDecorator:
    type: interface
    decorator: true
    inherits:
        - 'BaseCustomerUserDecorator'
    config:
        description: "Represents a common interface for a currently logged customer user (both company and regular)"
        fields:
            loginInfo:
                type: "LoginInfo!"
                description: "Current login information"
