RegularCustomerUserDecorator:
    type: object
    decorator: true
    inherits:
        - 'BaseCustomerUser'
    config:
        description: "Represents a regular customer user"
        interfaces:
            - 'BaseCustomerUser'
