kind: Endpoints
apiVersion: v1
metadata:
    name: elasticsearch
subsets:
    -   addresses:
            -   ip: "{{ELASTICSEARCH_IP_ADDRESS_HOST}}"
        ports:
                -   name: elasticsearch
                    port: {{ELASTICSEARCH_HOST_PORT}}
