kind: Endpoints
apiVersion: v1
metadata:
    name: postgres
subsets:
    -   addresses:
            -   ip: "{{POSTGRES_DATABASE_IP_ADDRESS}}"
        ports:
                -   name: postgres
                    port: 5432
