import { DomainConfig, PublicRuntimeConfig } from 'envConfig';
import { CustomerUserAreaEnum } from 'types/customer';

export const defaultTestDomainConfig: DomainConfig = {
    url: 'https://test1.example.com/',
    publicGraphqlEndpoint: '',
    defaultLocale: 'en',
    currencyCode: 'EUR',
    fallbackTimezone: 'UTC',
    domainId: 1,
    mapSetting: { latitude: 0, longitude: 0, zoom: 10 },
    gtmId: '',
    isLuigisBoxActive: false,
    type: CustomerUserAreaEnum.B2C,
    packeteryCountry: 'cz',
};

export const defaultTestConfig: PublicRuntimeConfig = {
    errorDebuggingLevel: 'no-debug',
    domains: [
        {
            url: 'https://test1.example.com/',
            publicGraphqlEndpoint: '',
            defaultLocale: 'en',
            currencyCode: 'EUR',
            fallbackTimezone: 'UTC',
            domainId: 1,
            mapSetting: { latitude: 0, longitude: 0, zoom: 10 },
            gtmId: '',
            isLuigisBoxActive: false,
            type: CustomerUserAreaEnum.B2C,
            packeteryCountry: 'cz',
        },
        {
            url: 'https://test2.example.com/',
            publicGraphqlEndpoint: '',
            defaultLocale: 'cs',
            currencyCode: 'CZK',
            fallbackTimezone: 'UTC',
            domainId: 2,
            mapSetting: { latitude: 0, longitude: 0, zoom: 10 },
            gtmId: '',
            isLuigisBoxActive: false,
            type: CustomerUserAreaEnum.B2B,
            packeteryCountry: 'cz',
        },
        {
            url: 'https://test3.example.com/',
            publicGraphqlEndpoint: '',
            defaultLocale: 'sk',
            currencyCode: 'EUR',
            fallbackTimezone: 'UTC',
            domainId: 3,
            mapSetting: { latitude: 0, longitude: 0, zoom: 10 },
            gtmId: '',
            isLuigisBoxActive: false,
            type: CustomerUserAreaEnum.B2B,
            packeteryCountry: 'sk',
        },
    ],
    cdnDomain: '',
    shouldUseDefer: false,
    userSnapEnabledDefaultValue: false,
    userSnapApiKey: '',
    googleMapApiKey: '',
    packeteryApiKey: '',
    showSymfonyToolbar: '',
    sentryDsn: '',
    sentryEnvironment: '',
    sentryRelease: '',
    sentryFeedbackEnable: false,
    sentryReplaysEnable: false,
};
