query SettingsQuery @redisCache(ttl: 3600) {
    settings {
        pricing {
            __typename
            defaultCurrencyCode
            minimumFractionDigits
        }
        seo {
            __typename
            title
            titleAddOn
            metaDescription
        }
        contactFormMainText
        emailTransportDescription
        displayTimezone
        heurekaEnabled
        productReviewsEnabled
        mainBlogCategoryData {
            mainBlogCategoryName
            mainBlogCategoryUrl
            mainBlogCategoryMainImage {
                url
            }
        }
        privacyPolicyArticleUrl
        productReviewPolicyArticleUrl
        productReviewMinimalAverageRatingForListing
        termsAndConditionsArticleUrl
        userConsentPolicyArticleUrl
        socialNetworkLoginConfig
        cspHeader
        defaultPricingGroupId
    }
}
