export const VISIBLE_SLIDER_ITEMS = 6;
export const VISIBLE_SLIDER_ITEMS_BASKET_POPUP = 4;
export const VISIBLE_SLIDER_ITEMS_LAST_VISITED = 9;
export const VISIBLE_SLIDER_ITEMS_ARTICLE = 3;
export const VISIBLE_SLIDER_ITEMS_AUTOCOMPLETE = 5;
