query FlagQuery($uuid: Uuid, $firstProducts: Int!, $filter: ProductFilter) {
    flag(uuid: $uuid) {
        name
        rgbColor
        seo {
            title
            metaDescription
            h1
            metaRobots
            canonicalUrl
        }
        slug
        breadcrumb {
            name
            slug
        }
        products (first: $firstProducts, filter: $filter) {
            orderingMode
            edges {
                node {
                    name
                }
            }
        }
        categories (productFilter: $filter) {
            name
        }
    }
}
