fragment ListedProductFragment on Product {
    __typename
    id
    uuid
    slug
    fullName
    stockQuantity
    isAllowedNegativeStock
    unit {
        __typename
        name
    }
    isSellingDenied
    isCurrentlyOutOfStock
    flags {
        ...SimpleFlagFragment
    }
    mainImage {
        __typename
        url
    }
    price {
        ...ListedProductPriceFragment
    }
    availability {
        ...AvailabilityFragment
    }
    availableStoresCount
    catalogNumber
    brand {
        __typename
        name
    }
    categories {
        __typename
        name
    }
    isMainVariant
    isInquiryType

    ... on MainVariant {
        variantsCount
    }
}
