fragment ProductDetailInterfaceFragment on Product {
    __typename
    id
    uuid
    slug
    fullName
    name
    namePrefix
    nameSuffix
    breadcrumb {
        ...BreadcrumbFragment
    }
    catalogNumber
    ean
    description
    unit {
        name
    }
    images {
        ...ImageFragment
    }
    price {
        ...ProductPriceFragment
    }
    parameters {
        ...ParameterFragment
    }
    accessories {
        ...ListedProductFragment
    }
    brand {
        ...SimpleBrandFragment
    }
    zboziCategory
    categories {
        name
    }
    promotionBuyQuantity
    promotionFreeQuantity
    flags {
        ...SimpleFlagFragment
    }
    isSellingDenied
    isCurrentlyOutOfStock
    expectedRestockingDate
    availability {
        ...AvailabilityFragment
    }
    stockQuantity
    isAllowedNegativeStock
    seoTitle
    seoMetaDescription
    hreflangLinks {
        ...HreflangLinksFragment
    }
    isMainVariant
    isInquiryType
    productVideos {
        ...VideoTokenFragment
    }
    relatedProducts {
        ...ListedProductFragment
    }
    files {
        ...FileFragment
    }
    gifts {
        ...ProductGiftFragment
    }
    reviewsSummary {
        ...ProductReviewsSummaryFragment
    }
}
