mutation AddOrderItemsToCart(
    $orderUuid: Uuid!,
    $orderUrlHash: String,
    $cartUuid: Uuid,
    $shouldMerge: Boolean
) {
    AddOrderItemsToCart(
        input: {
            orderUuid: $orderUuid,
            orderUrlHash: $orderUrlHash,
            cartUuid: $cartUuid,
            shouldMerge: $shouldMerge
        }) {
        uuid
        items {
            quantity
            product {
                name
            }
        }
        modifications {
            multipleAddedProductModifications {
                notAddedProducts {
                    name
                }
            }
        }
    }
}
