mutation ApplyPromoCodeToCart(
    $promoCode: String!,
    $cartUuid: Uuid,
) {
    ApplyPromoCodeToCart(
        input: {
            cartUuid: $cartUuid
            promoCode: $promoCode
        }) {
        uuid
        promoCodes {
            code
            type
            discount {
                priceWithVat
                priceWithoutVat
                vatAmount
            }
        }
        totalPrice {
            priceWithVat
            priceWithoutVat
            vatAmount
        }
    }
}
