query ReadyCategorySeoMix($slug: String!) {
    slug(slug: $slug) {
        ... on Category {
            products {
                productFilterOptions {
                    parameters {
                        uuid
                        __typename
                        ...on ParameterCheckboxFilterOption {
                            values {
                                text
                                isSelected
                            }
                        }
                    }
                    flags {
                        flag {
                            uuid
                        }
                        isSelected
                    }
                }
            }
        }
    }
}
