web_profiler_profiler:
    prefix: /_profiler
    resource: '@WebProfilerBundle/Resources/config/routing/profiler.php'
web_profiler_wdt:
    prefix: /_wdt
    resource: '@WebProfilerBundle/Resources/config/routing/wdt.php'
