type AddProductResult {
  notOnStockQuantity: Int!
  overLimitQuantity: Int
  isQuantityOverLimit: Boolean
  isNew: Boolean!
  addedQuantity: Int!
}

input AddToCartInput {
  """
  Cart identifier, new cart will be created if not provided and customer is not logged in
  """
  cartUuid: Uuid = null

  """Represents a transport in order"""
  transport: TransportInput = null

  """Represents a payment in order"""
  payment: PaymentInput = null
  promoCode: String = null

  """Product UUID"""
  productUuid: Uuid!

  """Item quantity"""
  quantity: Int!

  """
  True if quantity should be set no matter the current state of the cart. False
  if quantity should be added to the already existing same item in the cart
  """
  isAbsoluteQuantity: Boolean = false
}

type AddToCartResult {
  """UUID of the cart, null for authenticated user"""
  uuid: Uuid

  """All items in the cart"""
  items: [CartItem!]!

  """Selected transport if transport provided"""
  transport: Transport

  """Selected payment if payment provided"""
  payment: Payment
  modifications: CartModificationsResult!
  totalPrice: Price!
  totalDiscountPrice: Price!

  """
  Remaining amount for free transport and payment; null = transport cannot be free
  """
  remainingAmountWithVatForFreeTransport: Money
  addProductResult: AddProductResult!
}

interface Advert {
  """UUID"""
  uuid: Uuid!

  """Name of advert"""
  name: String!

  """Type of advert"""
  type: String!

  """Position of advert"""
  positionName: String!
}

type AdvertCode implements Advert {
  """UUID"""
  uuid: Uuid!

  """Name of advert"""
  name: String!

  """Type of advert"""
  type: String!

  """Position of advert"""
  positionName: String!

  """Advert code"""
  code: String!
}

type AdvertImage implements Advert {
  """UUID"""
  uuid: Uuid!

  """Name of advert"""
  name: String!

  """Type of advert"""
  type: String!

  """Position of advert"""
  positionName: String!

  """Advert link"""
  link: String

  """Advert image"""
  image(type: String = null, size: String = null, sizes: [String!] = null): [Image]!
}

type AdvertPosition {
  """Desription of advert position"""
  description: String!

  """Position of advert"""
  positionName: String!
}

type Article implements Breadcrumb & Slug & ArticleInterface {
  """UUID"""
  uuid: Uuid!

  """Placement of article"""
  placement: String!

  """Name of article"""
  name: String!

  """Text of article"""
  text: String

  """Seo first level heading of article"""
  seoH1: String

  """Seo title of article"""
  seoTitle: String

  """Seo meta description of article"""
  seoMetaDescription: String

  """Article URL slug"""
  slug: String!

  """Hierarchy of the current element in relation to the structure"""
  breadcrumb: [Link!]!
}

"""A connection to a list of items."""
type ArticleConnection {
  """Total number of articles"""
  totalCount: Int!

  """Information to aid in pagination."""
  pageInfo: PageInfo!

  """Information to aid in pagination."""
  edges: [ArticleEdge]
}

"""An edge in a connection."""
type ArticleEdge {
  """The item at the end of the edge."""
  node: Article

  """A cursor for use in pagination."""
  cursor: String!
}

"""Represents entity that is considered to be an article on the eshop"""
interface ArticleInterface {
  uuid: Uuid!
  name: String
  slug: String!
  text: String
  seoTitle: String
  seoMetaDescription: String
  seoH1: String
  breadcrumb: [Link!]!
}

"""Represents an availability"""
type Availability {
  """Localized availability name (domain dependent)"""
  name: String

  """Availability status in a format suitable for usage in the code"""
  status: String!
}

type BlogArticle implements Breadcrumb & Slug & ArticleInterface {
  """The blog article UUID"""
  uuid: Uuid!

  """The blog article title"""
  name: String!

  """The blog article text"""
  text: String

  """Date and time of the blog article creation"""
  createdAt: DateTime!

  """Indicates whether the blog article is displayed on homepage"""
  visibleOnHomepage: Boolean!

  """Date and time of the blog article publishing"""
  publishDate: DateTime!

  """The blog article perex"""
  perex: String

  """The blog article SEO title"""
  seoTitle: String

  """The blog article SEO meta description"""
  seoMetaDescription: String

  """The blog article SEO H1 heading"""
  seoH1: String

  """The list of the blog article blog categories"""
  blogCategories: [BlogCategory!]!

  """The blog article absolute URL"""
  link: String!

  """The blog article URL slug"""
  slug: String!

  """The list of the products assigned to the blog article"""
  products: [Product!]!

  """Hierarchy of the current element in relation to the structure"""
  breadcrumb: [Link!]!

  """Blog article image"""
  image(type: String = null, sizes: [String!] = null): Image
}

"""A connection to a list of items."""
type BlogArticleConnection {
  """Total number of the blog articles"""
  totalCount: Int!

  """Information to aid in pagination."""
  pageInfo: PageInfo!

  """Information to aid in pagination."""
  edges: [BlogArticleEdge]
}

"""An edge in a connection."""
type BlogArticleEdge {
  """The item at the end of the edge."""
  node: BlogArticle

  """A cursor for use in pagination."""
  cursor: String!
}

type BlogCategory implements Breadcrumb & Slug {
  """The blog category UUID"""
  uuid: Uuid!

  """The blog category name"""
  name: String!

  """The blog category description"""
  description: String

  """The blog category parent"""
  parent: BlogCategory

  """The blog category children"""
  children: [BlogCategory!]!

  """The blog category SEO title"""
  seoTitle: String

  """The blog category SEO meta description"""
  seoMetaDescription: String

  """The blog category SEO H1 heading"""
  seoH1: String

  """Paginated blog articles of the given blog category"""
  blogArticles(after: String, first: Int, before: String, last: Int, onlyHomepageArticles: Boolean = false): BlogArticleConnection

  """The blog category absolute URL"""
  link: String!

  """The blog category URL slug"""
  slug: String!

  """Hierarchy of the current element in relation to the structure"""
  breadcrumb: [Link!]!
}

"""Represents a brand"""
type Brand implements Breadcrumb & Slug {
  """UUID"""
  uuid: Uuid!

  """Brand name"""
  name: String!

  """Brand description"""
  description: String

  """Brand main URL"""
  link: String!

  """Brand SEO title"""
  seoTitle: String

  """Brand SEO meta description"""
  seoMetaDescription: String

  """Brand SEO H1"""
  seoH1: String

  """Brand images"""
  images(type: String = null, size: String, sizes: [String!] = null): [Image]!

  """Paginated and ordered products of brand"""
  products(after: String, first: Int, before: String, last: Int, orderingMode: ProductOrderingModeEnum, filter: ProductFilter, search: String): ProductConnection

  """Brand URL slug"""
  slug: String!

  """Hierarchy of the current element in relation to the structure"""
  breadcrumb: [Link!]!
}

"""Brand filter option"""
type BrandFilterOption {
  """Brand"""
  brand: Brand!

  """
  Count of products that will be filtered if this filter option is applied.
  """
  count: Int!

  """
  If true than count parameter is number of products that will be displayed if
  this filter option is applied, if false count parameter is number of products
  that will be added to current products result.
  """
  isAbsolute: Boolean!
}

"""Represents entity able to return breadcrumb"""
interface Breadcrumb {
  """Hierarchy of the current element in relation to the structure"""
  breadcrumb: [Link!]!
}

type Cart {
  """UUID of the cart, null for authenticated user"""
  uuid: Uuid

  """All items in the cart"""
  items: [CartItem!]!

  """Selected transport if transport provided"""
  transport: Transport

  """Selected payment if payment provided"""
  payment: Payment
  modifications: CartModificationsResult!
  totalPrice: Price!
  totalDiscountPrice: Price!

  """
  Remaining amount for free transport and payment; null = transport cannot be free
  """
  remainingAmountWithVatForFreeTransport: Money
}

input CartInput {
  """
  Cart identifier, new cart will be created if not provided and customer is not logged in
  """
  cartUuid: Uuid = null

  """Represents a transport in order"""
  transport: TransportInput = null

  """Represents a payment in order"""
  payment: PaymentInput = null
  promoCode: String = null
}

"""Represent one item in the cart"""
type CartItem {
  """Product in the cart"""
  product: Product!

  """Cart item UUID"""
  uuid: Uuid!

  """Quantity of items in the cart"""
  quantity: Int!
}

type CartItemModificationsResult {
  noLongerListableCartItems: [CartItem!]!
  cartItemsWithModifiedPrice: [CartItem!]!
  cartItemsWithChangedQuantity: [CartItem!]!
  noLongerAvailableCartItemsDueToQuantity: [CartItem!]!
}

type CartModificationsResult {
  itemModifications: CartItemModificationsResult!
  transportModifications: CartTransportModificationsResult!
  paymentModifications: CartPaymentModificationsResult!
}

type CartPaymentModificationsResult {
  paymentPriceChanged: Boolean!
  paymentUnavailable: Boolean!
}

type CartTransportModificationsResult {
  transportPriceChanged: Boolean!
  transportUnavailable: Boolean!
  transportWeightLimitExceeded: Boolean!
  personalPickupStoreUnavailable: Boolean!
}

"""Represents a category"""
type Category implements Breadcrumb & Slug {
  """UUID"""
  uuid: Uuid!

  """Localized category name (domain dependent)"""
  name: String

  """Descendant categories"""
  children: [Category!]!

  """Ancestor category"""
  parent: Category

  """Category images"""
  images(type: String = null, size: String, sizes: [String!] = null): [Image!]!

  """Paginated and ordered products of category"""
  products(after: String, first: Int, before: String, last: Int, orderingMode: ProductOrderingModeEnum, filter: ProductFilter, search: String): ProductConnection

  """Seo first level heading of category"""
  seoH1: String

  """Seo title of category"""
  seoTitle: String

  """Seo meta description of category"""
  seoMetaDescription: String

  """Best selling products"""
  bestsellers: [Product!]!

  """Category URL slug"""
  slug: String!

  """Hierarchy of the current element in relation to the structure"""
  breadcrumb: [Link!]!

  """An array of links of prepared category SEO mixes of a given category"""
  readyCategorySeoMixLinks: [Link!]!

  """A list of categories linked to the given category"""
  linkedCategories: [Category!]!
}

"""A connection to a list of items."""
type CategoryConnection {
  """Total number of categories"""
  totalCount: Int!

  """Information to aid in pagination."""
  pageInfo: PageInfo!

  """Information to aid in pagination."""
  edges: [CategoryEdge]
}

"""An edge in a connection."""
type CategoryEdge {
  """The item at the end of the edge."""
  node: Category

  """A cursor for use in pagination."""
  cursor: String!
}

input ChangePasswordInput {
  """Customer user email."""
  email: String!

  """Current customer user password."""
  oldPassword: Password!

  """New customer user password."""
  newPassword: Password!
}

input ChangePersonalDataInput {
  """Customer user first name"""
  firstName: String!

  """Customer user last name"""
  lastName: String!

  """The customer's telephone number"""
  telephone: String!

  """Billing address street name (will be on the tax invoice)"""
  street: String!

  """Billing address city name (will be on the tax invoice)"""
  city: String!

  """Billing address zip code (will be on the tax invoice)"""
  postcode: String!

  """
  Billing address country code in ISO 3166-1 alpha-2 (Country will be on the tax invoice)
  """
  country: String!

  """Whether customer user should receive newsletters or not"""
  newsletterSubscription: Boolean!
}

"""Represents an currently logged customer user"""
type CompanyCustomerUser implements CustomerUser {
  """UUID"""
  uuid: Uuid!

  """First name"""
  firstName: String!

  """Last name"""
  lastName: String!

  """Email address"""
  email: String!

  """Phone number"""
  telephone: String

  """Billing address street name"""
  street: String!

  """Billing address city name"""
  city: String!

  """Billing address zip code"""
  postcode: String!

  """Billing address country code"""
  country: String!

  """Whether customer user receives newsletters or not"""
  newsletterSubscription: Boolean!

  """Default customer delivery addresses"""
  defaultDeliveryAddress: DeliveryAddress

  """List of delivery addresses"""
  deliveryAddresses: [DeliveryAddress!]!

  """The customer’s company name (only when customer is a company)"""
  companyName: String

  """
  The customer’s company identification number (only when customer is a company)
  """
  companyNumber: String

  """The customer’s company tax number (only when customer is a company)"""
  companyTaxNumber: String
}

"""Represents country"""
type Country {
  """Localized country name"""
  name: String!

  """Country code in ISO 3166-1 alpha-2"""
  code: String!
}

"""Represents an currently logged customer user"""
interface CustomerUser {
  """UUID"""
  uuid: Uuid!

  """First name"""
  firstName: String!

  """Last name"""
  lastName: String!

  """Email address"""
  email: String!

  """Phone number"""
  telephone: String

  """Billing address street name"""
  street: String!

  """Billing address city name"""
  city: String!

  """Billing address zip code"""
  postcode: String!

  """Billing address country code"""
  country: String!

  """Whether customer user receives newsletters or not"""
  newsletterSubscription: Boolean!

  """Default customer delivery addresses"""
  defaultDeliveryAddress: DeliveryAddress

  """List of delivery addresses"""
  deliveryAddresses: [DeliveryAddress!]!
}

"""Represents and encapsulates an ISO-8601 encoded UTC date-time value"""
scalar DateTime

type DeliveryAddress {
  """UUID"""
  uuid: Uuid

  """Delivery address company name"""
  companyName: String!

  """Delivery address street name"""
  street: String!

  """Delivery address city name"""
  city: String!

  """Delivery address zip code"""
  postcode: String!

  """Delivery address telephone"""
  telephone: String!

  """Delivery address country code"""
  country: String!

  """Delivery address firstname"""
  firstName: String!

  """Delivery address lastname"""
  lastName: String!
}

"""Represents a downloadable file"""
type File {
  """Clickable text for a hyperlink"""
  anchorText: String!

  """Url to download the file"""
  url: String!
}

"""Represents a flag"""
type Flag implements Breadcrumb & Slug {
  """UUID"""
  uuid: Uuid!

  """Localized flag name (domain dependent)"""
  name: String

  """Flag color in rgb format"""
  rgbColor: String!

  """URL slug of flag"""
  slug: String!

  """Paginated and ordered products of flag"""
  products(after: String, first: Int, before: String, last: Int, orderingMode: ProductOrderingModeEnum, filter: ProductFilter, search: String): ProductConnection

  """Hierarchy of the current element in relation to the structure"""
  breadcrumb: [Link!]!

  """Categories containing at least one product with flag"""
  categories(productFilter: ProductFilter): [Category!]!
}

"""Flag filter option"""
type FlagFilterOption {
  """Flag"""
  flag: Flag!

  """
  Count of products that will be filtered if this filter option is applied.
  """
  count: Int!

  """
  If true than count parameter is number of products that will be displayed if
  this filter option is applied, if false count parameter is number of products
  that will be added to current products result.
  """
  isAbsolute: Boolean!
}

type GoPayPaymentMethod {
  """Identifier of payment method"""
  identifier: String!

  """Name of payment method"""
  name: String!

  """URL to normal size image of payment method"""
  imageNormalUrl: String!

  """URL to large size image of payment method"""
  imageLargeUrl: String!

  """Group of payment methods"""
  paymentGroup: String!
}

"""Represents an image"""
type Image {
  """Position of image in list"""
  position: Int

  """Image type"""
  type: String
  sizes: [ImageSize!]!
}

"""Represents a single image size"""
type ImageSize {
  """Image size defined in images.yaml"""
  size: String!

  """URL address of image"""
  url: String!

  """Width in pixels defined in images.yaml"""
  width: Int

  """Height in pixels defined in images.yaml"""
  height: Int
}

"""Represents an internal link"""
type Link {
  """Clickable text for a hyperlink"""
  name: String!

  """Target URL slug"""
  slug: String!
}

input LoginInput {
  """The user email."""
  email: String!

  """The user password."""
  password: Password!
}

"""Represents a product"""
type MainVariant implements Product & Breadcrumb & Slug {
  """UUID"""
  uuid: Uuid!

  """Localized product name (domain dependent)"""
  name: String

  """Localized product short description (domain dependent)"""
  shortDescription: String

  """Product link"""
  link: String!
  unit: Unit!
  isUsingStock: Boolean!
  availability: Availability!

  """Count of quantity on stock"""
  stockQuantity: Int!

  """List of categories"""
  categories: [Category!]!

  """List of flags"""
  flags: [Flag!]!

  """Product price"""
  price: ProductPrice!

  """Product images"""
  images(type: String = null, size: String, sizes: [String!] = null): [Image!]!

  """Brand of product"""
  brand: Brand
  isSellingDenied: Boolean!
  orderingPriority: Int!
  description: String
  accessories: [Product]
  parameters: [Parameter]!

  """Seo first level heading of product"""
  seoH1: String

  """Seo title of product"""
  seoTitle: String

  """Seo meta description of product"""
  seoMetaDescription: String

  """Product URL slug"""
  slug: String!

  """Product catalog number"""
  catalogNumber: String!

  """Product part number"""
  partNumber: String

  """EAN"""
  ean: String

  """List of product's unique selling propositions"""
  usps: [String!]!

  """Name prefix"""
  namePrefix: String

  """Name suffix"""
  nameSuffix: String

  """
  The full name of the product, which consists of a prefix, name, and a suffix
  """
  fullName: String!

  """Distinguishes if the product can be pre-ordered"""
  hasPreorder: Boolean!

  """Distinguishes if the product can be bought"""
  hasSaleExclusion: Boolean!

  """List of downloadable files"""
  files: [File!]!

  """List of availabilities in individual stores"""
  storeAvailabilities: [StoreAvailability!]!

  """Number of the stores where the product is available"""
  availableStoresCount: Int!

  """Number of the stores where the product is exposed"""
  exposedStoresCount: Int!

  """Hierarchy of the current element in relation to the structure"""
  breadcrumb: [Link!]!

  """List of related products"""
  relatedProducts: [Product!]!
  variants: [Variant!]!
}

"""Represents and encapsulates monetary value"""
scalar Money

type Mutation {
  """Creates complete order with products and addresses"""
  CreateOrder(input: OrderInput!): Order!

  """Login user and return access and refresh tokens"""
  Login(input: LoginInput!): Token!

  """Logout user"""
  Logout: Boolean!

  """Refreshes access and refresh tokens"""
  RefreshTokens(input: RefreshTokenInput!): Token!

  """Changes customer user password"""
  ChangePassword(input: ChangePasswordInput!): CustomerUser!

  """Changes customer user personal data"""
  ChangePersonalData(input: ChangePersonalDataInput!): CustomerUser!

  """Register new customer user"""
  Register(input: RegistrationDataInput!): Token!

  """Subscribe for e-mail newsletter"""
  NewsletterSubscribe(input: NewsletterSubscriptionDataInput!): Boolean!

  """Add product to cart for future checkout"""
  AddToCart(input: AddToCartInput!): AddToCartResult!

  """Remove product from cart"""
  RemoveFromCart(input: RemoveFromCartInput!): Cart!

  """Request password recovery - email with hash will be sent"""
  RequestPasswordRecovery(email: String!): String!

  """Recover password using hash required from RequestPasswordRecovery"""
  RecoverPassword(input: RecoverPasswordInput!): Token!

  """Request access to personal data"""
  RequestPersonalDataAccess(input: PersonalDataAccessRequestInput!): PersonalDataPage!
}

"""Represents a navigation structure item"""
type NavigationItem {
  """Localized navigation item name (domain dependent)"""
  name: String!

  """Target URL"""
  link: String!

  """Categories separated into columns"""
  categoriesByColumns: [NavigationItemCategoriesByColumns!]!
}

"""Represents a single column inside the navigation item"""
type NavigationItemCategoriesByColumns {
  """Column number"""
  columnNumber: Int!

  """Categories"""
  categories: [Category!]!
}

type NewsletterSubscriber {
  """Subscribed email address"""
  email: String!

  """Date and time of subscription"""
  createdAt: DateTime!
}

"""Represents the main input object to subscribe for e-mail newsletter"""
input NewsletterSubscriptionDataInput {
  email: String!
}

"""Represents a notification supposed to be displayed on all pages"""
type NotificationBar {
  """Message of the notification"""
  text: String!

  """Color of the notification"""
  rgbColor: String!

  """Notification bar images"""
  images(type: String = null, sizes: [String!] = null): [Image]!
}

type Order {
  """UUID"""
  uuid: Uuid!

  """Unique order number"""
  number: String!

  """Date and time when the order was created"""
  creationDate: DateTime!

  """All items in the order including payment and transport"""
  items: [OrderItem!]!

  """Transport method applied to the order"""
  transport: Transport!

  """Payment method applied to the order"""
  payment: Payment!

  """Current status of the order"""
  status: String!

  """Total price of the order including transport and payment prices"""
  totalPrice: Price!

  """The customer's first name"""
  firstName: String

  """The customer's last name"""
  lastName: String

  """The customer's email address"""
  email: String!

  """The customer's telephone number"""
  telephone: String!

  """The customer’s company name (only when ordered on the company behalf)"""
  companyName: String

  """
  The customer’s company identification number (only when ordered on the company behalf)
  """
  companyNumber: String

  """
  The customer’s company tax number (only when ordered on the company behalf)
  """
  companyTaxNumber: String

  """Billing address street name """
  street: String!

  """Billing address city name"""
  city: String!

  """Billing address zip code"""
  postcode: String!

  """Billing address country code"""
  country: String!

  """
  Indicates whether the billing address is other than a delivery address
  """
  differentDeliveryAddress: Boolean!

  """First name of the contact person for delivery"""
  deliveryFirstName: String

  """Last name of the contact person for delivery"""
  deliveryLastName: String

  """Company name for delivery"""
  deliveryCompanyName: String

  """Contact telephone number for delivery"""
  deliveryTelephone: String

  """Street name for delivery"""
  deliveryStreet: String

  """City name for delivery"""
  deliveryCity: String

  """Zip code for delivery"""
  deliveryPostcode: String

  """Country code for delivery"""
  deliveryCountry: String

  """Other information related to the order"""
  note: String

  """Unique url hash that can be used to """
  urlHash: String!

  """Promo code (coupon) used in the order"""
  promoCode: String

  """The order tracking number"""
  trackingNumber: String

  """The order tracking link"""
  trackingUrl: String
}

"""A connection to a list of items."""
type OrderConnection {
  """Total number of orders"""
  totalCount: Int!

  """Information to aid in pagination."""
  pageInfo: PageInfo!

  """Information to aid in pagination."""
  edges: [OrderEdge]
}

"""An edge in a connection."""
type OrderEdge {
  """The item at the end of the edge."""
  node: Order

  """A cursor for use in pagination."""
  cursor: String!
}

"""Represents the main input object to create orders"""
input OrderInput {
  """The customer's first name"""
  firstName: String!

  """The customer's last name"""
  lastName: String!

  """The customer's email address"""
  email: String!

  """The customer's phone number"""
  telephone: String!

  """Determines whether the order is made on the company behalf."""
  onCompanyBehalf: Boolean!

  """The customer’s company name (required when onCompanyBehalf is true)"""
  companyName: String

  """
  The customer’s company identification number (required when onCompanyBehalf is true)
  """
  companyNumber: String

  """
  The customer’s company tax number (required when onCompanyBehalf is true)
  """
  companyTaxNumber: String

  """Billing address street name (will be on the tax invoice)"""
  street: String!

  """Billing address city name (will be on the tax invoice)"""
  city: String!

  """Billing address zip code (will be on the tax invoice)"""
  postcode: String!

  """
  Billing address country code in ISO 3166-1 alpha-2 (Country will be on the tax invoice)
  """
  country: String!

  """
  Determines whether to deliver products to a different address than the billing one
  """
  differentDeliveryAddress: Boolean!

  """
  First name of the contact person for delivery (required when differentDeliveryAddress is true)
  """
  deliveryFirstName: String

  """
  Last name of the contact person for delivery (required when differentDeliveryAddress is true)
  """
  deliveryLastName: String

  """Company name for delivery"""
  deliveryCompanyName: String

  """Contact telephone number for delivery"""
  deliveryTelephone: String

  """
  Street name for delivery (required when differentDeliveryAddress is true)
  """
  deliveryStreet: String

  """
  City name for delivery (required when differentDeliveryAddress is true)
  """
  deliveryCity: String

  """
  Zip code for delivery (required when differentDeliveryAddress is true)
  """
  deliveryPostcode: String

  """
  Country code in ISO 3166-1 alpha-2 for delivery (required when differentDeliveryAddress is true)
  """
  deliveryCountry: String

  """Other information related to the order"""
  note: String

  """Payment method applied to the order"""
  payment: PaymentInput!

  """Transport method applied to the order"""
  transport: TransportInput!

  """
  Deprecated, this field is not used, the products are taken from the server cart instead.
  """
  products: [OrderProductInput!]

  """Cart identifier used for getting carts of not logged customers"""
  cartUuid: Uuid = null

  """The promo code used in the order"""
  promoCode: String
}

"""Represent one item in the order"""
type OrderItem {
  """Name of the order item"""
  name: String!

  """Order item price per unit"""
  unitPrice: Price!

  """Total price for the quantity of order item"""
  totalPrice: Price!

  """Applied VAT rate percentage applied to the order item"""
  vatRate: String!

  """Quantity of order items in the order"""
  quantity: Int!

  """Unit of measurement used for the order item"""
  unit: String
}

"""Represents a product in order"""
input OrderProductInput {
  """UUID"""
  uuid: Uuid!

  """Quantity of products"""
  quantity: Int!

  """Product price per unit"""
  unitPrice: PriceInput!
}

"""Information about pagination in a connection."""
type PageInfo {
  """When paginating forwards, are there more items?"""
  hasNextPage: Boolean!

  """When paginating backwards, are there more items?"""
  hasPreviousPage: Boolean!

  """When paginating backwards, the cursor to continue."""
  startCursor: String

  """When paginating forwards, the cursor to continue."""
  endCursor: String
}

"""Represents a parameter"""
type Parameter {
  """UUID"""
  uuid: Uuid!

  """Parameter name"""
  name: String!
  visible: Boolean!
  values: [ParameterValue!]!

  """Parameter group to which the parameter is assigned"""
  group: String

  """Unit of the parameter"""
  unit: Unit
}

"""Represents a parameter filter"""
input ParameterFilter {
  """Uuid of filtered parameter"""
  parameter: Uuid!

  """Array of uuids filtered parameter values"""
  values: [Uuid!]!
}

"""Parameter filter option"""
type ParameterFilterOption {
  """UUID"""
  uuid: Uuid!

  """Parameter name"""
  name: String!

  """Is parameter visible for customers"""
  visible: Boolean!

  """Filter options of parameter values"""
  values: [ParameterValueFilterOption!]!
  type: String!
  unit: Unit
}

"""Represents a parameter value"""
type ParameterValue {
  """UUID"""
  uuid: Uuid!

  """Parameter value"""
  text: String!
}

"""Parameter value filter option"""
type ParameterValueFilterOption {
  """UUID"""
  uuid: Uuid!

  """Parameter value"""
  text: String!

  """
  Count of products that will be filtered if this filter option is applied.
  """
  count: Int!

  """
  If true than count parameter is number of products that will be displayed if
  this filter option is applied, if false count parameter is number of products
  that will be added to current products result.
  """
  isAbsolute: Boolean!

  """RGB hex of color parameter"""
  rgbHex: String
}

"""Represents and encapsulates a string for password"""
scalar Password

"""Represents a payment"""
type Payment {
  """UUID"""
  uuid: Uuid!

  """Payment name"""
  name: String!

  """Localized payment description (domain dependent)"""
  description: String

  """Localized payment instruction (domain dependent)"""
  instruction: String

  """Payment position"""
  position: Int!

  """Payment price"""
  price(cartUuid: Uuid = null): Price!

  """Payment images"""
  images(type: String = null, size: String, sizes: [String!] = null): [Image]!

  """List of assigned transports"""
  transports: [Transport!]!

  """Type of payment"""
  type: String!

  """Additional data for GoPay payment"""
  goPayPaymentMethod: GoPayPaymentMethod
}

"""Represents a payment in order"""
input PaymentInput {
  """UUID"""
  uuid: Uuid!

  """Price for payment"""
  price: PriceInput!
}

type PersonalData {
  """Customer orders"""
  orders: [Order!]!

  """Customer user data"""
  customerUser: CustomerUser

  """Newsletter subscription"""
  newsletterSubscriber: NewsletterSubscriber
}

input PersonalDataAccessRequestInput {
  """The customer's email address"""
  email: String!

  """
  One of two possible types for personal data access request - display or export
  """
  type: PersonalDataAccessRequestTypeEnum
}

"""One of two possible types for personal data access request"""
enum PersonalDataAccessRequestTypeEnum {
  """Display data"""
  display

  """Export data"""
  export
}

type PersonalDataPage {
  """
  The HTML content of the site where a customer can request displaying his personal data
  """
  displaySiteContent: String!

  """URL slug of display site"""
  displaySiteSlug: String!

  """
  The HTML content of the site where a customer can request exporting his personal data
  """
  exportSiteContent: String!

  """URL slug of export site"""
  exportSiteSlug: String!
}

"""Represents the price"""
type Price {
  """Price with VAT"""
  priceWithVat: Money!

  """Price without VAT"""
  priceWithoutVat: Money!

  """Total value of VAT"""
  vatAmount: Money!
}

"""Represents the price"""
input PriceInput {
  """Price with VAT"""
  priceWithVat: Money!

  """Price without VAT"""
  priceWithoutVat: Money!

  """Total value of VAT"""
  vatAmount: Money!
}

"""Represents a product"""
interface Product {
  """UUID"""
  uuid: Uuid!

  """Localized product name (domain dependent)"""
  name: String

  """Localized product short description (domain dependent)"""
  shortDescription: String

  """Product link"""
  link: String!
  unit: Unit!
  isUsingStock: Boolean!
  availability: Availability!

  """Count of quantity on stock"""
  stockQuantity: Int!

  """List of categories"""
  categories: [Category!]!

  """List of flags"""
  flags: [Flag!]!

  """Product price"""
  price: ProductPrice!

  """Product images"""
  images(type: String = null, size: String, sizes: [String!] = null): [Image!]!

  """Brand of product"""
  brand: Brand
  isSellingDenied: Boolean!
  orderingPriority: Int!
  description: String
  accessories: [Product]
  parameters: [Parameter]!

  """Seo first level heading of product"""
  seoH1: String

  """Seo title of product"""
  seoTitle: String

  """Seo meta description of product"""
  seoMetaDescription: String

  """Product URL slug"""
  slug: String!

  """Product catalog number"""
  catalogNumber: String!

  """Product part number"""
  partNumber: String

  """EAN"""
  ean: String

  """List of product's unique selling propositions"""
  usps: [String!]!

  """Name prefix"""
  namePrefix: String

  """Name suffix"""
  nameSuffix: String

  """
  The full name of the product, which consists of a prefix, name, and a suffix
  """
  fullName: String!

  """Distinguishes if the product can be pre-ordered"""
  hasPreorder: Boolean!

  """Distinguishes if the product can be bought"""
  hasSaleExclusion: Boolean!

  """List of downloadable files"""
  files: [File!]!

  """List of availabilities in individual stores"""
  storeAvailabilities: [StoreAvailability!]!

  """Number of the stores where the product is available"""
  availableStoresCount: Int!

  """Number of the stores where the product is exposed"""
  exposedStoresCount: Int!

  """Hierarchy of the current element in relation to the structure"""
  breadcrumb: [Link!]!

  """List of related products"""
  relatedProducts: [Product!]!
}

"""A connection to a list of items."""
type ProductConnection {
  """Total number of products"""
  totalCount: Int!
  productFilterOptions: ProductFilterOptions!

  """Information to aid in pagination."""
  pageInfo: PageInfo!

  """Information to aid in pagination."""
  edges: [ProductEdge]
}

"""An edge in a connection."""
type ProductEdge {
  """The item at the end of the edge."""
  node: Product

  """A cursor for use in pagination."""
  cursor: String!
}

"""Represents a product filter"""
input ProductFilter {
  """Minimal price filter"""
  minimalPrice: Money

  """Maximal price filter"""
  maximalPrice: Money

  """Array of uuids of brands filter"""
  brands: [Uuid!]

  """Array of uuids of flags filter"""
  flags: [Uuid!]

  """Only in stock filter"""
  onlyInStock: Boolean

  """Parameter filter"""
  parameters: [ParameterFilter!]
}

"""Represents a product filter options"""
type ProductFilterOptions {
  """Minimal price of products for filtering"""
  minimalPrice: Money!

  """Maximal price of products for filtering"""
  maximalPrice: Money!

  """Brands filter options"""
  brands: [BrandFilterOption!]

  """Flags filter options"""
  flags: [FlagFilterOption!]

  """Number of products in stock that will be filtered"""
  inStock: Int!

  """Parameter filter options"""
  parameters: [ParameterFilterOption!]
}

"""One of possible ordering modes for product"""
enum ProductOrderingModeEnum {
  """Order by priority"""
  PRIORITY

  """Order by price ascending"""
  PRICE_ASC

  """Order by price descending"""
  PRICE_DESC

  """Order by name ascending"""
  NAME_ASC

  """Order by name descending"""
  NAME_DESC

  """Order by relevance"""
  RELEVANCE
}

"""Represents the price of the product"""
type ProductPrice {
  """Price with VAT"""
  priceWithVat: Money!

  """Price without VAT"""
  priceWithoutVat: Money!

  """Total value of VAT"""
  vatAmount: Money!

  """Determines whether it's a final price or starting price"""
  isPriceFrom: Boolean!
}

type Query {
  """Returns complete list of categories"""
  categories: [Category!]!

  """
  Returns list of searched categories that can be paginated using `first`, `last`, `before` and `after` keywords
  """
  categoriesSearch(after: String, first: Int, before: String, last: Int, search: String!): CategoryConnection

  """
  Returns list of ordered products that can be paginated using `first`, `last`, `before` and `after` keywords
  """
  products(after: String, first: Int, before: String, last: Int, orderingMode: ProductOrderingModeEnum, filter: ProductFilter, search: String): ProductConnection

  """Returns product filtered using UUID or URL slug"""
  product(uuid: Uuid, urlSlug: String): Product
  RegularProduct: RegularProduct
  MainVariant: MainVariant
  Variant: Variant

  """Returns category filtered using UUID or URL slug"""
  category(uuid: Uuid, urlSlug: String): Category

  """Returns complete list of payment methods"""
  payments: [Payment!]!

  """Returns payment filtered using UUID"""
  payment(uuid: Uuid!): Payment

  """Returns available transport methods based on the current cart state"""
  transports(cartUuid: Uuid): [Transport!]!

  """Returns complete list of transport methods"""
  transport(uuid: Uuid!): Transport

  """Returns currently logged in customer user"""
  currentCustomerUser: CustomerUser!

  """
  Returns list of orders that can be paginated using `first`, `last`, `before` and `after` keywords
  """
  orders(after: String, first: Int, before: String, last: Int): OrderConnection

  """Returns order filtered using UUID or urlHash"""
  order(uuid: Uuid, urlHash: String): Order

  """
  Returns list of articles that can be paginated using `first`, `last`, `before`
  and `after` keywords and filtered by `placement`
  """
  articles(after: String, first: Int, before: String, last: Int, placement: String): ArticleConnection

  """Returns article filtered using UUID or URL slug"""
  article(uuid: Uuid, urlSlug: String): Article

  """Returns Terms and Conditions article"""
  termsAndConditionsArticle: Article

  """Returns privacy policy article"""
  privacyPolicyArticle: Article

  """Returns information about cookies article"""
  cookiesArticle: Article

  """Returns complete list of brands"""
  brands: [Brand!]!

  """Returns brand filtered using UUID or URL slug"""
  brand(uuid: Uuid, urlSlug: String): Brand

  """Returns promoted products"""
  promotedProducts: [Product!]!

  """Returns list of adverts, optionally filtered by `positionName`"""
  adverts(positionName: String): [Advert!]!
  AdvertCode: AdvertCode
  AdvertImage: AdvertImage

  """Returns list of advert positions."""
  advertPositions: [AdvertPosition!]!

  """Returns complete navigation menu"""
  navigation: [NavigationItem!]!
  CompanyCustomerUser: CompanyCustomerUser
  RegularCustomerUser: RegularCustomerUser

  """Returns promoted categories"""
  promotedCategories: [Category!]!

  """
  Returns list of stores that can be paginated using `first`, `last`, `before` and `after` keywords
  """
  stores(after: String, first: Int, before: String, last: Int): StoreConnection

  """Returns store filtered using UUID or URL slug"""
  store(uuid: Uuid, urlSlug: String): Store

  """Returns blog article filtered using UUID or URL slug"""
  blogArticle(uuid: Uuid, urlSlug: String): BlogArticle

  """
  Returns a list of the blog articles that can be paginated using `first`, `last`, `before` and `after` keywords
  """
  blogArticles(after: String, first: Int, before: String, last: Int, onlyHomepageArticles: Boolean = false): BlogArticleConnection

  """Returns blog category filtered using UUID or URL slug"""
  blogCategory(uuid: Uuid, urlSlug: String): BlogCategory

  """Returns a complete list of the blog categories"""
  blogCategories: [BlogCategory!]!

  """Returns a complete list of the slider items"""
  sliderItems: [SliderItem!]!

  """Returns entity by slug"""
  slug(slug: String!): Slug

  """Returns a list of notifications supposed to be displayed on all pages"""
  notificationBars: [NotificationBar!]

  """Returns list of searched articles and blog articles"""
  articlesSearch(search: String!): [ArticleInterface]

  """Return cart of logged customer or cart by UUID for anonymous user"""
  cart(cartInput: CartInput = {cartUuid: null}): Cart

  """Returns a complete list of the flags"""
  flags: [Flag!]

  """Returns a flag by uuid or url slug"""
  flag(uuid: Uuid, urlSlug: String): Flag

  """Return personal data page content and URL"""
  personalDataPage: PersonalDataPage

  """
  Access personal data using hash received in email from personal data access request
  """
  accessPersonalData(
    """Hash to securely recognize access"""
    hash: String!
  ): PersonalData!

  """Returns available countries"""
  countries: [Country!]!

  """Returns list of searched brands"""
  brandSearch(search: String!): [Brand!]!
}

input RecoverPasswordInput {
  """Customer user email."""
  email: String!

  """Hash"""
  hash: String!

  """New customer user password."""
  newPassword: Password!
}

input RefreshTokenInput {
  """The refresh token."""
  refreshToken: String!
}

"""Represents the main input object to register customer user"""
input RegistrationDataInput {
  """Customer user first name"""
  firstName: String!

  """Customer user last name"""
  lastName: String!

  """The customer's email address"""
  email: String!

  """Customer user password"""
  password: Password!

  """The customer's telephone number"""
  telephone: String!

  """Billing address street name (will be on the tax invoice)"""
  street: String!

  """Billing address city name (will be on the tax invoice)"""
  city: String!

  """Billing address zip code (will be on the tax invoice)"""
  postcode: String!

  """
  Billing address country code in ISO 3166-1 alpha-2 (Country will be on the tax invoice)
  """
  country: String!

  """Determines whether the registered customer is a company or not."""
  companyCustomer: Boolean!

  """The customer’s company name (required when companyCustomer is true)"""
  companyName: String

  """
  The customer’s company identification number (required when companyCustomer is true)
  """
  companyNumber: String

  """
  The customer’s company tax number (required when companyCustomer is true)
  """
  companyTaxNumber: String

  """Whether customer user should receive newsletters or not"""
  newsletterSubscription: Boolean!
}

"""Represents an currently logged customer user"""
type RegularCustomerUser implements CustomerUser {
  """UUID"""
  uuid: Uuid!

  """First name"""
  firstName: String!

  """Last name"""
  lastName: String!

  """Email address"""
  email: String!

  """Phone number"""
  telephone: String

  """Billing address street name"""
  street: String!

  """Billing address city name"""
  city: String!

  """Billing address zip code"""
  postcode: String!

  """Billing address country code"""
  country: String!

  """Whether customer user receives newsletters or not"""
  newsletterSubscription: Boolean!

  """Default customer delivery addresses"""
  defaultDeliveryAddress: DeliveryAddress

  """List of delivery addresses"""
  deliveryAddresses: [DeliveryAddress!]!
}

"""Represents a product"""
type RegularProduct implements Product & Breadcrumb & Slug {
  """UUID"""
  uuid: Uuid!

  """Localized product name (domain dependent)"""
  name: String

  """Localized product short description (domain dependent)"""
  shortDescription: String

  """Product link"""
  link: String!
  unit: Unit!
  isUsingStock: Boolean!
  availability: Availability!

  """Count of quantity on stock"""
  stockQuantity: Int!

  """List of categories"""
  categories: [Category!]!

  """List of flags"""
  flags: [Flag!]!

  """Product price"""
  price: ProductPrice!

  """Product images"""
  images(type: String = null, size: String, sizes: [String!] = null): [Image!]!

  """Brand of product"""
  brand: Brand
  isSellingDenied: Boolean!
  orderingPriority: Int!
  description: String
  accessories: [Product]
  parameters: [Parameter]!

  """Seo first level heading of product"""
  seoH1: String

  """Seo title of product"""
  seoTitle: String

  """Seo meta description of product"""
  seoMetaDescription: String

  """Product URL slug"""
  slug: String!

  """Product catalog number"""
  catalogNumber: String!

  """Product part number"""
  partNumber: String

  """EAN"""
  ean: String

  """List of product's unique selling propositions"""
  usps: [String!]!

  """Name prefix"""
  namePrefix: String

  """Name suffix"""
  nameSuffix: String

  """
  The full name of the product, which consists of a prefix, name, and a suffix
  """
  fullName: String!

  """Distinguishes if the product can be pre-ordered"""
  hasPreorder: Boolean!

  """Distinguishes if the product can be bought"""
  hasSaleExclusion: Boolean!

  """List of downloadable files"""
  files: [File!]!

  """List of availabilities in individual stores"""
  storeAvailabilities: [StoreAvailability!]!

  """Number of the stores where the product is available"""
  availableStoresCount: Int!

  """Number of the stores where the product is exposed"""
  exposedStoresCount: Int!

  """Hierarchy of the current element in relation to the structure"""
  breadcrumb: [Link!]!

  """List of related products"""
  relatedProducts: [Product!]!
}

input RemoveFromCartInput {
  """
  Cart identifier, new cart will be created if not provided and customer is not logged in
  """
  cartUuid: Uuid = null

  """Represents a transport in order"""
  transport: TransportInput = null

  """Represents a payment in order"""
  payment: PaymentInput = null
  promoCode: String = null

  """Cart item UUID"""
  cartItemUuid: Uuid!
}

type SliderItem {
  """UUID"""
  uuid: Uuid!

  """Slider name"""
  name: String!

  """Target link"""
  link: String!

  """Text below slider"""
  extendedText: String

  """Target link of text below slider"""
  extendedTextLink: String

  """GTM ID"""
  gtmId: String!

  """GTM creative"""
  gtmCreative: String

  """Slider item images"""
  images(type: String = null, sizes: [String!] = null): [Image!]!
}

"""Represents entity retrievable by slug"""
interface Slug {
  """UUID"""
  uuid: Uuid!
  name: String
  slug: String!
}

type Store implements Breadcrumb & Slug {
  """Store URL slug"""
  slug: String!

  """UUID"""
  uuid: Uuid!

  """Is set as default store"""
  isDefault: Boolean!

  """Store name"""
  name: String!

  """Store description"""
  description: String

  """Store address street"""
  street: String!

  """Store address city"""
  city: String!

  """Store address postcode"""
  postcode: String!

  """Store address country code"""
  country: String!

  """Store opening hours"""
  openingHours: String
  contactInfo: String
  specialMessage: String

  """Store location latitude"""
  locationLatitude: String

  """Store location longitude"""
  locationLongitude: String

  """Hierarchy of the current element in relation to the structure"""
  breadcrumb: [Link!]!
}

"""Represents an availability in an individual store"""
type StoreAvailability {
  """Name of the store"""
  storeName: String!

  """Is product exposed on this store"""
  exposed: Boolean!

  """Detailed information about availability"""
  availabilityInformation: String!

  """Availability status in a format suitable for usage in the code"""
  availabilityStatus: String!
}

"""A connection to a list of items."""
type StoreConnection {
  """Total number of stores"""
  totalCount: Int!

  """Information to aid in pagination."""
  pageInfo: PageInfo!

  """Information to aid in pagination."""
  edges: [StoreEdge]
}

"""An edge in a connection."""
type StoreEdge {
  """The item at the end of the edge."""
  node: Store

  """A cursor for use in pagination."""
  cursor: String!
}

type Token {
  accessToken: String!
  refreshToken: String!
}

"""Represents a transport"""
type Transport {
  """UUID"""
  uuid: Uuid!

  """Transport name"""
  name: String!

  """Localized transport description (domain dependent)"""
  description: String

  """Localized transport instruction (domain dependent)"""
  instruction: String

  """Transport position"""
  position: Int!

  """Transport price"""
  price(cartUuid: Uuid = null): Price!

  """Transport images"""
  images(type: String = null, size: String, sizes: [String!] = null): [Image]!

  """List of assigned payments"""
  payments: [Payment!]!

  """Number of days until goods are delivered"""
  daysUntilDelivery: Int!

  """Type of transport"""
  transportType: TransportType!

  """Stores available for personal pickup"""
  stores: StoreConnection
}

"""Represents a transport in order"""
input TransportInput {
  """UUID"""
  uuid: Uuid!

  """Price for transport"""
  price: PriceInput!

  """The identifier of selected personal pickup place"""
  pickupPlaceIdentifier: String = null
}

"""Represents a transport type"""
type TransportType {
  """Name of transport type"""
  name: String!

  """Code of transport"""
  code: String!
}

"""Represents a unit"""
type Unit {
  """Localized unit name (domain dependent)"""
  name: String
}

"""Represents and encapsulates an ISO-8601 encoded UTC date-time value"""
scalar Uuid

"""Represents a product"""
type Variant implements Product & Breadcrumb & Slug {
  """UUID"""
  uuid: Uuid!

  """Localized product name (domain dependent)"""
  name: String

  """Localized product short description (domain dependent)"""
  shortDescription: String

  """Product link"""
  link: String!
  unit: Unit!
  isUsingStock: Boolean!
  availability: Availability!

  """Count of quantity on stock"""
  stockQuantity: Int!

  """List of categories"""
  categories: [Category!]!

  """List of flags"""
  flags: [Flag!]!

  """Product price"""
  price: ProductPrice!

  """Product images"""
  images(type: String = null, size: String, sizes: [String!] = null): [Image!]!

  """Brand of product"""
  brand: Brand
  isSellingDenied: Boolean!
  orderingPriority: Int!
  description: String
  accessories: [Product]
  parameters: [Parameter]!

  """Seo first level heading of product"""
  seoH1: String

  """Seo title of product"""
  seoTitle: String

  """Seo meta description of product"""
  seoMetaDescription: String

  """Product URL slug"""
  slug: String!

  """Product catalog number"""
  catalogNumber: String!

  """Product part number"""
  partNumber: String

  """EAN"""
  ean: String

  """List of product's unique selling propositions"""
  usps: [String!]!

  """Name prefix"""
  namePrefix: String

  """Name suffix"""
  nameSuffix: String

  """
  The full name of the product, which consists of a prefix, name, and a suffix
  """
  fullName: String!

  """Distinguishes if the product can be pre-ordered"""
  hasPreorder: Boolean!

  """Distinguishes if the product can be bought"""
  hasSaleExclusion: Boolean!

  """List of downloadable files"""
  files: [File!]!

  """List of availabilities in individual stores"""
  storeAvailabilities: [StoreAvailability!]!

  """Number of the stores where the product is available"""
  availableStoresCount: Int!

  """Number of the stores where the product is exposed"""
  exposedStoresCount: Int!

  """Hierarchy of the current element in relation to the structure"""
  breadcrumb: [Link!]!

  """List of related products"""
  relatedProducts: [Product!]!
  mainVariant: MainVariant
}
