OrderStepsAccessQuery:
    type: object
    config:
        fields:
            orderStepsAccessibility:
                type: "OrderStepsAccessibility!"
                args:
                    cartInput:
                        type: CartInput
                        validation: cascade
                resolve: "@=resolver('checkOrderStepsAccessibility', [args])"
                description: "Checks whether user can access the transport and payment or the contact info steps"
