NotificationBarQuery:
    type: object
    config:
        fields:
            notificationBars:
                type: '[NotificationBar!]'
                resolve: "@=resolver('notificationBars')"
                description: "Returns a list of notifications supposed to be displayed on all pages"
