apiVersion: apps/v1
kind: Deployment
metadata:
    name: storefront
spec:
    replicas: 1
    selector:
        matchLabels:
            app: storefront
    template:
        metadata:
            labels:
                app: storefront
        spec:
            containers:
                -   name: storefront
                    image: "{{STOREFRONT_TAG}}"
                    ports:
                        -   name: storefront
                            containerPort: 3000
                            protocol: TCP
            imagePullSecrets:
                -   name: dockerregistry
