CoordinatesDecorator:
    type: input-object
    decorator: true
    config:
        fields:
            latitude:
                type: "Float!"
            longitude:
                type: "Float!"
