services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            Overblog\DataLoader\DataLoaderInterface $productsVisibleByIdsBatchLoader: '@products_visible_by_ids_batch_loader'
            Overblog\DataLoader\DataLoaderInterface $productsSellableByIdsBatchLoader: '@products_sellable_by_ids_batch_loader'
            Overblog\DataLoader\DataLoaderInterface $productsByEntitiesBatchLoader: '@products_by_entities_batch_loader'
            Overblog\DataLoader\DataLoaderInterface $imagesBatchLoader: '@images_batch_loader'
            Overblog\DataLoader\DataLoaderInterface $readyCategorySeoMixesBatchLoader: '@ready_category_seo_mixes_batch_loader'
            Overblog\DataLoader\DataLoaderInterface $categoryChildrenBatchLoader: '@category_children_batch_loader'
            Overblog\DataLoader\DataLoaderInterface $linkedCategoriesBatchLoader: '@linked_categories_batch_loader'
            Overblog\DataLoader\DataLoaderInterface $categoriesBatchLoader: '@categories_batch_loader'
            Overblog\DataLoader\DataLoaderInterface $flagsBatchLoader: '@flags_batch_loader'
            Overblog\DataLoader\DataLoaderInterface $brandsBatchLoader: '@brands_batch_loader'
            Overblog\DataLoader\DataLoaderInterface $orderItemsBatchLoader: '@order_items_batch_loader'

    resolverMaps:
        namespace: App\FrontendApi\
        resource: '../src/FrontendApi/**/*{Map}.php'
        tags:
            - { name: overblog_graphql.resolver_map, schema: default }

    App\FrontendApi\:
        resource: '../src/FrontendApi/**/*{Mutation,Resolver,Mapper}.php'

    Shopsys\FrontendApiBundle\Model\Resolver\Products\PromotedProductsResolver:
        alias: App\FrontendApi\Model\Resolver\Products\PromotedProductsResolver
        public: true

    Shopsys\FrontendApiBundle\Model\Product\ProductFacade:
        alias: App\FrontendApi\Model\Product\ProductFacade

    Shopsys\FrontendApiBundle\Model\Product\Filter\ProductFilterDataMapper:
        alias: App\FrontendApi\Model\Product\Filter\ProductFilterDataMapper

    Shopsys\FrontendApiBundle\Model\Order\OrderDataFactory:
        alias: App\FrontendApi\Model\Order\OrderDataFactory

    Shopsys\FrontendApiBundle\Model\Resolver\Products\DataMapper\ProductArrayFieldMapper:
        alias: App\FrontendApi\Model\Resolver\Products\DataMapper\ProductArrayFieldMapper

    Shopsys\FrontendApiBundle\Model\Resolver\Products\DataMapper\ProductEntityFieldMapper:
        alias: App\FrontendApi\Model\Resolver\Products\DataMapper\ProductEntityFieldMapper

    Shopsys\FrontendApiBundle\Model\Resolver\Products\ProductResolverMap:
        alias: App\FrontendApi\Model\Resolver\Products\ProductResolverMap

    Shopsys\FrontendApiBundle\Model\Parameter\ParameterWithValuesFactory:
        alias: App\FrontendApi\Model\Parameter\ParameterWithValuesFactory

    Shopsys\FrontendApiBundle\Model\Mutation\Customer\User\CustomerUserMutation:
        alias: App\FrontendApi\Mutation\Customer\User\CustomerUserMutation

    Shopsys\FrontendApiBundle\Model\Customer\User\CustomerUserUpdateDataFactory:
        alias: App\FrontendApi\Model\Customer\User\CustomerUserUpdateDataFactory

    Shopsys\FrontendApiBundle\Model\Resolver\Order\OrderResolverMap:
        alias: App\FrontendApi\Model\Order\OrderResolverMap

    Shopsys\FrontendApiBundle\Model\Resolver\Category\CategoryResolverMap:
        alias: App\FrontendApi\Model\Resolver\Category\CategoryResolverMap

    Shopsys\FrontendApiBundle\Model\Product\Filter\ProductFilterOptionsFactory:
        alias: App\FrontendApi\Model\Product\Filter\ProductFilterOptionsFactory

    Shopsys\FrontendApiBundle\Model\Resolver\Products\ProductsResolver:
        alias: App\FrontendApi\Model\Resolver\Products\ProductsResolver
        public: true

    Shopsys\FrontendApiBundle\Model\Resolver\Category\CategoryResolver:
        alias: App\FrontendApi\Model\Resolver\Category\CategoryResolver
        public: true

    Shopsys\FrontendApiBundle\Model\Resolver\Article\ArticleResolver:
        alias: App\FrontendApi\Model\Resolver\Article\ArticleResolver
        public: true

    Shopsys\FrontendApiBundle\Model\Resolver\Article\ArticlesResolver:
        alias: App\FrontendApi\Model\Resolver\Article\ArticlesResolver
        public: true

    Shopsys\FrontendApiBundle\Model\Mutation\Order\CreateOrderMutation:
        alias: App\FrontendApi\Mutation\Order\CreateOrderMutation

    Shopsys\FrontendApiBundle\Model\Order\PlaceOrderFacade:
        alias: App\FrontendApi\Model\Order\PlaceOrderFacade

    Shopsys\FrontendApiBundle\Model\Product\Filter\ProductFilterFacade:
        alias: App\FrontendApi\Model\Product\Filter\ProductFilterFacade

    Shopsys\FrontendApiBundle\Model\Product\Connection\ProductConnectionFactory:
        alias: App\FrontendApi\Model\Product\Connection\ProductConnectionFactory

    Shopsys\FrontendApiBundle\Model\Resolver\Price\PriceResolver:
        alias: App\FrontendApi\Model\Resolver\Price\PriceResolver
        public: true

    Shopsys\FrontendApiBundle\Model\Resolver\Transport\TransportsResolver:
        alias: App\FrontendApi\Model\Resolver\Transport\TransportsResolver
        public: true

    Shopsys\FrontendApiBundle\Model\Resolver\Category\CategoriesSearchResolver:
        alias: App\FrontendApi\Model\Resolver\Category\CategoriesSearchResolver
        public: true

    Shopsys\FrontendApiBundle\Model\Resolver\Order\OrdersResolver:
        alias: App\FrontendApi\Model\Resolver\Order\OrdersResolver
        public: true

    Shopsys\FrontendApiBundle\Model\Resolver\Order\OrderResolver:
        alias: App\FrontendApi\Model\Resolver\Order\OrderResolver
        public: true

    Shopsys\FrontendApiBundle\Model\Order\OrderFacade:
        alias: App\FrontendApi\Model\Order\OrderFacade

    Shopsys\FrontendApiBundle\Model\Order\OrderRepository:
        alias: App\FrontendApi\Model\Order\OrderRepository

    Shopsys\FrontendApiBundle\Model\Mutation\Login\LoginMutation:
        alias: App\FrontendApi\Mutation\Login\LoginMutation
        public: true

    Shopsys\FrontendApiBundle\Model\Resolver\Brand\BrandsResolver:
        alias: App\FrontendApi\Model\Resolver\Brand\BrandsResolver
        public: true

    Shopsys\FrontendApiBundle\Model\Resolver\Category\CategoriesResolver:
        alias: App\FrontendApi\Model\Resolver\Category\CategoriesResolver
        public: true

    Shopsys\FrontendApiBundle\Component\Image\ImageFacade:
        alias: App\FrontendApi\Model\Image\ImageFacade

    Shopsys\FrontendApiBundle\Model\Category\CategoryFacade:
        alias: App\FrontendApi\Model\Category\CategoryFacade

    Shopsys\FrontendApiBundle\Model\Mutation\Login\RefreshTokensMutation:
        alias: App\FrontendApi\Mutation\Login\RefreshTokensMutation
