query FlagProductsFilterOptions($flagUuid: Uuid!) {
    flag(uuid: $flagUuid) {
        uuid
        products {
            productFilterOptions {
                ...FlagProductFilterOptions
            }
        }
    }
}

fragment FlagProductFilterOptions on ProductFilterOptions {
    minimalPrice
    maximalPrice
    inStock
    flags {
        flag {
            name
        }
        count
        isAbsolute
    }
    brands {
        brand {
            name
        }
        count
        isAbsolute
    }
}
