mutation ApplyPromoCodeToCart(
    $cartUuid: Uuid
    $promoCode: String!
) {
    ApplyPromoCodeToCart(input: {
        cartUuid: $cartUuid
        promoCode: $promoCode
    }) {
        uuid
        promoCode {
            code
            type
        }
        transport {
            price {
                priceWithVat
                priceWithoutVat
                vatAmount
            }
        }
        payment {
            price {
                priceWithVat
                priceWithoutVat
                vatAmount
            }
        }
        remainingAmountForFreeTransport
    }
}
