SeoPageDecorator:
    type: object
    decorator: true
    config:
        interfaces:
            - "Hreflang"
            - "Seo"
        description: "Represents SEO settings for specific page"
        fields:
            seo:
                type: "SeoAttributes!"
                description: "SEO attributes of the page"
            ogTitle:
                type: "String"
                description: "Title for og:title meta tag"
            ogDescription:
                type: "String"
                description: "Description for og:description meta tag"
            ogImage:
                type: "Image"
                description: "Image for og image meta tag by params"
                resolve: '@=query("ogImageBySeoPageQuery", value)'
            hreflangLinks:
                type: "[HreflangLink!]!"
                description: "Alternate links for hreflang meta tags"
