#!/usr/bin/env php
<?php

$phingPharFilepath = __DIR__ . '/phing.phar';

if (!file_exists($phingPharFilepath)) {
    echo "Error: $phingPharFilepath not found.\n";
    echo "Please run: composer install\n";
    exit(1);
}

// turn off html errors
ini_set('html_errors', 'off');

putenv("PHING_HOME=" . realpath(dirname($phingPharFilepath) . '/../'));

require_once $phingPharFilepath;
