query OrdersQuery (
    $after: String
    $filter: OrderFilterInput
    $first: Int
    $statuslessFilter: OrderFilterInput
){
    orders (after: $after, filter: $filter, first: $first) {
        __typename
        totalCount
        pageInfo {
            ...PageInfoFragment
        }
        edges {
            __typename
            node {
                ...ListedOrderFragment
            }
            cursor
        }
    }
    orderStatusCounts(filter: $statuslessFilter) {
        status {
            code
            type
            name
        }
        count
    }
}
