query ProductReviewsQuery(
    $productUuid: Uuid!
    $first: Int
    $after: String
    $orderingMode: ProductReviewOrderingModeEnum
) {
    productReviews(productUuid: $productUuid, first: $first, after: $after, orderingMode: $orderingMode) {
        totalCount
        orderingMode
        summary {
            ...ProductReviewsSummaryFragment
        }
        pageInfo {
            ...PageInfoFragment
        }
        edges {
            cursor
            node {
                ...ProductReviewFragment
            }
        }
    }
}
