query CurrentCustomerUserQuery {
    currentCustomerUser {
        __typename
        firstName
        lastName
        email
        telephone
        street
        city
        postcode
        country {
            ...CountryFragment
        }
        newsletterSubscription
        defaultDeliveryAddress {
            ...DeliveryAddressFragment
        }
        deliveryAddresses {
            ...DeliveryAddressFragment
        }
        ... on CompanyCustomerUser {
            companyName
            companyNumber
            companyTaxNumber
        }
    }
}
