<?php

declare(strict_types=1);

namespace Shopsys\ProductFeed\ZboziBundle\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Override;
use Shopsys\MigrationBundle\Component\Doctrine\Migrations\AbstractMigration;

class Version20260504143000 extends AbstractMigration
{
    #[Override]
    public function up(Schema $schema): void
    {
        $this->sql('
            CREATE TABLE zbozi_category (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                zbozi_id INT NOT NULL,
                name VARCHAR(255) DEFAULT NULL,
                full_name VARCHAR(500) DEFAULT NULL,
                locale VARCHAR(255) NOT NULL,
                PRIMARY KEY(id)
            )');
        $this->sql('CREATE UNIQUE INDEX uq_zbozi_category_zbozi_id_locale ON zbozi_category (locale, zbozi_id)');
        $this->sql('
            CREATE TABLE zbozi_category_categories (
                zbozi_category_id INT NOT NULL,
                category_id INT NOT NULL,
                PRIMARY KEY(zbozi_category_id, category_id)
            )');
        $this->sql('CREATE INDEX IDX_BCD81DA1B1309E16 ON zbozi_category_categories (zbozi_category_id)');
        $this->sql('CREATE INDEX IDX_BCD81DA112469DE2 ON zbozi_category_categories (category_id)');
        $this->sql('
            ALTER TABLE
                zbozi_category_categories
            ADD
                CONSTRAINT FK_B50745E31FDC062E FOREIGN KEY (zbozi_category_id) REFERENCES zbozi_category (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->sql('
            ALTER TABLE
                zbozi_category_categories
            ADD
                CONSTRAINT FK_B50745E312469DE2 FOREIGN KEY (category_id) REFERENCES categories (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }
}
