CountryQuery:
    type: object
    config:
        fields:
            countries:
                type: '[Country!]!'
                resolve: "@=resolver('resolveCountries')"
                description: "Returns available countries"
