ArticleDecorator:
    type: object
    decorator: true
    config:
        fields:
            uuid:
                type: "Uuid!"
                description: "UUID"
            placement:
                type: "String!"
                description: "Placement of article"
            name:
                type: "String!"
                description: "Name of article"
            text:
                type: "String"
                description: "Text of article"
            seo:
                type: "SeoAttributes!"
                description: "SEO attributes of the article page"
