OrderFilterInputDecorator:
    type: input-object
    decorator: true
    config:
        description: "Filter orders"
        fields:
            createdAfter:
                type: "DateTime"
                description: "Filter orders created after this date"
            createdBefore:
                type: "DateTime"
                description: "Filter orders created before this date"
            search:
                type: "String"
                description: "Filter orders by order number or product"
            statusCodes:
                type: "[String!]"
                description: "Filter orders by status codes"
            orderItemsCatnum:
                type: "String"
                description: "Filter orders by order items with product catalog number (OR condition with orderItemsProductUuid)"
            orderItemsProductUuid:
                type: "Uuid"
                description: "Filter orders by order items with product UUID (OR condition with orderItemsCatnum)"
