front_cart:
    path: /kosik
    defaults: { _controller: App\Controller\Front\CartController:indexAction }

front_contact:
    path: /kontakt
    defaults: { _controller: App\Controller\Front\ContactFormController:indexAction }

front_customer_edit:
    path: /zakaznik/upravit-udaje
    defaults: { _controller: App\Controller\Front\CustomerController:editAction }

front_customer_orders:
    path: /zakaznik/objednavky
    defaults: { _controller: App\Controller\Front\CustomerController:ordersAction }

front_customer_order_detail_registered:
    path: /zakaznik/detail-objednavky/{orderNumber}
    defaults: { _controller: App\Controller\Front\CustomerController:orderDetailRegisteredAction }

front_customer_order_detail_unregistered:
    path: /detail-objednavky/{urlHash}
    defaults: { _controller: App\Controller\Front\CustomerController:orderDetailUnregisteredAction }

front_login:
    path: /prihlaseni
    defaults: { _controller: App\Controller\Front\LoginController:loginAction }

front_logout:
    # controller's action is unnecessary, because firewall processes whole request
    path: /odhlasit/{_csrf_token}

front_order_index:
    path: /objednavka
    defaults: { _controller: App\Controller\Front\OrderController:indexAction }

front_order_paid:
    path: /potvrzeni-platby-objednavky/{urlHash}
    defaults: { _controller: App\Controller\Front\OrderController:paidAction }

front_order_not_paid:
    path: /nezaplacena-objednavka/{urlHash}
    defaults: { _controller: App\Controller\Front\OrderController:notPaidAction }

front_order_gopay_status_notify:
    path: /order/gopay-status-notify/{orderId}
    defaults: { _controller: App\Controller\Front\GoPayController:gopayStatusNotifyAction }
    methods: [GET]

front_order_repeat_gopay_payment:
    path: /opakovat-platbu/{urlHash}
    defaults: { _controller: App\Controller\Front\OrderController:repeatGoPayPaymentAction }

front_order_sent:
    path: /potvrzeni-objednavky
    defaults: { _controller: App\Controller\Front\OrderController:sentAction }

front_product_search:
    path: /hledani
    defaults: { _controller: App\Controller\Front\ProductController:searchAction }

front_registration_register:
    path: /registrace
    defaults: { _controller: App\Controller\Front\RegistrationController:registerAction }

front_registration_reset_password:
    path: /zapomenute-heslo
    defaults: { _controller: App\Controller\Front\CustomerPasswordController:resetPasswordAction }

front_registration_set_new_password:
    path: /nove-heslo
    defaults: { _controller: App\Controller\Front\CustomerPasswordController:setNewPasswordAction }

front_brand_list:
    path: /prehled-znacek
    defaults: { _controller: App\Controller\Front\BrandController:listAction }

front_personal_data:
    path: /prehled-osobnich-udaju
    defaults: { _controller: App\Controller\Front\PersonalDataController:indexAction }

front_personal_data_access:
    path: /prehled-osobnich-udaju/{hash}
    defaults: { _controller: App\Controller\Front\PersonalDataController:accessDisplayAction }

front_personal_data_export:
    path: /export-osobnich-udaju
    defaults: { _controller: App\Controller\Front\PersonalDataController:exportAction }

front_personal_data_access_export:
    path: /export-osobnich-udaju/{hash}
    defaults: { _controller: App\Controller\Front\PersonalDataController:accessExportAction }

front_productseries_list:
    path: /nabytkove-programy
    defaults: { _controller: App\Controller\Front\ProductSeriesController:listAction }

front_stores:
    path: /obchodne-domy
    defaults: { _controller: App\Controller\Front\StoreController:indexAction }

front_contacts:
    path: /kontakty
    defaults: { _controller: App\Controller\Front\ContactController:indexAction }

front_leaflet:
    path: /letak
    defaults: { _controller: App\Controller\Front\LeafletController:indexAction }

front_kitchen:
    path: /kuchyne
    defaults: { _controller: App\Controller\Front\KitchenController:indexAction }

front_kitchen_list:
    path: /kuchyne-na-mieru
    defaults: { _controller: App\Controller\Front\KitchenController:listAction }

front_kitchen_list_modern:
    path: /moderne-kuchyne
    defaults: { _controller: App\Controller\Front\KitchenController:listModernKitchenAction }

front_kitchen_list_rustical:
    path: /rustikalne-kuchyne
    defaults: { _controller: App\Controller\Front\KitchenController:listRusticalKitchenAction }

front_kitchen_list_classic:
    path: /klasicke-kuchyne
    defaults: { _controller: App\Controller\Front\KitchenController:listClassicKitchenAction }

front_kitchen_detail:
    path: /detail-kuchyne
    defaults: { _controller: App\Controller\Front\KitchenController:detailAction }

# All next routes are only temporary for static templates content
# Currently we don't have administration for kitchen module.
# TODO: Create single detailAction (front_kitchen_detail) with parameter (ID) for dynamic routing

front_kitchen_detail_flash:
    path: /kuchyne/nobilia-flash
    defaults: { _controller: App\Controller\Front\KitchenController:detailActionFlash }

front_kitchen_detail_touch:
    path: /kuchyne/nobilia-touch
    defaults: { _controller: App\Controller\Front\KitchenController:detailActionTouch }

front_kitchen_detail_speed:
    path: /kuchyne/nobilia-speed
    defaults: { _controller: App\Controller\Front\KitchenController:detailActionSpeed }

front_kitchen_detail_lux:
    path: /kuchyne/nobilia-lux
    defaults: { _controller: App\Controller\Front\KitchenController:detailActionLux }

front_kitchen_detail_stoneart:
    path: /kuchyne/nobilia-stoneart
    defaults: { _controller: App\Controller\Front\KitchenController:detailActionStoneart }

front_kitchen_detail_riva:
    path: /kuchyne/nobilia-riva
    defaults: { _controller: App\Controller\Front\KitchenController:detailActionRiva }

front_kitchen_detail_structura:
    path: /kuchyne/nobilia-structura
    defaults: { _controller: App\Controller\Front\KitchenController:detailActionStructura }

front_kitchen_detail_easytouch:
    path: /kuchyne/nobilia-easytouch
    defaults: { _controller: App\Controller\Front\KitchenController:detailActionEasytouch }

front_kitchen_detail_fashion:
    path: /kuchyne/nobilia-fashion
    defaults: { _controller: App\Controller\Front\KitchenController:detailActionFashion }

front_kitchen_detail_inline:
    path: /kuchyne/nobilia-inline
    defaults: { _controller: App\Controller\Front\KitchenController:detailActionInline }

front_kitchen_detail_inox:
    path: /kuchyne/nobilia-inox
    defaults: { _controller: App\Controller\Front\KitchenController:detailActionInox }

front_kitchen_detail_laser:
    path: /kuchyne/nobilia-laser
    defaults: { _controller: App\Controller\Front\KitchenController:detailActionLaser }

front_kitchen_detail_rio:
    path: /kuchyne/nobilia-rio
    defaults: { _controller: App\Controller\Front\KitchenController:detailActionRio }

front_kitchen_detail_pura:
    path: /kuchyne/nobilia-pura
    defaults: { _controller: App\Controller\Front\KitchenController:detailActionPura }

front_kitchen_detail_focus:
    path: /kuchyne/nobilia-focus
    defaults: { _controller: App\Controller\Front\KitchenController:detailActionFocus }

front_kitchen_detail_cemento:
    path: /kuchyne/nobilia-cemento
    defaults: { _controller: App\Controller\Front\KitchenController:detailActionCemento }

front_kitchen_detail_cascada:
    path: /kuchyne/nobilia-cascada
    defaults: { _controller: App\Controller\Front\KitchenController:detailActionCascada }

front_kitchen_detail_castello:
    path: /kuchyne/nobilia-castello
    defaults: { _controller: App\Controller\Front\KitchenController:detailActionCastello }

front_kitchen_detail_chalet:
    path: /kuchyne/nobilia-chalet
    defaults: { _controller: App\Controller\Front\KitchenController:detailActionChalet }

front_kitchen_detail_gent:
    path: /kuchyne/nobilia-gent
    defaults: { _controller: App\Controller\Front\KitchenController:detailActionGent }

front_kitchen_detail_york:
    path: /kuchyne/nobilia-york
    defaults: { _controller: App\Controller\Front\KitchenController:detailActionYork }

front_kitchen_detail_sylt:
    path: /kuchyne/nobilia-sylt
    defaults: { _controller: App\Controller\Front\KitchenController:detailActionSylt }

front_kitchen_detail_kansas:
    path: /kuchyne/nobilia-kansas
    defaults: { _controller: App\Controller\Front\KitchenController:detailActionKansas }

front_kitchen_detail_credo:
    path: /kuchyne/nobilia-credo
    defaults: { _controller: App\Controller\Front\KitchenController:detailActionCredo }
