FileDecorator:
    type: object
    decorator: true
    config:
        description: "Represents a downloadable file"
        fields:
            anchorText:
                type: "String!"
                description: "Clickable text for a hyperlink"
            url:
                type: "String!"
                description: "Url to download the file"
            viewUrl:
                type: "String"
                description: "Url to view the file in browser (available for images and PDF files)"
            size:
                type: "Int"
                description: "File size in bytes"
            extension:
                type: "String"
                description: "File extension"
