image: docker:19.03.1

services:
    -   name: docker:dind
        alias: docker

stages:
    - build
    - test
    - review

.only-default: &only-default
    only:
        - pushes
        - merge_requests

variables:
    TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    DOCKER_DRIVER: overlay2

before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build:
    stage: build
    <<: *only-default
    script:
        - docker build -f ./docker/php-fpm/Dockerfile --target production --compress -t $TAG -t $CI_REGISTRY_IMAGE:latest .
        - docker push $CI_REGISTRY_IMAGE

test-standards:
    stage: test
    <<: *only-default
    variables:
        GIT_STRATEGY: none
    script:
        - docker run -i $TAG /bin/bash -c "mv PRODUCTION DEVELOPMENT; php phing composer-dev npm dirs-create test-dirs-create assets standards tests-unit tests-acceptance-build"

test-functional:
    image: tmaier/docker-compose:latest
    stage: test
    <<: *only-default
    script:
        - cp -f ./gitlab/docker-compose-ci.yml ./docker-compose.yml
        - docker pull $TAG
        - docker tag $TAG php-fpm
        - docker-compose up -d
        - docker-compose exec -T php-fpm /bin/bash -c "mv PRODUCTION DEVELOPMENT; php phing composer-dev npm dirs-create test-dirs-create assets db-create test-db-create build-demo-dev-quick error-pages-generate tests"

review-start:
    stage: review
    environment:
        name: "review/$CI_COMMIT_REF_SLUG"
        url: https://$CI_COMMIT_REF_SLUG.ci.scontodev.cz
        on_stop: review-stop
    variables:
        CI_NETWORK: ci_default
        CI_NGINX_PROXY_NETWORK: ci_nginx-proxy-network
        PHP_FPM_IMAGE_NAME: $CI_COMMIT_REF_SLUG
        HOSTS: $CI_COMMIT_REF_SLUG.ci.scontodev.cz,$CI_COMMIT_REF_SLUG.ci.scontodev.sk
        COMPOSE_PROJECT_NAME: $CI_COMMIT_REF_SLUG
    needs:
        - build
    only:
        - merge_requests
        - master

    script:
        - cp -f ./gitlab/docker-compose-review.yml ./docker-compose.yml
        - docker-compose up -d
        - "docker-compose exec -T php-fpm sed -i \"s/database_name:.*/database_name: ${PHP_FPM_IMAGE_NAME}/\" config/parameters.yml"
        - docker-compose exec -T php-fpm sed -i "s/http:\/\/127.0.0.1:8000/https:\/\/${PHP_FPM_IMAGE_NAME}.ci.scontodev.cz/g" config/domains_urls.yml
        - docker-compose exec -T php-fpm sed -i "s/http:\/\/127.0.0.2:8000/https:\/\/${PHP_FPM_IMAGE_NAME}.ci.scontodev.sk/g" config/domains_urls.yml
        - docker-compose exec -T php-fpm php phing -D production.confirm.action=y db-create build-demo
    tags:
        - review

review-stop:
    stage: review
    variables:
        CI_NETWORK: ci_default
        CI_NGINX_PROXY_NETWORK: ci_nginx-proxy-network
        PHP_FPM_IMAGE_NAME: $CI_COMMIT_REF_SLUG
        PHP_FPM_IMAGE_TAG: $TAG
        HOSTS: $CI_COMMIT_REF_SLUG.ci.scontodev.cz,$CI_COMMIT_REF_SLUG.ci.scontodev.sk
        COMPOSE_PROJECT_NAME: $CI_COMMIT_REF_SLUG
    tags:
        - review
    script:
        - cp -f ./gitlab/docker-compose-review.yml ./docker-compose.yml
        - docker-compose exec -T php-fpm php phing -D production.confirm.action=y product-search-delete-structure
        - docker-compose down --rmi all -v
        - /home/ci/clean.sh ${CI_COMMIT_REF_SLUG}
    when: manual
    only:
        - merge_requests
    environment:
        name: review/$CI_COMMIT_REF_SLUG
        action: stop
