image: docker:19.03.1

services:
    -   name: docker:19.03.1-dind

stages:
    - build
    - test
    - review
    - deploy
    - service

.only-default: &only-default
    only:
        - branches
        - master
    except:
        - schedules


.deploy: &deploy
    image:
        name: shopsys/kubernetes-buildpack:0.3.0-dev
    stage: deploy
    needs:
        - build
    allow_failure: false
    script:
        - apk add --no-cache bash openvpn
        - openvpn --daemon --config $OVPN
        - sleep 10
        - mkdir -p /root/.kube/
        - cp $KUBE_CONFIG /root/.kube/config
        - ./.ci/deploy.sh
    except:
        - schedules


variables:
    TAG: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG:$CI_COMMIT_SHA
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""

before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build:
    stage: build
    <<: *only-default
    script:
        - docker build -f ./docker/php-fpm/Dockerfile --target production --compress -t $TAG .
        - docker push $TAG

test:standards:
    stage: test
    <<: *only-default
    variables:
        GIT_STRATEGY: none
    script:
        - docker run -i $TAG /bin/bash -c "mv PRODUCTION DEVELOPMENT; php phing composer-dev npm dirs-create test-dirs-create assets standards tests-unit tests-acceptance-build"

test:functional:
    image: tmaier/docker-compose:latest
    stage: test
    <<: *only-default
    script:
        - cp -f ./gitlab/docker-compose-ci.yml ./docker-compose.yml
        - docker pull $TAG
        - docker tag $TAG php-fpm
        - docker-compose up -d
        - docker-compose exec -T php-fpm /bin/bash -c "mv PRODUCTION DEVELOPMENT; php phing composer-dev npm dirs-create test-dirs-create assets db-create test-db-create build-demo-dev-quick error-pages-generate tests"

review:
    stage: review
    environment:
        name: "review/$CI_COMMIT_REF_SLUG"
        url: https://$CI_AUTH_USERNAME:$CI_AUTH_PASSWORD@$CI_COMMIT_REF_SLUG.ci.scontodev.cz
        on_stop: review:stop
    variables:
        CI_NETWORK: ci_default
        CI_NGINX_PROXY_NETWORK: ci_nginx-proxy-network
        PHP_FPM_IMAGE_NAME: $CI_COMMIT_REF_SLUG
        PHP_FPM_CONTAINER_NAME_SUFFIX: _php-fpm_1
        PHP_FPM_CONTAINER_NAME: ${CI_COMMIT_REF_SLUG}${PHP_FPM_CONTAINER_NAME_SUFFIX}
        HOSTS: $CI_COMMIT_REF_SLUG.ci.scontodev.cz,$CI_COMMIT_REF_SLUG.ci.scontodev.sk
        COMPOSE_PROJECT_NAME: $CI_COMMIT_REF_SLUG
    needs:
        - build
    <<: *only-default
    script:
        - cp /home/ci/docker-compose-review.yml ./docker-compose.yml
        - docker-compose down --rmi all -v
        - docker-compose up -d
        - docker cp ${PHP_FPM_CONTAINER_NAME}:/var/www/html/config/parameters.yaml ~/parameters.yaml
        - ~/yq write --inplace ~/parameters.yaml parameters.database_name ${PHP_FPM_IMAGE_NAME}
        - ~/yq write --inplace ~/parameters.yaml parameters.akeneo_config.enabled ${AKENEO_ENABLED}
        - ~/yq write --inplace ~/parameters.yaml parameters.akeneo_config.base_uri ${AKENEO_BASE_URI}
        - ~/yq write --inplace ~/parameters.yaml parameters.akeneo_config.client_id ${AKENEO_CLIENT_ID}
        - ~/yq write --inplace ~/parameters.yaml parameters.akeneo_config.secret ${AKENEO_SECRET}
        - ~/yq write --inplace ~/parameters.yaml parameters.akeneo_config.user ${AKENEO_USER}
        - ~/yq write --inplace ~/parameters.yaml parameters.akeneo_config.password ${AKENEO_PASSWORD}
        - ~/yq write --inplace ~/parameters.yaml parameters.sconto_bridge_config.enabled ${SCONTO_BRIDGE_DEV_ENABLED}
        - ~/yq write --inplace ~/parameters.yaml parameters.sconto_bridge_config.base_uri ${SCONTO_BRIDGE_DEV_BASE_URI}
        - ~/yq write --inplace ~/parameters.yaml parameters.sconto_bridge_config.user ${SCONTO_BRIDGE_DEV_USER}
        - ~/yq write --inplace ~/parameters.yaml parameters.sconto_bridge_config.password ${SCONTO_BRIDGE_DEV_PASSWORD}
        - ~/yq write --inplace ~/parameters.yaml parameters.kraken_config.enabled ${KRAKEN_DEV_ENABLED}
        - ~/yq write --inplace ~/parameters.yaml parameters.kraken_config.lossy ${KRAKEN_DEV_LOSSY}
        - ~/yq write --inplace ~/parameters.yaml parameters.kraken_config.api_key ${KRAKEN_DEV_API_KEY}
        - ~/yq write --inplace ~/parameters.yaml parameters.kraken_config.api_secret ${KRAKEN_DEV_API_SECRET}
        - ~/yq write --inplace ~/parameters.yaml parameters.targito_config.enabled ${TARGITO_DEV_ENABLED}
        - ~/yq write --inplace ~/parameters.yaml parameters.targito_config.eshop_to_targito_account_id ${TARGITO_ESHOP_TO_TARGITO_ACCOUNT_ID}
        - ~/yq write --inplace ~/parameters.yaml parameters.targito_config.eshop_to_targito_password ${TARGITO_ESHOP_TO_TARGITO_PASSWORD}
        - ~/yq write --inplace ~/parameters.yaml parameters.gtm_config.cs.enabled ${GTM_DEV_ENABLED}
        - ~/yq write --inplace ~/parameters.yaml parameters.gtm_config.cs.container_id ${GTM_CZ_ID}
        - ~/yq write --inplace ~/parameters.yaml parameters.gtm_config.sk.enabled ${GTM_DEV_ENABLED}
        - ~/yq write --inplace ~/parameters.yaml parameters.gtm_config.sk.container_id ${GTM_SK_ID}
        - docker cp ~/parameters.yaml "${PHP_FPM_CONTAINER_NAME}:/var/www/html/config/parameters.yaml"
        - docker-compose exec --user root -T php-fpm chown www-data:www-data /var/www/html/config/parameters.yaml
        - docker-compose exec -T php-fpm sed -i "s/http:\/\/127.0.0.1:8000/https:\/\/${PHP_FPM_IMAGE_NAME}.ci.scontodev.cz/g" config/domains_urls.yaml
        - docker-compose exec -T php-fpm sed -i "s/http:\/\/127.0.0.2:8000/https:\/\/${PHP_FPM_IMAGE_NAME}.ci.scontodev.sk/g" config/domains_urls.yaml
        - docker-compose exec -T php-fpm php phing -D production.confirm.action=y db-create build-demo
    tags:
        - review

review:stop:
    stage: review
    variables:
        GIT_STRATEGY: none
        CI_NETWORK: ci_default
        CI_NGINX_PROXY_NETWORK: ci_nginx-proxy-network
        PHP_FPM_IMAGE_NAME: $CI_COMMIT_REF_SLUG
        HOSTS: $CI_COMMIT_REF_SLUG.ci.scontodev.cz,$CI_COMMIT_REF_SLUG.ci.scontodev.sk
        COMPOSE_PROJECT_NAME: $CI_COMMIT_REF_SLUG
    tags:
        - review
    needs:
        - build
    <<: *only-default
    script:
        - cp /home/ci/docker-compose-review.yml ./docker-compose.yml
        - docker-compose exec -T php-fpm php phing -D production.confirm.action=y elasticsearch-index-delete
        - docker-compose down --rmi all -v
        - /home/ci/clean.sh ${CI_COMMIT_REF_SLUG}
    when: manual
    only:
        - branches
    environment:
        name: review/$CI_COMMIT_REF_SLUG
        action: stop

deploy:production:
    <<: *deploy
    when: manual
    resource_group: deploy_production
    only:
        - master
        - /^master-.*$/
    environment:
        name: production
        url: https://prod.eshop.scontodev.cz

deploy:production2:
    <<: *deploy
    when: manual
    resource_group: deploy_production2
    only:
        - master
        - /^master-.*$/
        - pk/sd-1428-production-cluster
    environment:
        name: production2
        url: https://prod.scontodev.cz

deploy:beta:
    <<: *deploy
    resource_group: deploy_beta
    only:
        - beta
    environment:
        name: beta
        url: https://beta.eshop.scontodev.cz

deploy:devel:
    <<: *deploy
    resource_group: deploy_devel
    only:
        - devel
    environment:
        name: devel
        url: https://devel.eshop.scontodev.cz

repository:clean:
    stage: service
    image: dwdraju/alpine-curl-jq
    when: always
    tags:
        - docker
    only:
        refs:
            - schedules
    before_script:
        - chmod +x ./gitlab/scripts/repository-clean.sh
    script:
        - ./gitlab/scripts/repository-clean.sh

security:check:
    stage: service
    tags:
        - docker
    needs:
        - build
    only:
        refs:
            - master
    except:
        - schedules
    script:
        - docker run -i ${TAG} composer security-check
