query ComplaintsQuery(
    $first: Int
    $after: String
    $filter: ComplaintFilterInput
    $statuslessFilter: ComplaintFilterInput
) {
    complaints(first: $first, after: $after, filter: $filter) {
        totalCount
        pageInfo {
            ...PageInfoFragment
        }
        edges {
            cursor
            node {
                ...ComplaintListItemFragment
            }
        }
    }
    complaintStatusCounts(filter: $statuslessFilter) {
        status {
            code
            type
            name
        }
        count
    }
}
