StoreConnection:
    type: relay-connection
    config:
        nodeType: Store
        connectionFields:
            totalCount:
                type: "Int!"
                description: "Total number of stores"
            searchCoordinates:
                type: "StoreSearchCoordinates"
                description: "Coordinates found by the store search text"
    inherits:
        - 'StoreConnectionDecorator'
