mutation LoginWithCredentialMutation(
    $type: LoginTypeEnum!
    $credential: String!
    $nonce: String
    $previousCartUuid: Uuid
    $productListsUuids: [Uuid!]!
    $shouldOverwriteCustomerUserCart: Boolean = false
) {
    LoginWithCredential(
        input: {
            type: $type
            credential: $credential
            nonce: $nonce
            cartUuid: $previousCartUuid
            productListsUuids: $productListsUuids
            shouldOverwriteCustomerUserCart: $shouldOverwriteCustomerUserCart
        }
    ) {
        tokens {
            ...TokenFragments
        }
        showCartMergeInfo
    }
}
