query AutocompleteSearchQuery(
    $search: String!
    $maxProductCount: Int
    $maxCategoryCount: Int
    $isAutocomplete: Boolean!
    $userIdentifier: Uuid!
) {
    articlesSearch(
        searchInput: {
            search: $search,
            isAutocomplete: $isAutocomplete
            userIdentifier: $userIdentifier
        }
    ) {
        __typename
        ... on ArticleSite {
            uuid
            name
            slug
        }
        ... on BlogArticle {
            name
            slug
        }
    }
    brandSearch(
        searchInput: {
            search: $search,
            isAutocomplete: $isAutocomplete
            userIdentifier: $userIdentifier
        }
    ) {
        ...SimpleBrandFragment
    }
    categoriesSearch(
        searchInput: {
            search: $search
            isAutocomplete: $isAutocomplete
            userIdentifier: $userIdentifier
        }
        first: $maxCategoryCount
    ) {
        __typename
        totalCount
        edges {
            __typename
            node {
                ...SimpleCategoryFragment
            }
        }
    }
    productsSearch: productsSearch(
        searchInput: {
            search: $search
            isAutocomplete: $isAutocomplete
            userIdentifier: $userIdentifier
        }
        first: $maxProductCount
    ) {
        __typename
        totalCount
        edges {
            __typename
            node {
                ...CompactProductFragment
            }
        }
    }
}
