Article:
    type: object
    inherits:
        - 'ArticleDecorator'
    config:
        interfaces:
            - 'Breadcrumb'
            - 'Slug'
        fields:
            slug:
                type: "String!"
                description: "Article URL slug"
            breadcrumb:
                type: "[Link!]!"
                description: "Hierarchy of the current element in relation to the structure"
                resolve: '@=resolver("resolveBreadcrumb", [value["id"], "front_article_detail"])'
