Availability:
    type: object
    inherits:
        - 'AvailabilityDecorator'
    config:
        fields:
            status:
                type: "String!"
                description: "Availability status in a format suitable for usage in the code"
