Brand:
    type: object
    inherits:
        - 'BrandDecorator'
    config:
        interfaces:
            - 'Breadcrumb'
            - 'Slug'
        fields:
            images:
                type: "[Image!]!"
                description: "Brand images"
                resolve: '@=resolver("brandImageResolver", [value, args["type"], args["sizes"]])'
                args:
                    type:
                        type: "String"
                        defaultValue: null
                    sizes:
                        type: "[String!]"
                        defaultValue: null
            slug:
                type: "String!"
                description: "Brand URL slug"
            breadcrumb:
                type: "[Link!]!"
                description: "Hierarchy of the current element in relation to the structure"
                resolve: '@=resolver("resolveBreadcrumb", [value.getId(), "front_brand_detail"])'
