Brand:
    type: object
    inherits:
        - 'BrandDecorator'
    config:
        interfaces:
            - 'Slug'
        fields:
            slug:
                type: "String!"
                description: "Brand URL slug"
