Category:
    type: object
    inherits:
        - 'CategoryDecorator'
    config:
        interfaces:
            - 'Breadcrumb'
            - 'Slug'
        fields:
            name:
                type: "String!"
                description: "Localized category name (domain dependent)"
            children:
                type: "[Category!]!"
                description: "Descendant categories"
            bestsellers:
                type: "[Product!]!"
                description: "Best selling products"
                resolve: '@=service("App\\FrontendApi\\Model\\Resolver\\Products\\BestsellingProductsResolver").resolveByCategoryOrReadyCategorySeoMix(value)'
            slug:
                type: "String!"
                description: "Category URL slug"
            breadcrumb:
                type: "[Link!]!"
                description: "Hierarchy of the current element in relation to the structure"
                resolve: '@=resolver("resolveCategoryBreadcrumb", [value])'
            images:
                type: "[Image!]!"
                description: "Category images"
                resolve: '@=resolver("categoryOrReadyCategorySeoMixImageResolver", [value, args["type"], args["sizes"]])'
                args:
                    type:
                        type: "String"
                        defaultValue: null
                    sizes:
                        type: "[String!]"
                        defaultValue: null
            products:
                type: "ProductConnection"
                description: "Paginated and ordered products of category"
                argsBuilder:
                    builder: "PaginatorArgumentsBuilder"
                    config:
                        orderingModeType: 'ProductOrderingModeEnum'
                resolve: '@=service("App\\FrontendApi\\Model\\Resolver\\Products\\ProductsResolver").resolveByCategoryOrReadyCategorySeoMix(args, value)'
            readyCategorySeoMixLinks:
                type: "[Link!]!"
                description: "An array of links of prepared category SEO mixes of a given category"
            linkedCategories:
                type: "[Category!]!"
                description: "A list of categories linked to the given category"
