Category:
    type: object
    inherits:
        - 'CategoryDecorator'
    config:
        interfaces:
            - 'Breadcrumb'
            - 'Slug'
        fields:
            bestsellers:
                type: "[Product!]!"
                description: "Best selling products"
                resolve: '@=service("App\\FrontendApi\\Model\\Resolver\\Products\\BestsellingProductsResolver").resolveByCategory(value)'
            slug:
                type: "String!"
                description: "Category URL slug"
            breadcrumb:
                type: "[Link!]!"
                description: "Hierarchy of the current element in relation to the structure"
                resolve: '@=resolver("resolveBreadcrumb", [value.getId(), "front_product_list"])'
            images:
                type: "[Image]!"
                description: "Category images"
                resolve: '@=service("App\\FrontendApi\\Model\\Resolver\\Image\\ImagesResolver").resolveByCategory(value, args["type"], args["size"])'
                args:
                    type:
                        type: "String"
                        defaultValue: null
                    size:
                        type: "String"
