Mutation:
    type: object
    inherits:
        - 'MutationDecorator'
    config:
        fields:
            AddToCart:
                type: AddToCartResult!
                description: "Add product to cart for future checkout"
                args:
                    input:
                        type: AddToCartInput!
                        validation: cascade
                resolve: "@=mutation('addToCart', [args, validator])"
            RemoveFromCart:
                type: Cart!
                description: "Remove product from cart"
                args:
                    input:
                        type: RemoveFromCartInput!
                        validation: cascade
                resolve: "@=mutation('removeFromCart', [args, validator])"
            RequestPasswordRecovery:
                type: String!
                description: "Request password recovery - email with hash will be sent"
                args:
                    email:
                        type: String!
                        validation:
                            -   Email:
                                    message: "Please enter valid email"
                            -   Length:
                                    max: 255
                                    maxMessage: "Email cannot be longer than {{ limit }} characters"
                resolve: "@=mutation('requestPasswordRecovery', [args, validator])"
            RecoverPassword:
                type: Token!
                description: "Recover password using hash required from RequestPasswordRecovery"
                args:
                    input:
                        type: RecoverPasswordInput!
                        validation: cascade
                resolve: "@=mutation('recoverPassword', [args, validator])"
