Mutation:
    type: object
    inherits:
        - 'MutationDecorator'
    config:
        fields:
            AddToCart:
                type: AddToCartResult!
                description: "Add product to cart for future checkout"
                args:
                    input:
                        type: AddToCartInput!
                        validation: cascade
                resolve: "@=mutation('addToCart', [args, validator])"
