Price:
    type: object
    inherits:
        - 'PriceDecorator'
    config:
        fields:
            priceWithVat:
                type: "Money!"
                description: "Price with VAT"
            priceWithoutVat:
                type: "Money!"
                description: "Price without VAT"
            vatAmount:
                type: "Money!"
                description: "Total value of VAT"
