Product:
    type: interface
    inherits:
        - 'ProductDecorator'
    config:
        fields:
            catalogNumber:
                type: "String!"
                description: "Product catalog number"
            partNumber:
                type: "String"
                description: "Product part number"
            ean:
                type: "String"
                description: "EAN"
            usps:
                type: "[String!]!"
                description: "List of product's unique selling propositions"
            namePrefix:
                type: "String"
                description: "Name prefix"
            nameSuffix:
                type: "String"
                description: "Name suffix"
            fullName:
                type: "String!"
                description: "The full name of the product, which consists of a prefix, name, and a suffix"
            isInSale:
                type: "Boolean!"
                description: "Distinguishes if the product is on sale"
            hasPreorder:
                type: "Boolean!"
                description: "Distinguishes if the product can be pre-ordered"
            hasSaleExclusion:
                type: "Boolean!"
                description: "Distinguishes if the product can be bought"
            files:
                type: "[File!]!"
                description: "List of downloadable files"
            storeAvailabilities:
                type: "[StoreAvailability!]!"
                description: "List of availabilities in individual stores"
