Query:
    type: object
    inherits:
        - 'QueryDecorator'
    config:
        fields:
            navigation:
                type: '[NavigationItem!]!'
                resolve: "@=resolver('navigationResolver')"
                description: "Returns complete navigation menu"
            CurrentCompanyCustomerUser:
                type: 'CurrentCompanyCustomerUser'
            CurrentRegularCustomerUser:
                type: 'CurrentRegularCustomerUser'
            promotedCategories:
                type: '[Category!]!'
                resolve: "@=resolver('promotedCategoriesResolver')"
                description: "Returns promoted categories"
            stores:
                type: "StoreConnection"
                argsBuilder: "Relay::Connection"
                resolve: "@=resolver('stores', [args])"
                description: "Returns list of stores that can be paginated using `first`, `last`, `before` and `after` keywords"
            store:
                type: 'Store'
                resolve: "@=resolver('store', [args['uuid'], args['urlSlug']])"
                args:
                    uuid:
                        type: "Uuid"
                    urlSlug:
                        type: "String"
                description: "Returns store filtered using UUID or URL slug"
            blogArticle:
                type: 'BlogArticle'
                resolve: "@=resolver('blogArticle', [args['uuid']])"
                args:
                    uuid:
                        type: "Uuid!"
                description: "Returns blog article filtered using UUID"
