Query:
    type: object
    inherits:
        - 'QueryDecorator'
    config:
        fields:
            navigation:
                type: '[NavigationItem!]!'
                resolve: "@=resolver('navigationResolver')"
                description: "Returns complete navigation menu"
            CurrentCompanyCustomerUser:
                type: 'CurrentCompanyCustomerUser'
            CurrentRegularCustomerUser:
                type: 'CurrentRegularCustomerUser'
            promotedCategories:
                type: '[Category!]!'
                resolve: "@=resolver('promotedCategoriesResolver')"
                description: "Returns promoted categories"
