Query:
    type: object
    inherits:
        - 'QueryDecorator'
    config:
        fields:
            navigation:
                type: '[NavigationItem!]!'
                resolve: "@=resolver('navigationResolver')"
                description: "Returns complete navigation menu"
            CompanyCustomerUser:
                type: 'CompanyCustomerUser'
            RegularCustomerUser:
                type: 'RegularCustomerUser'
            promotedCategories:
                type: '[Category!]!'
                resolve: "@=resolver('promotedCategoriesResolver')"
                description: "Returns promoted categories"
            stores:
                type: "StoreConnection"
                argsBuilder: "Relay::Connection"
                resolve: "@=resolver('stores', [args])"
                description: "Returns list of stores that can be paginated using `first`, `last`, `before` and `after` keywords"
            store:
                type: 'Store'
                resolve: "@=resolver('store', [args['uuid'], args['urlSlug']])"
                args:
                    uuid:
                        type: "Uuid"
                    urlSlug:
                        type: "String"
                description: "Returns store filtered using UUID or URL slug"
            blogArticle:
                type: 'BlogArticle'
                resolve: "@=resolver('blogArticleByUuidOrUrlSlug', [args['uuid'], args['urlSlug']])"
                args:
                    uuid:
                        type: "Uuid"
                    urlSlug:
                        type: "String"
                description: "Returns blog article filtered using UUID or URL slug"
            blogArticles:
                type: "BlogArticleConnection"
                argsBuilder: "BlogArticlePaginatorArgumentsBuilder"
                resolve: "@=resolver('blogArticles', [args])"
                description: "Returns a list of the blog articles that can be paginated using `first`, `last`, `before` and `after` keywords"
            blogCategory:
                type: 'BlogCategory'
                resolve: "@=resolver('blogCategoryByUuidOrUrlSlug', [args['uuid'], args['urlSlug']])"
                args:
                    uuid:
                        type: "Uuid"
                    urlSlug:
                        type: "String"
                description: "Returns blog category filtered using UUID or URL slug"
            blogCategories:
                type: '[BlogCategory!]!'
                resolve: "@=resolver('blogCategories')"
                description: "Returns a complete list of the blog categories"
            sliderItems:
                type: '[SliderItem!]!'
                resolve: "@=resolver('sliderItems')"
                description: "Returns a complete list of the slider items"
            slug:
                type: 'Slug'
                resolve: "@=resolver('slugResolver', [args['slug']])"
                description: "Returns entity by slug"
                args:
                    slug:
                        type: "String!"
            notificationBars:
                type: '[NotificationBar!]'
                resolve: "@=resolver('notificationBars')"
                description: "Returns a list of notifications supposed to be displayed on all pages"
            articlesSearch:
                type: "[ArticleInterface]"
                resolve: "@=resolver('articlesSearch', [args])"
                args:
                    search:
                        type: "String!"
                description: "Returns list of searched articles and blog articles"
            cart:
                type: 'Cart'
                args:
                    cartInput:
                        type: CartInput
                        validation: cascade
                        defaultValue: {"cartUuid": null}
                resolve: "@=resolver('getCart', [args['cartInput']])"
                description: "Return cart of logged customer or cart by UUID for anonymous user"
            flags:
                type: '[Flag!]'
                resolve: "@=resolver('flags')"
                description: "Returns a complete list of the flags"
            flag:
                type: 'Flag'
                resolve: "@=resolver('flag', [args['uuid'], args['urlSlug']])"
                args:
                    uuid:
                        type: "Uuid"
                    urlSlug:
                        type: "String"
                description: "Returns a flag by uuid or url slug"
            transports:
                type: '[Transport!]!'
                resolve: "@=resolver('transports', [args['cartUuid']])"
                args:
                    cartUuid:
                        type: "Uuid"
                description: "Returns available transport methods based on the current cart state"
            personalDataPage:
                type: 'PersonalDataPage'
                resolve: "@=resolver('personalDataPage')"
                description: "Return personal data page content and URL"
            currentCustomerUser:
                type: 'CustomerUser!'
                resolve: "@=resolver('currentCustomerUser')"
                description: "Returns currently logged in customer user"
            accessPersonalData:
                type: PersonalData!
                description: "Access personal data using hash received in email from personal data access request"
                args:
                    hash:
                        type: "String!"
                        description: "Hash to securely recognize access"
                        validation:
                            -   Length:
                                    min: 20
                                    max: 20
                resolve: "@=resolver('accessPersonalData', [args['hash'], validator])"
            countries:
                type: '[Country!]!'
                resolve: "@=resolver('countries')"
                description: "Returns available countries"
