fragment CategoryDetailFragment on Category {
    __typename
    id
    uuid
    slug
    originalCategorySlug
    zboziCategory
    name
    description
    images {
        ...ImageFragment
    }
    seo {
        ...SeoAttributesFragment
    }
    readyCategorySeoMixLinks {
        __typename
        name
        slug
    }
    hreflangLinks {
        ...HreflangLinksFragment
    }
    breadcrumb {
        ...BreadcrumbFragment
    }
    categoryHierarchy {
        id
        name
    }
    children {
        __typename
        uuid
        name
        slug
        mainImage {
            ...ImageFragment
        }
        products {
            __typename
            totalCount
        }
    }
    products(orderingMode: $orderingMode, filter: $filter) {
        ...ListedProductConnectionPreviewFragment
    }
    bestsellers {
        ...CategoryBestsellerFragment
    }
    automatedFilters
}
