fragment CategoryDetailFragment on Category {
    uuid
    slug
    name
    seoH1
    ...BreadcrumbFragment
    children {
        ...CategoryPreviewFragment
    }
    linkedCategories {
        ...CategoryPreviewFragment
    }
    products(orderingMode: $sortingMode, after: $endCursorForPagination, first: $pageSize) {
        totalCount
        pageInfo {
            ...PageInfoFragment
        }
        edges {
            node {
                ...ProductListFragment
            }
        }
    }
    readyCategorySeoMixLinks {
        name
        slug
    }
}
