ComplaintStatusEnumDecorator:
    type: enum
    decorator: true
    config:
        description: "Status of complaint"
        values:
            new:
                value: '@=constant("Shopsys\\FrameworkBundle\\Model\\Complaint\\Status\\ComplaintStatusTypeEnum::STATUS_TYPE_NEW")'
                description: "New"
            in_progress:
                value: '@=constant("Shopsys\\FrameworkBundle\\Model\\Complaint\\Status\\ComplaintStatusTypeEnum::STATUS_TYPE_IN_PROGRESS")'
                description: "In progress"
            resolved:
                value: '@=constant("Shopsys\\FrameworkBundle\\Model\\Complaint\\Status\\ComplaintStatusTypeEnum::STATUS_TYPE_RESOLVED")'
                description: "Resolved"
