ComplaintDecorator:
    type: object
    decorator: true
    config:
        fields:
            uuid:
                type: "Uuid!"
                description: "UUID"
            number:
                type: "String!"
                description: "Unique complaint number"
            createdAt:
                type: "DateTime!"
                description: "Date and time when the complaint was created"
            deliveryFirstName:
                type: "String!"
                description: "First name of the contact person for delivery"
            deliveryLastName:
                type: "String!"
                description: "Last name of the contact person for delivery"
            deliveryCompanyName:
                type: "String"
                description: "Company name for delivery"
            deliveryTelephone:
                type: "String!"
                description: "Contact telephone number for delivery"
            deliveryTelephoneData:
                type: "PhoneData!"
                description: "Structured delivery telephone data with prefix and number"
            deliveryStreet:
                type: "String!"
                description: "Street name for delivery"
            deliveryCity:
                type: "String!"
                description: "City name for delivery"
            deliveryPostcode:
                type: "String!"
                description: "Zip code for delivery"
            deliveryCountry:
                type: "Country!"
                description: "Country for delivery"
            items:
                type: "[ComplaintItem!]!"
                description: "All items in the complaint"
            status:
                type: "String!"
                description: "Status of the complaint"
            order:
                type: "Order"
                description: "Order for which the complaint was created"
            manualDocumentNumber:
                type: "String"
                description: "Order or document number entered by customer (if the complaint was created without an order)"
            email:
                type: "String!"
                description: "The customer's email address"
            resolution:
                type: "ComplaintResolution!"
                description: "Resolution of the complaint"
            bankAccountNumber:
                type: "String"
                description: "Number of the bank account if the resolution is money return"
