CustomerUserRoleEnumDecorator:
    type: enum
    decorator: true
    config:
        description: "Available customer user roles"
        values:
            ROLE_API_ALL:
                value: '@=constant("Shopsys\\FrameworkBundle\\Model\\Customer\\User\\Role\\CustomerUserRole::ROLE_API_ALL")'
            ROLE_API_CUSTOMER_SELF_MANAGE:
                value: '@=constant("Shopsys\\FrameworkBundle\\Model\\Customer\\User\\Role\\CustomerUserRole::ROLE_API_CUSTOMER_SELF_MANAGE")'
            ROLE_API_CUSTOMER_SEES_PRICES:
                value: '@=constant("Shopsys\\FrameworkBundle\\Model\\Customer\\User\\Role\\CustomerUserRole::ROLE_API_CUSTOMER_SEES_PRICES")'
            ROLE_API_ORDER_FULL:
                value: '@=constant("Shopsys\\FrameworkBundle\\Model\\Customer\\User\\Role\\CustomerUserRole::ROLE_API_ORDER_FULL")'
            ROLE_API_ORDER_VIEW:
                value: '@=constant("Shopsys\\FrameworkBundle\\Model\\Customer\\User\\Role\\CustomerUserRole::ROLE_API_ORDER_VIEW")'
