CustomerUserRoleEnumDecorator:
    type: enum
    decorator: true
    config:
        description: "Available customer user roles"
        values:
            ROLE_API_ALL:
                value: '@=constant("Shopsys\\FrameworkBundle\\Model\\Customer\\User\\Role\\CustomerUserRole::ROLE_API_ALL")'
            ROLE_API_MANAGE_COMPANY_DATA:
                value: '@=constant("Shopsys\\FrameworkBundle\\Model\\Customer\\User\\Role\\CustomerUserRole::ROLE_API_MANAGE_COMPANY_DATA")'
            ROLE_API_MANAGE_CUSTOMERS:
                value: '@=constant("Shopsys\\FrameworkBundle\\Model\\Customer\\User\\Role\\CustomerUserRole::ROLE_API_MANAGE_CUSTOMERS")'
            ROLE_API_CUSTOMER_SELF_MANAGE:
                value: '@=constant("Shopsys\\FrameworkBundle\\Model\\Customer\\User\\Role\\CustomerUserRole::ROLE_API_CUSTOMER_SELF_MANAGE")'
            ROLE_API_CUSTOMER_SEES_PRICES:
                value: '@=constant("Shopsys\\FrameworkBundle\\Model\\Customer\\User\\Role\\CustomerUserRole::ROLE_API_CUSTOMER_SEES_PRICES")'
            ROLE_API_CART_AND_ORDER_CREATION:
                value: '@=constant("Shopsys\\FrameworkBundle\\Model\\Customer\\User\\Role\\CustomerUserRole::ROLE_API_CART_AND_ORDER_CREATION")'
            ROLE_API_COMPANY_ORDERS_VIEW:
                value: '@=constant("Shopsys\\FrameworkBundle\\Model\\Customer\\User\\Role\\CustomerUserRole::ROLE_API_COMPANY_ORDERS_VIEW")'
            ROLE_API_COMPLAINT_CREATION:
                value: '@=constant("Shopsys\\FrameworkBundle\\Model\\Customer\\User\\Role\\CustomerUserRole::ROLE_API_COMPLAINT_CREATION")'
            ROLE_API_COMPANY_COMPLAINTS_VIEW:
                value: '@=constant("Shopsys\\FrameworkBundle\\Model\\Customer\\User\\Role\\CustomerUserRole::ROLE_API_COMPANY_COMPLAINTS_VIEW")'
