PaymentContentPageStatusEnumDecorator:
    type: enum
    decorator: true
    config:
        description: "Represents the status of a payment content page after the payment process"
        values:
            SUCCESSFUL:
                value: '@=constant("Shopsys\\FrontendApiBundle\\Model\\Order\\PaymentContentPage\\PaymentContentPageStatusEnum::STATUS_SUCCESSFUL")'
            FAILED:
                value: '@=constant("Shopsys\\FrontendApiBundle\\Model\\Order\\PaymentContentPage\\PaymentContentPageStatusEnum::STATUS_FAILED")'
            IN_PROCESS:
                value: '@=constant("Shopsys\\FrontendApiBundle\\Model\\Order\\PaymentContentPage\\PaymentContentPageStatusEnum::STATUS_IN_PROCESS")'
