ProductTypeEnumDecorator:
    type: enum
    decorator: true
    config:
        description: "One of possible product types"
        values:
            BASIC:
                value: '@=constant("Shopsys\\FrameworkBundle\\Model\\Product\\ProductTypeEnum::TYPE_BASIC")'
                description: "Basic product"
            INQUIRY:
                value: '@=constant("Shopsys\\FrameworkBundle\\Model\\Product\\ProductTypeEnum::TYPE_INQUIRY")'
                description: "Product with inquiry form instead of add to cart button"
            ELECTRONIC_GIFT_VOUCHER:
                value: '@=constant("Shopsys\\FrameworkBundle\\Model\\Product\\ProductTypeEnum::TYPE_ELECTRONIC_GIFT_VOUCHER")'
                description: "Gift voucher delivered by email after the order is paid"
            PRINTED_GIFT_VOUCHER:
                value: '@=constant("Shopsys\\FrameworkBundle\\Model\\Product\\ProductTypeEnum::TYPE_PRINTED_GIFT_VOUCHER")'
                description: "Gift voucher delivered printed as a regular product"
