ProductListTypeEnumDecorator:
    type: enum
    decorator: true
    config:
        description: "One of possible types of the product list"
        values:
            wishlist:
                value: '@=constant("Shopsys\\FrameworkBundle\\Model\\Product\\List\\ProductListType::WISHLIST")'
            comparison:
                value: '@=constant("Shopsys\\FrameworkBundle\\Model\\Product\\List\\ProductListType::COMPARISON")'
