BrandQuery:
    type: object
    config:
        fields:
            brandSearch:
                type: "[Brand!]!"
                resolve: "@=resolver('brandSearch', [args])"
                args:
                    search:
                        type: "String!"
                description: "Returns list of searched brands"
