const STATIC_REWRITE_PATHS = {
    [process.env.DOMAIN_HOSTNAME_1]: {
        '/search': '/hledani',
        '/cart': '/kosik',
        '/contact': '/kontakt',
        '/order/transport-and-payment': '/objednavka/doprava-a-platba',
        '/order/contact-information': '/objednavka/kontaktni-udaje',
        '/reset-password': '/zapomenute-heslo',
        '/order-confirmation': '/potvrzeni-objednavky',
        '/stores': '/obchodni-domy',
        '/brands-overview': '/prehled-znacek',
        '/login': '/prihlaseni',
        '/customer': '/zakaznik',
        '/customer/edit-profile': '/zakaznik/upravit-udaje',
        '/customer/orders': '/zakaznik/objednavky',
        '/customer/order-detail': '/zakaznik/detail-objednavky',
        '/registration': '/registrace',
        '/new-password': '/nove-heslo',
        '/personal-data-overview': '/prehled-osobnich-udaju',
        '/personal-data-overview/:hash': '/prehled-osobnich-udaju/:hash',
        '/personal-data-export': '/export-osobnich-udaju',
        '/order-payment-confirmation': '/potvrzeni-platby-objednavky',
        '/order/payment-status-notify': '/order/payment-status-notify',
        '/order-detail/:urlHash': '/detail-objednavky/:urlHash',
        '/cookie-consent': '/souhlas-se-soubory-cookies',
        '/abandoned-cart/:cartUuid': '/opusteny-kosik/:cartUuid',
    },
    [process.env.DOMAIN_HOSTNAME_2]: {
        '/search': '/hladanie',
        '/cart': '/kosik',
        '/contact': '/kontakt',
        '/order/transport-and-payment': '/objednavka/doprava-a-platba',
        '/order/contact-information': '/objednavka/kontaktne-udaje',
        '/reset-password': '/zapomenute-heslo',
        '/order-confirmation': '/potvrdenie-objednavky',
        '/stores': '/obchodne-domy',
        '/brands-overview': '/prehled-znacek',
        '/login': '/prihlasenie',
        '/customer': '/zakaznik',
        '/customer/edit-profile': '/zakaznik/upravit-udaje',
        '/customer/orders': '/zakaznik/objednavky',
        '/customer/order-detail': '/zakaznik/detail-objednavky',
        '/registration': '/registracia',
        '/new-password': '/nove-heslo',
        '/personal-data-overview': '/prehlad-osobnych-udajov',
        '/personal-data-overview/:hash': '/prehlad-osobnych-udajov/:hash',
        '/personal-data-export': '/export-osobnych-udajov',
        '/order-payment-confirmation': '/potvrdenie-platby-objednavky',
        '/order/payment-status-notify': '/order/payment-status-notify',
        '/order-detail/:urlHash': '/detail-objednavky/:urlHash',
        '/cookie-consent': '/souhlas-se-soubory-cookies',
        '/abandoned-cart/:cartUuid': '/opusteny-kosik/:cartUuid',
    },
};

// copy first domain as new third domain for acceptance (cypress) tests
STATIC_REWRITE_PATHS['http://' + process.env.ACCEPTANCE_DOMAIN_HOST + '/'] =
    STATIC_REWRITE_PATHS[process.env.DOMAIN_HOSTNAME_1];

module.exports = {
    ...STATIC_REWRITE_PATHS,
};
