fragment ListedOrderFragment on Order {
    __typename
    uuid
    number
    creationDate
    productItems {
        ...OrderItemFragment
    }
    totalPrice {
        ...PriceFragment
    }
    isPaid
    hasExternalPayment
    hasPaymentInProcess
    status
    note
    items {
        type
        payment {
            name
            mainImage {
                url
            }
        }
        transport {
            name
            mainImage {
                url
            }
        }
    }
}
