fragment ListedOrderFragment on Order {
    __typename
    uuid
    number
    creationDate
    productItems {
        ...OrderItemFragment
    }
    transport {
        __typename
        name
        mainImage {
            ...ImageFragment
        }
        mainImage {
            url
        }
    }
    payment {
        __typename
        name
        type
        mainImage {
            url
        }
    }
    totalPrice {
        ...PriceFragment
    }
    isPaid
    hasExternalPayment
    hasPaymentInProcess
    status
    note
}
