fragment OrderDetailItemFragment on OrderItem {
    __typename
    uuid
    name
    unitPrice {
        ...PriceFragment
    }
    totalPrice {
        ...PriceFragment
    }
    vatRate
    quantity
    unit
    type
    order {
        uuid
        number
        creationDate
        customerUser {
            uuid
        }
        withdrawalRequest {
            __typename
        }
    }
    product {
        uuid
        catalogNumber
        slug
        isVisible
        isSellingDenied
        isInquiryType
        productType
        isCurrentlyOutOfStock
        promotionBuyQuantity
        promotionFreeQuantity
        categories {
            name
        }
        mainImage {
            ...ImageFragment
        }
        price {
            ...ProductPriceFragment
        }
        giftPrice {
            ...ProductPriceFragment
        }
        availability {
            name
            status
        }
    }
    transport {
        transportTypeCode
        mainImage {
            url
        }
    }
    payment {
        mainImage {
            url
        }
    }
}
