fragment OrderDetailFragment on Order {
    __typename
    uuid
    number
    creationDate
    items {
        ...OrderDetailItemFragment
    }
    status
    statusType
    firstName
    lastName
    email
    telephone
    companyName
    companyNumber
    companyTaxNumber
    street
    city
    postcode
    country {
        __typename
        name
        code
    }
    isDeliveryAddressDifferentFromBilling
    deliveryFirstName
    deliveryLastName
    deliveryCompanyName
    deliveryTelephone
    deliveryStreet
    deliveryCity
    deliveryPostcode
    deliveryCountry {
        __typename
        name
        code
    }
    note
    urlHash
    promoCode
    trackingNumber
    trackingUrl
    totalPrice {
        ...PriceFragment
    }
    isPaid
    hasExternalPayment
    hasPaymentInProcess
    lastExternalPaymentUrl
    deliveredAt
    withdrawalRequest {
        ...OrderWithdrawalRequestFragment
    }
    canRequestWithdrawal
    withdrawalDeadline
    customerUser {
        uuid
    }
}
