fragment OrderDetailItemFragment on OrderItem {
    __typename
    uuid
    name
    unitPrice {
        ...PriceFragment
    }
    totalPrice {
        ...PriceFragment
    }
    vatRate
    quantity
    unit
    type
    catnum
    relatedItems {
        __typename
        uuid
        name
        catnum
        quantity
        unit
        type
        deliveryDaysExtension
        mainImage {
            ...ImageFragment
        }
        unitPrice {
            ...PriceFragment
        }
        totalPrice {
            ...PriceFragment
        }
    }
    order {
        uuid
        number
        creationDate
        customerUser {
            uuid
        }
        withdrawalRequest {
            __typename
        }
    }
    product {
        uuid
        catalogNumber
        slug
        isVisible
        isSellingDenied
        isInquiryType
        isCurrentlyOutOfStock
        promotionBuyQuantity
        promotionFreeQuantity
        categories {
            name
        }
        mainImage {
            ...ImageFragment
        }
        price {
            ...ProductPriceFragment
        }
        giftPrice {
            ...ProductPriceFragment
        }
        availability {
            name
            status
        }
    }
    transport {
        isPersonalPickup
        transportTypeCode
        mainImage {
            url
        }
    }
    payment {
        mainImage {
            url
        }
    }
}
