fragment OrderDetailItemFragment on OrderItem {
    __typename
    uuid
    name
    catnum
    unitPrice {
        ...PriceFragment
    }
    totalPrice {
        ...PriceFragment
    }
    vatRate
    quantity
    unit
    type
    catnum
    relatedItems {
        __typename
        uuid
        name
        catnum
        quantity
        unit
        type
        deliveryDaysExtension
        mainImage {
            ...ImageFragment
        }
        unitPrice {
            ...PriceFragment
        }
        totalPrice {
            ...PriceFragment
        }
    }
    order {
        uuid
        number
        creationDate
        customerUser {
            uuid
        }
        withdrawalRequest {
            __typename
        }
    }
    product {
        fullName
        mainCategory {
            name
        }
        uuid
        slug
        isVisible
        isSellingDenied
        isInquiryType
        productType
        isCurrentlyOutOfStock
        mainImage {
            ...ImageFragment
        }
    }
    transport {
        name
        transportTypeCode
        mainImage {
            ...ImageFragment
        }
    }
    payment {
        name
        mainImage {
            ...ImageFragment
        }
    }
}
