VariantDecorator:
    type: object
    decorator: true
    inherits:
        - 'Product'
    config:
        fields:
            mainVariant:
                type: 'MainVariant'
        interfaces:
            - 'Product'
            - 'Seo'
            - 'Hreflang'
            - 'Breadcrumb'
            - 'Slug'
