# Example:
#-   name: product
#    class: Shopsys\FrameworkBundle\Model\Product\Product
#    types:
#        -   name: gallery
#            multiple: true
#            sizes:
#                -   name: detail
#                    width: 200
#                    height: 300
#                    crop: false
#                    occurrence: 'Front-end: Product detail, when selected'
#                    additionalSizes:
#                       - {width: 1100, height: ~, media: "(min-width: 1200px)"}
#                       - {width: 275, height: ~, media: "(max-width: 480px)"}
#                -   name: list
#                    width: 100
#                    height: 100
#                    crop: true
#                    occurrence: 'Front-end: Product detail'
#        -   name: main
#            sizes:
#                -   name: ~
#                    width: 200
#                    height: 300
#                    crop: false
#                    occurrence: 'Front-end: Product detail, Product list'

-   name: payment
    class: Shopsys\FrameworkBundle\Model\Payment\Payment
    sizes:
        -   name: ~
            width: ~
            height: 20
            crop: false
            occurrence: 'Front-end: Ordering process'

-   name: category
    class: Shopsys\FrameworkBundle\Model\Category\Category
    sizes:
        -   name: ~
            width: 190
            height: 130
            crop: false
            occurrence: 'Front-end: Product list by category'
            additionalSizes:
                - {width: 380, height: ~, media: "only screen and (-webkit-min-device-pixel-ratio: 1.5)"}

-   name: product
    class: Shopsys\FrameworkBundle\Model\Product\Product
    multiple: true
    sizes:
        -   name: ~
            width: 605
            height: ~
            crop: false
            occurrence: 'Front-end: Main image in product detail'
            additionalSizes:
                - {width: 710, height: ~, media: "(min-width: 480px) and (max-width: 768px)"}
                - {width: 1210, height: ~, media: "only screen and (-webkit-min-device-pixel-ratio: 1.5)"}
        -   name: galleryThumbnail
            width: 250
            height: ~
            crop: false
            occurrence: 'Front-end: Thumbnail of images under the main image in product detail'
        -   name: list
            width: 280
            height: ~
            crop: false
            occurrence: 'Front-end: Listing of products in section, listing of products on special offer'
            additionalSizes:
                - {width: 560, height: ~, media: "only screen and (-webkit-min-device-pixel-ratio: 1.5)"}
        -   name: thumbnail
            width: 90
            height: 90
            crop: false
            occurrence: 'Front-end: Preview in autocomplete for search, preview in cart during ordering process'

-   name: productSeries
    class: App\Model\Product\Series\ProductSeries
    multiple: true
    sizes:
        -   name: preview
            width: 445
            height: ~
            crop: false
            occurrence: 'Front-end: Main image in product series detail and list'
            additionalSizes:
                - {width: 710, height: ~, media: "(min-width: 480px) and (max-width: 768px)"}
                - {width: 890, height: ~, media: "only screen and (-webkit-min-device-pixel-ratio: 1.5)"}
        -   name: galleryThumbnail
            width: 120
            height: 80
            crop: false
            occurrence: 'Front-end: Thumbnail of images under the main image in product series detail'

-   name: sliderItem
    class: Shopsys\FrameworkBundle\Model\Slider\SliderItem
    types:
        -   name: web
            sizes:
                -   name: ~
                    width: 1045
                    height: 290
                    crop: false
                    occurrence: 'Front-end: Main page slider'
                    additionalSizes:
                        - {width: 400, height: 165, media: "(max-width: 480px)"}
                        - {width: 730, height: 230, media: "(max-width: 1024px)"}
                        - {width: 2090, height: ~, media: "only screen and (-webkit-min-device-pixel-ratio: 1.5)"}
        -   name: mobile
            sizes:
                -   name: ~
                    width: 480
                    height: ~
                    crop: false
                    occurrence: 'Front-end: Mobile main page slider'

-   name: transport
    class: Shopsys\FrameworkBundle\Model\Transport\Transport
    sizes:
        -   name: ~
            width: ~
            height: 20
            crop: false
            occurrence: 'Front-end: Ordering process'

-   name: noticer
    class: Shopsys\FrameworkBundle\Model\Advert\Advert
    types:
        -   name: web
            sizes:
                -   name: header
                    width: 1160
                    height: ~
                    crop: false
                    occurrence: 'Front-end: Advertising under heading'
                -   name: footer
                    width: 1160
                    height: ~
                    crop: false
                    occurrence: 'Front-end: Advertising above footer'
                -   name: productList
                    width: 900
                    height: ~
                    crop: false
                    occurrence: 'Front-end: Advertising in category (above the category name)'
                -   name: cartPreview
                    width: 500
                    height: ~
                    crop: false
                    occurrence: 'Front-end: Advertising in cart (above the cart preview)'
                -   name: productListMiddle
                    width: 900
                    height: ~
                    crop: false
                    occurrence: 'Front-end: Advertising in middle category (above the product list)'
        -   name: mobile
            sizes:
                -   name: header
                    width: 425
                    height: ~
                    crop: false
                    occurrence: 'Front-end: Advertising under heading'
                -   name: footer
                    width: 425
                    height: ~
                    crop: false
                    occurrence: 'Front-end: Advertising above footer'
                -   name: productList
                    width: 425
                    height: ~
                    crop: false
                    occurrence: 'Front-end: Advertising in category (above the category name)'
                -   name: cartPreview
                    width: 425
                    height: ~
                    crop: false
                    occurrence: 'Front-end: Advertising in cart (above the cart preview)'
                -   name: productListMiddle
                    width: 425
                    height: ~
                    crop: false
                    occurrence: 'Front-end: Advertising in middle category (above the product list)'

-   name: brand
    class: Shopsys\FrameworkBundle\Model\Product\Brand\Brand
    sizes:
        -   name: ~
            width: 300
            height: 200
            crop: false
            occurrence: 'Front-end: Brand page'

-   name:  blogCategory
    class: App\Model\Blog\Category\BlogCategory
    sizes:
        -   name: ~
            width: 400
            height: 250
            crop: true
            occurrence: 'Front-end: Blog category detail'

-   name:  blogArticle
    class: App\Model\Blog\Article\BlogArticle
    sizes:
        -   name: ~
            width: 750
            height:
            crop: false
            occurrence: 'Front-end: Blog article detail'
        -   name: list
            width: 540
            height: 364
            crop: true
            occurrence: 'Front-end: Blog article list'
            additionalSizes:
                - {width: 269, height: 209, media: "(max-width: 768px)"}
        -   name: searchThumbnail
            width: 116
            height: 78
            crop: true
            occurrence: 'Front-end: Blog article thumbnail'
        -   name: listBig
            width: 549
            height: 390
            crop: true
            occurrence: 'Front-end: Blog article list with big images'

-   name: notificationBar
    class: App\Model\NotificationBar\NotificationBar
    sizes:
        -   name: ~
            width: ~
            height: 28
            crop: false
            occurrence: 'Front-end: Notification bar'
