services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    resolverMaps:
        namespace: App\FrontendApi\
        resource: '../src/FrontendApi/**/*{Map}.php'
        tags:
            - { name: overblog_graphql.resolver_map, schema: default }

    App\FrontendApi\:
        resource: '../src/FrontendApi/**/*{Mutation}.php'

    Shopsys\FrontendApiBundle\Model\Resolver\Products\PromotedProductsResolver:
        alias: App\FrontendApi\Model\Resolver\Products\PromotedProductsResolver
        public: true

    Shopsys\FrontendApiBundle\Model\Product\ProductFacade:
        alias: App\FrontendApi\Model\Product\ProductFacade

    Shopsys\FrontendApiBundle\Model\Product\Filter\ProductFilterDataMapper:
        alias: App\FrontendApi\Model\Product\Filter\ProductFilterDataMapper

    Shopsys\FrontendApiBundle\Model\Order\OrderDataFactory:
        alias: App\FrontendApi\Model\Order\OrderDataFactory

    Shopsys\FrontendApiBundle\Model\Resolver\Products\DataMapper\ProductArrayFieldMapper:
        alias: App\FrontendApi\Model\Resolver\Products\DataMapper\ProductArrayFieldMapper

    Shopsys\FrontendApiBundle\Model\Resolver\Products\DataMapper\ProductEntityFieldMapper:
        alias: App\FrontendApi\Model\Resolver\Products\DataMapper\ProductEntityFieldMapper

    Shopsys\FrontendApiBundle\Model\Resolver\Products\ProductResolverMap:
        alias: App\FrontendApi\Model\Resolver\Products\ProductResolverMap

    Shopsys\FrontendApiBundle\Model\Parameter\ParameterWithValuesFactory:
        alias: App\FrontendApi\Model\Parameter\ParameterWithValuesFactory

    Shopsys\FrontendApiBundle\Model\Mutation\Customer\User\CustomerUserMutation:
        alias: App\FrontendApi\Model\Mutation\Customer\User\CustomerUserMutation

    Shopsys\FrontendApiBundle\Model\Customer\User\CustomerUserUpdateDataFactory:
        alias: App\FrontendApi\Model\Customer\User\CustomerUserUpdateDataFactory

    Shopsys\FrontendApiBundle\Model\Resolver\Order\OrderResolverMap:
        alias: App\FrontendApi\Model\Order\OrderResolverMap

    Shopsys\FrontendApiBundle\Model\Resolver\Category\CategoryResolverMap:
        alias: App\FrontendApi\Model\Resolver\Category\CategoryResolverMap

    Shopsys\FrontendApiBundle\Model\Product\Filter\ProductFilterOptionsFactory:
        alias: App\FrontendApi\Model\Product\Filter\ProductFilterOptionsFactory

    Shopsys\FrontendApiBundle\Model\Resolver\Image\ImagesResolver:
        alias: App\FrontendApi\Model\Resolver\Image\ImagesResolver
        public: true

    Shopsys\FrontendApiBundle\Model\Resolver\Products\ProductsResolver:
        alias: App\FrontendApi\Model\Resolver\Products\ProductsResolver
        public: true

    Shopsys\FrontendApiBundle\Model\Resolver\Category\CategoryResolver:
        alias: App\FrontendApi\Model\Resolver\Category\CategoryResolver
        public: true

    Shopsys\FrontendApiBundle\Model\Resolver\Article\ArticleResolver:
        alias: App\FrontendApi\Model\Resolver\Article\ArticleResolver
        public: true

    Shopsys\FrontendApiBundle\Model\Resolver\Article\ArticlesResolver:
        alias: App\FrontendApi\Model\Resolver\Article\ArticlesResolver
        public: true

    Shopsys\FrontendApiBundle\Model\Mutation\Order\CreateOrderMutation:
        alias: App\FrontendApi\Model\Mutation\Order\CreateOrderMutation

    Shopsys\FrontendApiBundle\Model\Order\PlaceOrderFacade:
        alias: App\FrontendApi\Model\Order\PlaceOrderFacade

    Shopsys\FrontendApiBundle\Model\Product\Filter\ProductFilterFacade:
        alias: App\FrontendApi\Model\Product\Filter\ProductFilterFacade

    Shopsys\FrontendApiBundle\Model\Product\Connection\ProductConnectionFactory:
        alias: App\FrontendApi\Model\Product\Connection\ProductConnectionFactory
