# @deprecated This file content will be used on temporarily until next major, where it will be moved to framework
framework:
    test: true

parameters:
    overwrite_domain_url: '%env(OVERWRITE_DOMAIN_URL)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    Shopsys\FrameworkBundle\Component\Domain\Domain:
        alias: Shopsys\Cdn\Component\Domain\Domain

    Shopsys\Cdn\Component\Domain\Domain:
        factory: ['@Shopsys\Cdn\Component\Domain\DomainFactoryOverwritingDomainUrl', create]
        arguments:
            - '%shopsys.domain_config_filepath%'
            - '%shopsys.domain_urls_config_filepath%'
        lazy: true

    Shopsys\Cdn\Component\Domain\DomainFactoryOverwritingDomainUrl:
        class: Shopsys\Cdn\Component\Domain\DomainFactoryOverwritingDomainUrl
        arguments:
            - '%env(OVERWRITE_DOMAIN_URL)%'

    Shopsys\FrameworkBundle\Component\Elasticsearch\IndexDefinitionLoader:
        arguments:
            $indexDefinitionsDirectory: '%shopsys.elasticsearch.structure_dir%'
            $indexPrefix: 'test_%env(ELASTIC_SEARCH_INDEX_PREFIX)%'
