imports:
    - { resource: forms.yml }
    - { resource: services/*.yml }
    - { resource: paths.yml }
    - { resource: parameters_common.yml }
    - { resource: parameters.yml }
    - { resource: directories.yml }

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    _instanceof:
        App\Component\Placeholder\PlaceholderInterface:
            tags: ['shopsys.placeholder']

    App\Controller\:
        resource: '../src/Controller/'
        public: true
        tags: ['controller.service_arguments']

    App\:
        resource: '../src/**/*{Calculation,Facade,Factory,Generator,Handler,InlineEdit,Listener,Loader,Mapper,Parser,Provider,Recalculator,Registry,Repository,Resolver,Service,Scheduler,Subscriber,Transformer,Validator,Transfer,Helper,Converter}.php'
        exclude: '../src/{Command,Controller,DependencyInjection,Form,Migrations,Resources,Twig}'

    League\Flysystem\MountManager:
        arguments:
            -
                local: '@local_filesystem'
                main: '@main_filesystem'

    App\Component\Doctrine\QueryBuilderExtender: ~

    Shopsys\FrameworkBundle\Component\Doctrine\QueryBuilderExtender: '@App\Component\Doctrine\QueryBuilderExtender'

    Shopsys\FrameworkBundle\Model\Customer\User\CustomerUserUpdateDataFactory:
        class: 'App\Model\Customer\User\CustomerUserUpdateDataFactory'

    App\Model\Customer\User\RegistrationDataFactory: ~

    App\Model\Customer\User\RegistrationDataFactoryInterface: '@App\Model\Customer\User\RegistrationDataFactory'

    App\Model\Customer\User\RegistrationFacade: ~

    App\Model\Customer\User\RegistrationFacadeInterface: '@App\Model\Customer\User\RegistrationFacade'

    Shopsys\FrameworkBundle\Model\Customer\User\CustomerUserFacade:
        class: 'App\Model\Customer\User\CustomerUserFacade'

    App\Model\Blog\BlogVisibilityRecalculationListener:
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }

    App\Model\Product\Series\ProductSeriesFacade: ~

    App\Model\Product\Series\ProductSeriesFacadeInterface: '@App\Model\Product\Series\ProductSeriesFacade'

    App\Model\Product\Series\ProductSeriesFactory: ~

    App\Model\Product\Series\ProductSeriesFactoryInterface: '@App\Model\Product\Series\ProductSeriesFactory'

    App\Model\Product\Series\ProductSeriesDataFactory: ~

    App\Model\Product\Series\ProductSeriesDataFactoryInterface: '@App\Model\Product\Series\ProductSeriesDataFactory'

    App\Model\Product\Series\Grid\ProductSeriesGridFactory: ~

    Shopsys\FrameworkBundle\Component\Router\FriendlyUrl\FriendlyUrlFacade:
        class: App\Component\Router\FriendlyUrl\FriendlyUrlFacade

    Shopsys\FrameworkBundle\Component\Router\FriendlyUrl\FriendlyUrlFactory:
        class: App\Component\Router\FriendlyUrl\FriendlyUrlFactory

    App\Component\Router\FriendlyUrl\FriendlyUrlFactory: ~

    App\Component\Router\FriendlyUrl\FriendlyUrlFactoryInterface: '@App\Component\Router\FriendlyUrl\FriendlyUrlFactory'

    Shopsys\FrameworkBundle\Component\Router\FriendlyUrl\FriendlyUrlFactoryInterface: '@App\Component\Router\FriendlyUrl\FriendlyUrlFactory'

    Shopsys\FrameworkBundle\Component\Router\FriendlyUrl\FriendlyUrlUniqueResultFactory:
        class: App\Component\Router\FriendlyUrl\FriendlyUrlUniqueResultFactory

    App\Form\Front\Order\DomainAwareOrderFlowFactory: ~

    Shopsys\FrameworkBundle\Model\Order\PromoCode\PromoCodeDataFactoryInterface: '@App\Model\Order\PromoCode\PromoCodeDataFactory'

    Shopsys\FrameworkBundle\Model\Order\PromoCode\PromoCodeFacade: '@App\Model\Order\PromoCode\PromoCodeFacade'

    Shopsys\FrameworkBundle\Model\Order\PromoCode\PromoCodeRepository: '@App\Model\Order\PromoCode\PromoCodeRepository'

    Shopsys\FrameworkBundle\Model\Order\PromoCode\Grid\PromoCodeGridFactory: '@App\Model\Order\PromoCode\Grid\PromoCodeGridFactory'

    Shopsys\FrameworkBundle\Model\Order\PromoCode\CurrentPromoCodeFacade: '@App\Model\Order\PromoCode\CurrentPromoCodeFacade'

    Shopsys\FrameworkBundle\Model\Customer\BillingAddressDataFactory:
        class: 'App\Model\Customer\BillingAddressDataFactory'

    Shopsys\FrameworkBundle\Model\Order\OrderFlowFactoryInterface: '@App\Form\Front\Order\DomainAwareOrderFlowFactory'

    Shopsys\FrameworkBundle\Model\Article\ArticleDataFactoryInterface: '@App\Model\Article\ArticleDataFactory'

    App\Model\Category\CurrentCategoryResolver: ~

    League\Flysystem\FilesystemInterface: '@main_filesystem'

    Shopsys\FrameworkBundle\Model\Administrator\AdministratorFacade: '@App\Model\Administrator\AdministratorFacade'

    Shopsys\FrameworkBundle\Model\Administrator\AdministratorDataFactoryInterface: '@App\Model\Administrator\AdministratorDataFactory'

    Shopsys\FrameworkBundle\Model\Category\CategoryDataFactoryInterface: '@App\Model\Category\CategoryDataFactory'

    Shopsys\FrameworkBundle\Model\Category\CategoryFacade: '@App\Model\Category\CategoryFacade'

    Shopsys\FrameworkBundle\Model\Category\CategoryRepository: '@App\Model\Category\CategoryRepository'

    Shopsys\FrameworkBundle\Model\Customer\User\CustomerUserDataFactoryInterface: '@App\Model\Customer\User\CustomerUserDataFactory'

    Shopsys\FrameworkBundle\Model\Order\OrderDataFactoryInterface: '@App\Model\Order\OrderDataFactory'

    Shopsys\FrameworkBundle\Model\Order\FrontOrderDataMapper: '@App\Model\Order\FrontOrderDataMapper'

    Shopsys\FrameworkBundle\Model\Order\Item\OrderItemDataFactoryInterface: '@App\Model\Order\Item\OrderItemDataFactory'

    Shopsys\FrameworkBundle\Model\Order\Item\OrderItemFactory: '@App\Model\Order\Item\OrderItemFactory'

    Shopsys\FrameworkBundle\Model\Order\Item\OrderItemFactoryInterface: '@App\Model\Order\Item\OrderItemFactory'

    App\Model\Order\OrderDataMapper: ~

    Shopsys\FrameworkBundle\Model\Order\OrderDataMapper: '@App\Model\Order\OrderDataMapper'

    Shopsys\FrameworkBundle\Model\Transport\TransportDataFactoryInterface: '@App\Model\Transport\TransportDataFactory'

    Shopsys\FrameworkBundle\Model\Payment\PaymentDataFactoryInterface: '@App\Model\Payment\PaymentDataFactory'

    Shopsys\FrameworkBundle\Model\Product\ProductDataFactoryInterface: '@App\Model\Product\ProductDataFactory'

    Shopsys\FrameworkBundle\Model\Product\ProductRepository: '@App\Model\Product\ProductRepository'

    Shopsys\FrameworkBundle\Model\Product\ProductOnCurrentDomainFacadeInterface: '@Shopsys\FrameworkBundle\Model\Product\ProductOnCurrentDomainElasticFacade'

    Shopsys\ReadModelBundle\Product\Listed\ListedProductViewFacadeInterface: '@Shopsys\ReadModelBundle\Product\Listed\ListedProductViewElasticFacade'

    Shopsys\ReadModelBundle\Product\Listed\ListedProductViewElasticFacade: ~

    Shopsys\FrameworkBundle\Model\Product\Brand\BrandDataFactoryInterface: '@App\Model\Product\Brand\BrandDataFactory'

    Shopsys\FrameworkBundle\Model\Country\CountryFacade:
        class: 'App\Model\Country\CountryFacade'

    App\DataFixtures\Performance\CategoryDataFixture:
        arguments:
            - "%shopsys.performance_data.category.counts_by_level%"

    App\DataFixtures\Performance\OrderDataFixture:
        arguments:
            - "%shopsys.performance_data.order.total_count%"
            - "%shopsys.performance_data.order.item_count_per_order%"

    App\DataFixtures\Performance\ProductDataFixture:
        arguments:
            - "%shopsys.performance_data.product.total_count%"

    App\DataFixtures\Performance\CustomerUserDataFixture:
        arguments:
            - "%shopsys.performance_data.user.count_per_domain%"

    App\DataFixtures\Demo\ImageDataFixture:
        arguments:
            - '%shopsys.data_fixtures_images.resources_dir%'
            - '%shopsys.image_dir%'
            - '%shopsys.domain_images_dir%'
        tags: ['doctrine.fixture.orm']

    Shopsys\FrameworkBundle\Controller\Admin\DefaultController:
        class: 'App\Controller\Admin\DefaultController'

    Shopsys\FrameworkBundle\Controller\Admin\OrderController:
        class: 'App\Controller\Admin\OrderController'

    Shopsys\FrameworkBundle\Controller\Admin\PromoCodeController:
        class: 'App\Controller\Admin\PromoCodeController'
        arguments:
            $useInlineEditation: false

    Shopsys\FrameworkBundle\Controller\Admin\ArticleController:
        class: 'App\Controller\Admin\ArticleController'

    sensio_framework_extra.routing.loader.annot_class:
        class: App\Component\AnnotatedRouteControllerLoader
        arguments:
            - '@annotation_reader'

    App\Controller\Front\ErrorController:
        arguments:
            $environment: '%kernel.environment%'

    App\Component\Akeneo\AkeneoConfig:
        arguments:
            $akeneoConfig: "%akeneo_config%"

    App\Component\Akeneo\AkeneoClientFactory: ~

    App\Model\Product\Transfer\Akeneo\AkeneoImportProductFacade:

    App\Model\Product\Transfer\Akeneo\AkeneoImportAssemblyInstructionProductFilesFacade:
        arguments:
            $productFilesDir: "%shopsys.product_files_dir%"

    App\Model\Product\Transfer\Akeneo\AkeneoImportProductTypePlanProductFilesFacade:
        arguments:
            $productFilesDir: "%shopsys.product_files_dir%"

    Akeneo\PimEnterprise\ApiClient\AkeneoPimEnterpriseClientInterface:
        factory: ['@App\Component\Akeneo\AkeneoClientFactory', createClient]

    App\Component\Akeneo\Transfer\AkeneoImportTransferDependency: ~

    App\Component\Setting\Setting: ~

    Shopsys\FrameworkBundle\Component\Elasticsearch\IndexRepository: '@App\Component\Elasticsearch\IndexRepository'

    Shopsys\FrameworkBundle\Component\Setting\Setting: '@App\Component\Setting\Setting'

    Shopsys\ReadModelBundle\Product\Listed\ListedProductViewFactory: '@App\Model\Product\Listed\ListedProductViewFactory'

    Shopsys\FrameworkBundle\Model\Order\OrderFacade: '@App\Model\Order\OrderFacade'

    App\Model\Order\Preview\OrderPreviewCalculation: ~

    Shopsys\FrameworkBundle\Model\Order\Preview\OrderPreviewCalculation: '@App\Model\Order\Preview\OrderPreviewCalculation'

    Shopsys\FrameworkBundle\Model\Order\Preview\OrderPreviewFactory: '@App\Model\Order\Preview\OrderPreviewFactory'

    App\Model\Product\Pricing\QuantifiedProductDiscountCalculation: ~

    Shopsys\FrameworkBundle\Model\Product\Pricing\QuantifiedProductDiscountCalculation: '@App\Model\Product\Pricing\QuantifiedProductDiscountCalculation'

    Shopsys\FrameworkBundle\Model\Product\ProductBreadcrumbGenerator: '@App\Model\Product\ProductBreadcrumbGenerator'

    App\Model\Product\ProductFacade:
        arguments:
            $productFilesUrlPrefix: '%shopsys.product_files_url_prefix%'

    Shopsys\FrameworkBundle\Model\Product\ProductFacade: '@App\Model\Product\ProductFacade'

    Shopsys\FrameworkBundle\Model\Product\Elasticsearch\ProductExportRepository: '@App\Model\Product\Elasticsearch\ProductExportRepository'

    Shopsys\FrameworkBundle\Model\Product\ProductOnCurrentDomainFacade: '@App\Model\Product\ProductOnCurrentDomainFacade'

    Shopsys\FrameworkBundle\Model\Product\Filter\PriceRangeRepository: '@App\Model\Product\Filter\PriceRangeRepository'

    Shopsys\FrameworkBundle\Model\Product\Filter\ParameterFilterChoiceRepository: '@App\Model\Product\Filter\ParameterFilterChoiceRepository'

    Shopsys\FrameworkBundle\Model\Product\Pricing\ProductPriceCalculation: '@App\Model\Product\Pricing\ProductPriceCalculation'

    Shopsys\FrameworkBundle\Model\Product\Listing\ProductListAdminRepository: '@App\Model\Product\Listing\ProductListAdminRepository'

    App\Model\Product\Pricing\ProductPriceCalculationForCustomerUser: ~

    Shopsys\FrameworkBundle\Model\Product\Pricing\ProductPriceCalculationForCustomerUser: '@App\Model\Product\Pricing\ProductPriceCalculationForCustomerUser'

    Shopsys\FrameworkBundle\Model\Product\ProductCachedAttributesFacade: '@App\Model\Product\ProductCachedAttributesFacade'

    Shopsys\FrameworkBundle\Model\Product\ProductVisibilityRepository: '@App\Model\Product\ProductVisibilityRepository'

    Shopsys\FrameworkBundle\Model\Product\Availability\ProductAvailabilityCalculation: '@App\Model\Product\Availability\ProductAvailabilityCalculation'

    App\Model\Product\Search\ProductElasticsearchConverter: ~

    App\Model\Product\Search\FilterQuery: ~

    Shopsys\FrameworkBundle\Model\Product\Search\FilterQuery: '@App\Model\Product\Search\FilterQuery'

    Shopsys\FrameworkBundle\Model\Product\Search\ProductElasticsearchConverter: '@App\Model\Product\Search\ProductElasticsearchConverter'

    Shopsys\FrameworkBundle\Model\Product\Search\ProductElasticsearchRepository: '@App\Model\Product\Search\ProductElasticsearchRepository'

    App\Model\Product\Search\FilterQueryFactory: ~

    Shopsys\FrameworkBundle\Model\Product\Search\FilterQueryFactory: '@App\Model\Product\Search\FilterQueryFactory'

    Shopsys\ProductFeed\GoogleBundle\Model\FeedItem\GoogleFeedItemFactory: '@App\Model\ProductFeed\Google\FeedItem\GoogleFeedItemFactory'

    Shopsys\ProductFeed\HeurekaBundle\Model\FeedItem\HeurekaFeedItemFactory: '@App\Model\ProductFeed\Heureka\FeedItem\HeurekaFeedItemFactory'

    Shopsys\ProductFeed\ZboziBundle\Model\FeedItem\ZboziFeedItemFactory: '@App\Model\ProductFeed\Zbozi\FeedItem\ZboziFeedItemFactory'

    App\Component\Form\FormBuilderHelper:
        arguments:
            $disableFields: '%disable_form_fields_from_transfer%'

    Shopsys\FrameworkBundle\Model\Slider\SliderItemDataFactory: '@App\Model\Slider\SliderItemDataFactory'

    Shopsys\FrameworkBundle\Model\Slider\SliderItemRepository: '@App\Model\Slider\SliderItemRepository'

    Shopsys\FrameworkBundle\Model\Advert\AdvertDataFactory: '@App\Model\Advert\AdvertDataFactory'

    Shopsys\FrameworkBundle\Model\Advert\AdvertRepository: '@App\Model\Advert\AdvertRepository'

    App\Model\Transfer\TransferLoggerFactory:
        arguments:
            - '@monolog.logger.cron'

    App\Component\ScontoBridge\ScontoBridgeConfig:
        arguments:
            $scontoBridgeConfig: "%sconto_bridge_config%"

    App\Component\ScontoBridge\ScontoBridgeClient: ~

    App\Component\ScontoBridge\Transfer\ScontoBridgeImportTransferDependency: ~

    App\Component\Placeholder\:
        resource: '../src/Component/Placeholder/**/*{Extension,Placeholder,Validator}.php'

    App\Component\Placeholder\PlaceholderConverter:
        public: true
        arguments:
            $placeholders: !tagged shopsys.placeholder

    Shopsys\FrameworkBundle\Model\Customer\User\CustomerUserRepository: '@App\Model\Customer\User\CustomerUserRepository'

    Shopsys\FrameworkBundle\Model\Product\Parameter\ParameterRepository: '@App\Model\Product\Parameter\ParameterRepository'

    app.maintenance_cache_provider:
        class: Doctrine\Common\Cache\RedisCache
        factory: 'Shopsys\FrameworkBundle\Component\Doctrine\Cache\RedisCacheFactory:create'
        arguments:
            - '@snc_redis.global'

    App\Component\Maintenance\MaintenanceModeSubscriber:
        arguments:
            - '@app.maintenance_cache_provider'
        tags:
            - { name: kernel.event_subscriber }

    App\Command\MaintenanceModeCommand:
        arguments:
            - '@app.maintenance_cache_provider'

    App\Component\FileSystem\FileSystemFactoryDecorator:
        decorates: Shopsys\FrameworkBundle\Component\Filesystem\MainFilesystemFactory
        arguments:
            $inner: '@App\Component\FileSystem\FilesystemFactoryDecorator.inner'
            $s3ApiHost: '%env(S3_API_HOST)%'
            $s3ApiUsername: '%env(S3_API_USERNAME)%'
            $s3ApiPassword: '%env(S3_API_PASSWORD)%'
            $s3ApiBucketName: '%env(S3_API_BUCKET_NAME)%'

    App\Component\NinjaMutex\Lock\NullLock: ~

    NinjaMutex\Lock\LockInterface:
        class: App\Component\NinjaMutex\Lock\NullLock

    App\Model\Svg\SvgProvider:
        arguments:
            $svgDirectoryPath: "%svg_icon_path%"
