services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Shopsys\FrameworkBundle\Component\ClassExtension\ClassExtensionRegistry:
        arguments:
            - '%shopsys.entity_extension.map%'
            - '%shopsys.framework.root_dir%'

    App\Command\ExtendedClassesAnnotationsCommand:
        arguments:
            - '%shopsys.root_dir%'

    Shopsys\FrameworkBundle\Command\ExtendedClassesAnnotationsCommand:
        alias: App\Command\ExtendedClassesAnnotationsCommand

    App\Component\Collector\TwigCacheDataCollector:
        arguments:
            - '%env(bool:TWIG_CACHE_ENABLED)%'
        tags:
            -   name: data_collector
                template: 'DataCollector/twig_cache_collector.html.twig'
                id: 'app.twig_cache_collector'
