services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    resolverMaps:
        namespace: App\FrontendApi\
        resource: '../src/FrontendApi/**/*{Map}.php'
        tags:
            - { name: overblog_graphql.resolver_map, schema: default }

    Shopsys\FrontendApiBundle\Model\Resolver\Products\PromotedProductsResolver:
        alias: App\FrontendApi\Model\Resolver\Products\PromotedProductsResolver

    Shopsys\FrontendApiBundle\Model\Product\ProductFacade:
        alias: App\FrontendApi\Model\Product\ProductFacade

    Shopsys\FrontendApiBundle\Model\Product\Filter\ProductFilterDataMapper:
        alias: App\FrontendApi\Model\Product\Filter\ProductFilterDataMapper

    Shopsys\FrontendApiBundle\Model\Order\OrderDataFactory:
        alias: App\FrontendApi\Model\Order\OrderDataFactory

    Shopsys\FrontendApiBundle\Model\Resolver\Products\DataMapper\ProductArrayFieldMapper:
        alias: App\FrontendApi\Model\Resolver\Products\DataMapper\ProductArrayFieldMapper

    Shopsys\FrontendApiBundle\Model\Resolver\Products\ProductResolverMap:
        alias: App\FrontendApi\Model\Resolver\Products\ProductResolverMap

    Shopsys\FrontendApiBundle\Model\Parameter\ParameterWithValuesFactory:
        alias: App\FrontendApi\Model\Parameter\ParameterWithValuesFactory
