fragment TransportWithAvailablePaymentsFragment on Transport {
    __typename
    uuid
    name
    description
    price {
        ...PriceFragment
    }
    mainImage {
        ...ImageFragment
    }
    group {
        uuid
        name
        position
        mainImage {
            ...ImageFragment
        }
    }
    payments {
        ...SimplePaymentFragment
    }
    expectedDeliveryDate
    transportTypeCode
    productsBlockingSelectionInCart {
        reason
        products {
            uuid
            fullName
            mainImage {
                ...ImageFragment
            }
        }
    }
    vatPercent
}
