NavigationQuery:
    type: object
    config:
        fields:
            navigation:
                type: '[NavigationItem!]!'
                resolve: "@=resolver('resolveNavigation')"
                description: "Returns complete navigation menu"
