ComplaintItemInputDecorator:
    type: input-object
    decorator: true
    config:
        fields:
            orderItemUuid:
                type: "Uuid"
                description: "UUID of the order item"
                validation:
                    -   NotBlank:
                            message: "Order item is required"
                            groups: ["withOrder"]
            manualComplaintItemName:
                type: "String"
                defaultValue: null
                description: "Name of the complaint item entered by customer (if the complaint is created without an order, otherwise, the name is taken from the order item)"
                validation:
                    -   NotBlank:
                            message: "Complaint item name is required"
                            groups: ["withoutOrder"]
                    -   Length:
                            max: 255
                            maxMessage: "Complaint item name cannot be longer than {{ limit }} characters"
            manualComplaintItemCatnum:
                type: "String"
                defaultValue: null
                description: "Catalog number of the complaint item entered by customer (if the complaint is created without an order, otherwise, the catalog number is taken from the order item)"
                validation:
                    -   Length:
                            max: 255
                            maxMessage: "Complaint item catnum cannot be longer than {{ limit }} characters"
            quantity:
                type: "Int!"
                description: "Quantity of the complaint item"
                validation:
                    -   NotBlank:
                            message: "Please enter quantity"
                    -   Type:
                            type: "integer"
                            message: "Quantity must be an integer"
                    -   Range:
                            min: 1
                            minMessage: "Quantity must be greater than 0"
            description:
                type: "String!"
                description: "Description of the complaint item"
                validation:
                    -   NotBlank:
                            message: "Description is required"
            files:
                type: "[FileUpload!]"
                description: "Files attached to the complaint item"
                validation:
                  -   NotBlank:
                        message: "Please attach files"
                  -   \Shopsys\FrontendApiBundle\Component\Constraints\FileUpload:
                        mimeTypes: ['image/jpeg', 'image/png']
                        maxSize: 10485760
