ComplaintInputDecorator:
    type: input-object
    decorator: true
    config:
        validation:
            -   Shopsys\FrontendApiBundle\Component\Constraints\ComplaintResolution: ~
        fields:
            orderUuid:
                type: "Uuid"
                description: "UUID of the order"
                defaultValue: null
                validation:
                    -   NotBlank:
                            message: "Order is required"
                            groups: ["withOrder"]
            manualDocumentNumber:
                type: "String"
                defaultValue: null
                description: "Order or document number (doesn't have to be from any existing order)"
                validation:
                    -   NotBlank:
                            message: "Order or document number is required"
                            groups: ["withoutOrder"]
                    -   Length:
                            max: 255
                            maxMessage: "Order or document number cannot be longer than {{ limit }} characters"
            deliveryAddress:
                type: "DeliveryAddressInput!"
                description: "Delivery address"
                validation: cascade
            items:
                type: "[ComplaintItemInput!]!"
                description: "All items in the complaint"
                validation: cascade
            email:
                type: "String!"
                description: "The customer's email address"
                validation:
                    -   NotBlank:
                            message: "Please enter email"
                    -   Email:
                            message: "Please enter valid email"
                    -   Length:
                            max: 255
                            maxMessage: "Email cannot be longer than {{ limit }} characters"
            resolution:
                type: "String!"
                description: "Chosen resolution from complaintResolutionQuery"
                validation:
                    -   NotBlank:
                            message: "Resolution is required"
            bankAccountNumber:
                type: "String"
                description: "Bank account number for money return"
                defaultValue: null
                validation:
                    -   Length:
                            max: 34
                            maxMessage: "Bank account number cannot be longer than {{ limit }} characters"
                    -   Regex:
                            pattern: '/^[a-zA-Z0-9\/\-]+$/'
                            message: "Bank account number can contain only letters, numbers, slashes and dashes"
