query ArticlesQuery(
    $first: Int
    $last: Int
    $before: String
    $after: String
    $placement: [ArticlePlacementTypeEnum!]
) {
    articles(first: $first, last: $last, before: $before, after: $after, placement: $placement) {
        edges {
            node {
                ... on ArticleSite {
                    uuid
                    name
                    placement
                    text
                    seo {
                        title
                        metaDescription
                        h1
                        metaRobots
                        canonicalUrl
                    }
                    slug
                    breadcrumb {
                        slug
                        name
                    }
                }
            }
        }
        totalCount
        pageInfo {
            startCursor
            endCursor
            hasPreviousPage
            hasNextPage
        }
    }
}
