query CurrentCustomerUser {
    currentCustomerUser {
        firstName
        lastName
        email
        telephone
        telephoneData {
            countryCode
            prefix
            number
        }
        newsletterSubscription
        street
        city
        postcode
        country {
            code
        }
        defaultDeliveryAddress {
            uuid
            companyName
            street
            city
            postcode
            telephone
            telephoneData {
                countryCode
                prefix
                number
            }
            country {
                code
            }
            firstName
            lastName
        }
        deliveryAddresses {
            uuid
            companyName
            street
            city
            postcode
            telephone
            telephoneData {
                countryCode
                prefix
                number
            }
            country {
                code
            }
            firstName
            lastName
        }
        ... on CurrentCompanyCustomerUser {
            companyName
            companyNumber
            companyTaxNumber
        }
        __typename
    }
}
