fragment CartItemFragment on CartItem {
    __typename
    uuid
    quantity
    product {
        __typename
        uuid
        slug
        fullName
        catalogNumber
        stockQuantity
        flags {
            ...SimpleFlagFragment
        }
        ...ProductImagesListFragment
        stockQuantity
        availability {
            ...AvailabilityFragment
        }
        ...ProductPriceFragment
        availableStoresCount
        unit {
            name
        }
        brand {
            ...SimpleBrandFragment
        }
        categories {
            name
        }
    }
}
