fragment CartModificationsFragment on CartInterface {
    __typename
    modifications{
        __typename
        itemModifications {
            __typename
            noLongerListableCartItems {
                ...CartItemFragment
            }
            cartItemsWithModifiedPrice {
                ...CartItemFragment
            }
            cartItemsWithChangedQuantity {
                ...CartItemFragment
            }
            noLongerAvailableCartItemsDueToQuantity {
                ...CartItemFragment
            }
        }
        transportModifications {
            __typename
            transportPriceChanged
            transportUnavailable
            transportWeightLimitExceeded
        }
        paymentModifications {
            __typename
            paymentPriceChanged
            paymentUnavailable
        }
    }
}
