services:
    _defaults:
        autoconfigure: true
        autowire: true
        public: false

    Shopsys\ProductFeed\ZboziBundle\:
        resource: '../../*'

    Shopsys\ProductFeed\ZboziBundle\DataFixtures\:
        resource: '../../DataFixtures/*'
        tags:
            - { name: shopsys.data_fixture }

    Shopsys\ProductFeed\ZboziBundle\Form\ZboziProductCrudExtension:
        tags:
            - { name: shopsys.crud_extension, type: product }

    Shopsys\ProductFeed\ZboziBundle\ZboziFeed:
        tags:
            - { name: shopsys.feed, cron: '0 3 * * *' }
