fragment OrderDetailFragment on Order {
    uuid
    number
    creationDate
    items {
        ...OrderDetailItemFragment
    }
    transport {
        name
    }
    payment {
        name
    }
    status
    firstName
    lastName
    email
    telephone
    companyName
    companyNumber
    companyTaxNumber
    street
    city
    postcode
    country {
        name
    }
    differentDeliveryAddress
    deliveryFirstName
    deliveryLastName
    deliveryCompanyName
    deliveryTelephone
    deliveryStreet
    deliveryCity
    deliveryPostcode
    deliveryCountry {
        name
    }
    note
    urlHash
    promoCode
    trackingNumber
    trackingUrl
}
