domains:
    -   id: 1
        load_demo_data: true
        locale: en
        name: B2C - EN
        timezone: Europe/Prague
        type: b2c

    -   id: 2
        load_demo_data: true
        locale: cs
        name: B2B - CZ
        timezone: Europe/Prague
        type: b2b

    -   id: 3
        load_demo_data: true
        locale: sk
        name: B2B - SK
        timezone: Europe/Prague
        type: b2b
