<?php

declare(strict_types=1);

namespace Shopsys\McpBundle\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Override;
use Shopsys\MigrationBundle\Component\Doctrine\Migrations\AbstractMigration;

class Version20260401100401 extends AbstractMigration
{
    #[Override]
    public function up(Schema $schema): void
    {
        $this->sql('
            CREATE TABLE administrator_mcp_tokens (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                public_token_id VARCHAR(32) NOT NULL,
                secret_hash VARCHAR(255) NOT NULL,
                created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                last_used_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
                revoked_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
                replaced_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
                administrator_id INT NOT NULL,
                PRIMARY KEY (id)
            )');
        $this->sql('CREATE UNIQUE INDEX UNIQ_5A30067464EAEB46 ON administrator_mcp_tokens (public_token_id)');
        $this->sql('CREATE INDEX IDX_5A3006744B09E92C ON administrator_mcp_tokens (administrator_id)');
        $this->sql('
            ALTER TABLE
                administrator_mcp_tokens
            ADD
                CONSTRAINT FK_5A3006744B09E92C FOREIGN KEY (administrator_id) REFERENCES administrators (id) ON DELETE CASCADE NOT DEFERRABLE');
    }
}
