
export const VISIBLE_SLIDER_ITEMS = 5;
export const VISIBLE_SLIDER_ITEMS_LAST_VISITED = 8;
export const VISIBLE_SLIDER_ITEMS_BLOG = 3;
export const VISIBLE_SLIDER_ITEMS_ARTICLE = 4;
export const VISIBLE_SLIDER_ITEMS_AUTOCOMPLETE = 5;