query CurrentCustomerUserProductReviews($productUuid: Uuid, $first: Int, $after: String) {
    currentCustomerUserProductReviews(productUuid: $productUuid, first: $first, after: $after) {
        totalCount
        edges {
            node {
                uuid
                reviewerName
                rating
                text
                createdAt
                isVerifiedPurchase
                responseText
                responseCreatedAt
                status
                rejectionReason
                rejectedImagesCount
                productUuid
                productName
                product {
                    uuid
                    slug
                    isVisible
                }
            }
        }
        pageInfo {
            hasNextPage
            endCursor
        }
    }
}
