query ProductReviews($productUuid: Uuid!, $first: Int, $after: String, $orderingMode: ProductReviewOrderingModeEnum) {
    productReviews(productUuid: $productUuid, first: $first, after: $after, orderingMode: $orderingMode) {
        totalCount
        orderingMode
        summary {
            averageRating
            totalCount
            ratingCounts {
                rating
                count
            }
        }
        edges {
            node {
                uuid
                reviewerName
                rating
                text
                createdAt
                isVerifiedPurchase
                responseText
                responseCreatedAt
                status
                rejectedImagesCount
                productUuid
                productName
            }
        }
        pageInfo {
            hasNextPage
            endCursor
        }
    }
}
