apiVersion: apps/v1
kind: Deployment
metadata:
    name: webserver-php-fpm
    labels:
        app: webserver-php-fpm
spec:
    progressDeadlineSeconds: 1500
    replicas: 1
    strategy:
        rollingUpdate:
            maxSurge: 1
            maxUnavailable: 0
        type: RollingUpdate
    selector:
        matchLabels:
            app: webserver-php-fpm
    template:
        metadata:
            labels:
                app: webserver-php-fpm
        spec:
            hostAliases:
                -   ip: "127.0.0.1"
                    hostnames:
                        - "webserver-php-fpm"
                        - "php-fpm"
                        - "webserver"
            volumes:
                -   name: source-codes
                    emptyDir: {}
                -   name: domains-urls
                    configMap:
                        name: domains-urls
                -   name: parameters
                    configMap:
                        name: parameters
                -   name: nginx-configuration
                    configMap:
                        name: nginx-configuration
                        items:
                            -   key: nginx.conf
                                path: default.conf
                -   name: nginx-default-config
                    configMap:
                        name: nginx-default-config
            initContainers:
                -   name: copy-source-codes-to-volume
                    image: "{{TAG}}"
                    securityContext:
                        runAsUser: 33
                    command: ["sh", "-c", "cp -r /var/www/html/. /tmp/source-codes"]
                    volumeMounts:
                        -   name: source-codes
                            mountPath: /tmp/source-codes
                        -   name: domains-urls
                            mountPath: /var/www/html/config/domains_urls.yml
                            subPath: domains_urls.yml
                        -   name: parameters
                            mountPath: /var/www/html/config/parameters.yml
                            subPath: parameters.yml
            containers:
                -   image: "{{TAG}}"
                    name: php-fpm
                    securityContext:
                        runAsUser: 33
                    imagePullPolicy: Always
                    workingDir: /var/www/html
                    lifecycle:
                        postStart:
                            exec:
                                command: ["/var/www/html/phing", "maintenance-off", "clean-redis-old"]
                    volumeMounts:
                        -   name: source-codes
                            mountPath: /var/www/html
                        -   name: domains-urls
                            mountPath: /var/www/html/config/domains_urls.yml
                            subPath: domains_urls.yml
                        -   name: parameters
                            mountPath: /var/www/html/config/parameters.yml
                            subPath: parameters.yml
                    env:
                        -   name: S3_API_HOST
                            value: "{{S3_API_HOST}}"
                        -   name: S3_API_USERNAME
                            value: "{{S3_API_USERNAME}}"
                        -   name: S3_API_PASSWORD
                            value: "{{S3_API_PASSWORD}}"
                        -   name: S3_API_BUCKET_NAME
                            value: "{{S3_API_BUCKET_NAME}}"
                        -   name: REDIS_PREFIX
                            value: "{{REDIS_PREFIX}}"
                        -   name: ELASTIC_SEARCH_INDEX_PREFIX
                            value: "{{ELASTIC_SEARCH_INDEX_PREFIX}}"
                -   image: nginx:1.13.10-alpine
                    name: webserver
                    ports:
                        -   containerPort: 8080
                            name: http
                    volumeMounts:
                        -   name: nginx-configuration
                            mountPath: /etc/nginx/conf.d
                        -   name: nginx-default-config
                            mountPath: /etc/nginx/nginx.conf
                            subPath: nginx.conf
                        -   name: source-codes
                            mountPath: /var/www/html
                    lifecycle:
                        preStop:
                            exec:
                                command:
                                    - nginx -s quit
            imagePullSecrets:
                -   name: dockerregistry
