SlugQuery:
    type: object
    config:
        fields:
            slug:
                type: 'Slug'
                resolve: "@=resolver('slugResolver', [args['slug'], info])"
                description: "Returns entity by slug"
                args:
                    slug:
                        type: "String!"
