services:
    _defaults:
        autoconfigure: true
        autowire: true
        public: false

    Shopsys\ProductFeed\MergadoBundle\:
        resource: '../../*'

    Shopsys\ProductFeed\MergadoBundle\MergadoFeed:
        tags:
            - { name: shopsys.feed, cron: '0 5 * * *' }
