services:
    _defaults:
        autoconfigure: true
        autowire: true
        public: false

    Shopsys\FrontendApiBundle\:
        resource: '../../**/*{Context,Facade,Factory,Helper,Listener,Loader,Mapper,Mutation,Provider,Query,Repository,Subscriber,Transformer,Validator}.php'

    resolverMaps:
        namespace: Shopsys\FrontendApiBundle\
        resource: '../../**/*{Map}.php'
        tags:
            - { name: overblog_graphql.resolver_map, schema: default }

    Shopsys\FrameworkBundle\Model\Customer\User\CustomerUserLoginInformationProvider:
        alias: Shopsys\FrontendApiBundle\Model\Customer\User\CustomerUserLoginInformationProvider

    Shopsys\FrameworkBundle\Model\Security\LoginAdministratorAsUserUrlProvider:
        alias: Shopsys\FrontendApiBundle\Model\Security\LoginAdministratorAsUserUrlProvider

    Shopsys\FrontendApiBundle\Component\GqlContext\GqlContextInitializer: ~

    Shopsys\FrontendApiBundle\Component\HttpFoundation\GraphqlBatchRequestValidator:
        arguments:
            $maxOperations: '%shopsys.frontend_api.max_batch_operations%'

    Shopsys\FrontendApiBundle\Component\HttpFoundation\GraphqlMutationErrorRollbackSubscriber: ~

    Shopsys\FrontendApiBundle\Component\HttpFoundation\GraphqlOperationTypeResolver: ~

    Shopsys\FrontendApiBundle\Controller\Admin\CustomerUserController:
        tags: [ 'controller.service_arguments' ]

    Shopsys\FrontendApiBundle\Controller\FrontendApiController:
        tags: [ 'controller.service_arguments' ]

    Shopsys\FrontendApiBundle\Controller\SocialNetworkController:
        tags: [ 'controller.service_arguments' ]

    Shopsys\FrontendApiBundle\Model\Blog\Category\BlogCategoryResolverMap:
        arguments:
            $blogCategorySlugBatchLoader: '@blog_category_slug_batch_loader'
        tags:
            - { name: overblog_graphql.resolver_map, schema: default }

    Shopsys\FrontendApiBundle\Model\Category\ReadyCategorySeoMixBatchLoader:
        arguments:
            $mainFriendlyUrlSlugCache: '@main_friendly_url_slug_cache'

    Shopsys\FrontendApiBundle\Model\Error\ErrorHandlerListener:
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException, priority: 20 }

    Shopsys\FrontendApiBundle\Model\Flag\FlagResolverMap:
        arguments:
            $flagSlugBatchLoader: '@flag_slug_batch_loader'
        tags:
            - { name: overblog_graphql.resolver_map, schema: default }

    Shopsys\FrontendApiBundle\Model\FriendlyUrl\FriendlyUrlSlugBatchLoader:
        arguments:
            $mainFriendlyUrlSlugCache: '@main_friendly_url_slug_cache'

    Shopsys\FrontendApiBundle\Model\GraphqlConfigurator:
        arguments:
            $maxQueryComplexity: '%overblog_graphql.query_max_complexity%'

    Shopsys\FrontendApiBundle\Model\Logger\FrontendApiLogger:
        arguments:
            $logger: '@monolog.logger'
            $isValidationLoggedAsError: '%shopsys.frontend_api.validation_logged_as_error%'

    Shopsys\FrontendApiBundle\Model\Mutation\Login\LoginMutation:
        arguments:
            $loginRateLimiter: '@security.login_throttling.frontend_api.limiter'

    Shopsys\FrontendApiBundle\Model\Mutation\ProductReview\CreateProductReviewMutation:
        arguments:
            $productReviewCreateRateLimiter: '@limiter.frontend_api_product_review_create'

    Shopsys\FrontendApiBundle\Model\Product\Filter\ProductFilterNormalizer: ~

    Shopsys\FrontendApiBundle\Model\Resolver\Advert\AdvertResolverMap:
        arguments:
            $categoriesBatchLoader: '@categories_batch_loader'
        tags:
            - { name: overblog_graphql.resolver_map, schema: default }

    Shopsys\FrontendApiBundle\Model\Resolver\Article\Search\ArticlesSearchResultsProvider:
        tags:
            - { name: 'shopsys.frontend_api.articles_search_results_provider', priority: 1 }

    Shopsys\FrontendApiBundle\Model\Resolver\Article\Search\ArticlesSearchResultsProviderResolver:
        arguments:
            $articlesSearchResultsProviders: !tagged_iterator 'shopsys.frontend_api.articles_search_results_provider'

    Shopsys\FrontendApiBundle\Model\Resolver\Brand\BrandResolverMap:
        arguments:
            $brandSlugBatchLoader: '@brand_slug_batch_loader'
        tags:
            - { name: overblog_graphql.resolver_map, schema: default }

    Shopsys\FrontendApiBundle\Model\Resolver\Brand\Search\BrandSearchResultsProvider:
        tags:
            - { name: 'shopsys.frontend_api.brands_search_results_provider', priority: 1 }

    Shopsys\FrontendApiBundle\Model\Resolver\Brand\Search\BrandSearchResultsProviderResolver:
        arguments:
            $brandSearchResultsProviders: !tagged_iterator 'shopsys.frontend_api.brands_search_results_provider'

    Shopsys\FrontendApiBundle\Model\Resolver\Category\CategoryResolverMap:
        arguments:
            $readyCategorySeoMixesBatchLoader: '@ready_category_seo_mixes_batch_loader'
            $categoryChildrenBatchLoader: '@category_children_batch_loader'
            $categorySlugBatchLoader: '@category_slug_batch_loader'
            $categorySeoSlugBatchLoader: '@category_seo_slug_batch_loader'
        tags:
            - { name: overblog_graphql.resolver_map, schema: default }

    Shopsys\FrontendApiBundle\Model\Resolver\Category\Search\CategoriesSearchResultsProvider:
        tags:
            - { name: 'shopsys.frontend_api.categories_search_results_provider', priority: 1 }

    Shopsys\FrontendApiBundle\Model\Resolver\Category\Search\CategoriesSearchResultsProviderResolver:
        arguments:
            $categoriesSearchResultsProviders: !tagged_iterator 'shopsys.frontend_api.categories_search_results_provider'

    Shopsys\FrontendApiBundle\Model\Resolver\ConsumerUploadedFile\CustomerUploadedFileQuery:
        arguments:
            $customerUploadedFilesBatchLoader: '@customer_uploaded_files_batch_loader'

    Shopsys\FrontendApiBundle\Model\Resolver\Image\AdvertImagesQuery:
        arguments:
            $imagesBatchLoader: '@images_batch_loader'
            $firstImageBatchLoader: '@first_image_batch_loader'

    Shopsys\FrontendApiBundle\Model\Resolver\Image\BlogArticleAuthorImagesQuery:
        arguments:
            $imagesBatchLoader: '@images_batch_loader'
            $firstImageBatchLoader: '@first_image_batch_loader'

    Shopsys\FrontendApiBundle\Model\Resolver\Image\BlogArticleImagesQuery:
        arguments:
            $imagesBatchLoader: '@images_batch_loader'
            $firstImageBatchLoader: '@first_image_batch_loader'

    Shopsys\FrontendApiBundle\Model\Resolver\Image\BlogCategoryImagesQuery:
        arguments:
            $imagesBatchLoader: '@images_batch_loader'
            $firstImageBatchLoader: '@first_image_batch_loader'

    Shopsys\FrontendApiBundle\Model\Resolver\Image\CategoryOrReadyCategorySeoMixImagesQuery:
        arguments:
            $imagesBatchLoader: '@images_batch_loader'
            $firstImageBatchLoader: '@first_image_batch_loader'

    Shopsys\FrontendApiBundle\Model\Resolver\Image\ImagesQuery:
        arguments:
            $imagesBatchLoader: '@images_batch_loader'
            $firstImageBatchLoader: '@first_image_batch_loader'

    Shopsys\FrontendApiBundle\Model\Resolver\Image\ProductImagesCountQuery:
        arguments:
            $imagesCountBatchLoader: '@images_count_batch_loader'

    Shopsys\FrontendApiBundle\Model\Resolver\Image\ProductImagesQuery:
        arguments:
            $imagesBatchLoader: '@images_batch_loader'
            $firstImageBatchLoader: '@first_image_batch_loader'

    Shopsys\FrontendApiBundle\Model\Resolver\Image\SalesRepresentativeImagesQuery:
        arguments:
            $imagesBatchLoader: '@images_batch_loader'
            $firstImageBatchLoader: '@first_image_batch_loader'

    Shopsys\FrontendApiBundle\Model\Resolver\Image\SeoPageImagesQuery:
        arguments:
            $imagesBatchLoader: '@images_batch_loader'
            $firstImageBatchLoader: '@first_image_batch_loader'

    Shopsys\FrontendApiBundle\Model\Resolver\Image\StoreImagesQuery:
        arguments:
            $imagesBatchLoader: '@images_batch_loader'
            $firstImageBatchLoader: '@first_image_batch_loader'

    Shopsys\FrontendApiBundle\Model\Resolver\ProductReview\ProductReviewResolverMap:
        arguments:
            $productsVisibleByIdsBatchLoader: '@products_visible_by_ids_batch_loader'
        tags:
            - { name: overblog_graphql.resolver_map, schema: default }

    Shopsys\FrontendApiBundle\Model\Resolver\Products\BestsellingProductsQuery:
        arguments:
            $productsSellableInCategoryByIdsBatchLoader: '@products_sellable_in_category_by_ids_batch_loader'

    Shopsys\FrontendApiBundle\Model\Resolver\Products\DataMapper\ProductArrayFieldMapper:
        arguments:
            $productsSellableByIdsBatchLoader: '@products_sellable_by_ids_batch_loader'
            $productsVisibleByIdsBatchLoader: '@products_visible_by_ids_batch_loader'
            $productsVisibleCountByIdsBatchLoader: '@products_visible_count_by_ids_batch_loader'

    Shopsys\FrontendApiBundle\Model\Resolver\Products\DataMapper\ProductEntityFieldMapper:
        arguments:
            $productsSellableByIdsBatchLoader: '@products_sellable_by_ids_batch_loader'
            $productsVisibleByIdsBatchLoader: '@products_visible_by_ids_batch_loader'
            $productsVisibleCountByIdsBatchLoader: '@products_visible_count_by_ids_batch_loader'
            $productSlugBatchLoader: '@product_slug_batch_loader'

    Shopsys\FrontendApiBundle\Model\Resolver\Products\ParameterValueFilesQuery:
        arguments:
            $filesBatchLoader: '@first_file_batch_loader'

    Shopsys\FrontendApiBundle\Model\Resolver\Products\ProductFilesQuery:
        arguments:
            $filesBatchLoader: '@files_batch_loader'

    Shopsys\FrontendApiBundle\Model\Resolver\Products\ProductGiftsQuery:
        arguments:
            $productGiftsByMainProductIdsBatchLoader: '@product_gifts_by_main_product_ids_batch_loader'

    Shopsys\FrontendApiBundle\Model\Resolver\Products\ProductsQuery:
        arguments:
            $productsVisibleAndSortedByIdsBatchLoader: '@products_visible_and_sorted_by_ids_batch_loader'
            $productsByEntitiesBatchLoader: '@products_by_entities_batch_loader'

    Shopsys\FrontendApiBundle\Model\Resolver\Products\Search\ProductSearchResultsProvider:
        tags:
            - { name: 'shopsys.frontend_api.products_search_results_provider', priority: 1 }

    Shopsys\FrontendApiBundle\Model\Resolver\Products\Search\ProductSearchResultsProviderResolver:
        arguments:
            $productSearchResultsProviders: !tagged_iterator 'shopsys.frontend_api.products_search_results_provider'

    Shopsys\FrontendApiBundle\Model\Resolver\Store\StoreAvailabilityResolverMap:
        arguments:
            $storesBatchLoader: '@stores_batch_loader'
        tags:
            - { name: overblog_graphql.resolver_map, schema: default }

    Shopsys\FrontendApiBundle\Model\Resolver\Store\StoreResolverMap:
        arguments:
            $storeSlugBatchLoader: '@store_slug_batch_loader'
        tags:
            - { name: overblog_graphql.resolver_map, schema: default }

    Shopsys\FrontendApiBundle\Model\Resolver\Store\StoresQuery:
        arguments:
            $storesSearchRateLimiter: '@limiter.frontend_api_stores_search'

    Shopsys\FrontendApiBundle\Model\Security\RefreshTokenRedisCacheFacade:
        arguments:
            $redisClient: '@snc_redis.frontend_api_refresh_token'

    Shopsys\FrontendApiBundle\Model\SocialNetwork\SocialNetworkConfigFactory:
        arguments:
            $socialNetworkLoginConfig: '%social_network_login_config%'

    Shopsys\FrontendApiBundle\Model\SocialNetwork\SocialNetworkFacade:
        arguments:
            $logger: '@monolog.logger'

    Shopsys\FrontendApiBundle\Model\Store\StoreSearchTextCoordinatesProvider:
        arguments:
            $storeSearchCoordinatesCache: '@store_search_coordinates_cache'

    Shopsys\FrontendApiBundle\Model\Token\TokenAuthenticator: ~

    Shopsys\FrontendApiBundle\Model\User\FrontendApiUserProvider: ~

    Shopsys\FrontendApiBundle\Voter\:
        exclude: '../../Voter/Exception'
        resource: '../../Voter/'
        tags: [ 'security.voter' ]
