services:
    _defaults:
        autowire: true
        autoconfigure: true

    Shopsys\Cli\:
        resource: '../src/**/*{Handler}.php'

    Shopsys\Cli\Command\:
        resource: '../src/Command/*'
        public: true

    Shopsys\Cli\Worker\:
        resource: '../src/Worker/**/*Worker.php'
        tags: [ 'cli.worker' ]

    Shopsys\Cli\Worker\WorkerRunner:
        arguments:
            $taggedWorkers: !tagged_iterator 'cli.worker'
