services:
    _defaults:
        autoconfigure: true
        autowire: true
        public: false

    Shopsys\McpBundle\:
        resource: '../../**/*{Authenticator,DataFactory,Facade,Factory,Generator,Hasher,Lookup,Repository}.php'
