CartInterface:
    type: interface
    config:
        fields:
            uuid:
                type: "Uuid"
            items:
                type: "[CartItem!]!"
            transport:
                type: "Transport"
            payment:
                type: "Payment"
            selectedPickupPlaceIdentifier:
                type: "String"
            promoCode:
                type: "String"
            modifications:
                type: "CartModificationsResult!"
            totalPrice:
                type: "Price!"
            totalDiscountPrice:
                type: "Price!"
            remainingAmountWithVatForFreeTransport:
                type: "Money"
