Cart:
    type: object
    config:
        interfaces:
            - CartInterface
        fields:
            uuid:
                type: "Uuid"
                description: "UUID of the cart, null for authenticated user"
            items:
                type: "[CartItem!]!"
                description: "All items in the cart"
            transport:
                type: "Transport"
                description: "Selected transport if transport provided"
            payment:
                type: "Payment"
                description: "Selected payment if payment provided"
            promoCode:
                type: "String"
                description: "Applied promo code if provided"
            modifications:
                type: "CartModificationsResult!"
            totalPrice:
                type: "Price!"
            totalDiscountPrice:
                type: "Price!"
            remainingAmountWithVatForFreeTransport:
                type: "Money"
                description: "Remaining amount for free transport and payment; null = transport cannot be free"
