services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\Command\:
        resource: '../../src/Command'

    App\Command\ReplaceCdnDomainUrlCommand:
        arguments:
            $cdnDomainUrl: '%env(CDN_DOMAIN)%'
