const em = (value) => value / 16 + 'em';

/** @type {import('tailwindcss').Config} */
module.exports = {
    content: ['./pages/**/*.{js,ts,jsx,tsx}', './components/**/*.{js,ts,jsx,tsx}'],
    theme: {
        screens: {
            xxs: em(320),
            xs: em(375),
            sm: em(480),
            md: em(600),
            lg: em(769),
            vl: em(1024),
            xl: em(1240),
            xxl: em(1560),
        },
        colors: {
            text: '#25283D',
            textAccent: '#004EB6',
            textInverted: '#FFFFFF',
            textDisabled: '#727588',
            textSuccess: '#00CDBE',
            textSubtle: '#7892BC',
            textError: '#EC5353',

            link: '#004EB6',
            linkDisabled: '#7AA1D5',
            linkHovered: '#003479',
            linkInverted: '#FFFFFF',
            linkInvertedDisabled: '#727588',
            linkInvertedHovered: '#FFF0C4',

            borderLess: '#FAFAFA',
            borderAccent: '#7892BC',
            borderAccentLess: '#E0E0E0',
            borderAccentSuccess: '#20D3C6',
            borderAccentError: '#EC5353',

            background: '#FFFFFF',
            backgroundMore: '#FAFAFA',
            backgroundMost: '#ECECEC',
            backgroundBrand: '#004EB6',
            backgroundBrandLess: '#065FDB',
            backgroundAccent: '#009AFF',
            backgroundAccentLess: '#F4FAFF',
            backgroundAccentMore: '#008AE5',
            backgroundDark: '#25283D',
            backgroundError: '#EC5353',
            backgroundSuccess: '#20D3C6',
            backgroundSuccessMore: '#149F96',
            backgroundWarning: '#FCBD46',
            backgroundWarningMore: '#D58B00',

            price: '#004EB6',

            actionPrimaryText: '#FFFFFF',
            actionPrimaryTextActive: '#FFFFFF',
            actionPrimaryTextDisabled: '#7892BC',
            actionPrimaryTextHovered: '#FFFFFF',
            actionPrimaryBackground: '#00C8B7',
            actionPrimaryBackgroundActive: '#00BEB0',
            actionPrimaryBackgroundDisabled: '#CCF5F2',
            actionPrimaryBackgroundHovered: '#27E8DA',
            actionPrimaryBorder: '#00C8B7',
            actionPrimaryBorderActive: '#00BEB0',
            actionPrimaryBorderDisabled: '#CCF5F2',
            actionPrimaryBorderHovered: '#27E8DA',

            actionSecondaryText: '#FFFFFF',
            actionSecondaryTextActive: '#FFFFFF',
            actionSecondaryTextDisabled: '#FFFFFF',
            actionSecondaryTextHovered: '#FFFFFF',
            actionSecondaryBackground: '#004EB6',
            actionSecondaryBackgroundActive: '#00439C',
            actionSecondaryBackgroundDisabled: '#A1B5CF',
            actionSecondaryBackgroundHovered: '#4081D6',
            actionSecondaryBorder: '#004EB6',
            actionSecondaryBorderActive: '#00439C',
            actionSecondaryBorderDisabled: '#A1B5CF',
            actionSecondaryBorderHovered: '#4081D6',

            actionInvertedText: '#004EB6',
            actionInvertedTextActive: '#25283D',
            actionInvertedTextDisabled: '#A3ACBD',
            actionInvertedTextHovered: '#7892BC',
            actionInvertedBackground: 'transparent',
            actionInvertedBackgroundActive: '#FFFFFF',
            actionInvertedBackgroundDisabled: '#FAFAFA',
            actionInvertedBackgroundHovered: '#FFFFFF',
            actionInvertedBorder: '#004EB6',
            actionInvertedBorderActive: '#25283D',
            actionInvertedBorderDisabled: '#A3ACBD',
            actionInvertedBorderHovered: '#7892BC',

            actionTransparentText: '#FFFFFF',
            actionTransparentTextActive: '#FFFFFF',
            actionTransparentTextDisabled: '#FFFFFF66',
            actionTransparentTextHovered: '#FFFFFF',
            actionTransparentBackground: 'transparent',
            actionTransparentBackgroundActive: '#FFFFFF33',
            actionTransparentBackgroundDisabled: 'transparent',
            actionTransparentBackgroundHovered: '#FFFFFF66',
            actionTransparentBorder: '#FFFFFF',
            actionTransparentBorderActive: '#FFFFFF',
            actionTransparentBorderDisabled: '#FFFFFF66',
            actionTransparentBorderHovered: '#FFFFFF',

            activeIconFull: '#EC5353',

            availabilityInStock: '#00CDBE',
            availabilityOutOfStock: '#EC5353',

            openingStatusOpen: '#00CDBE',
            openingStatusClosed: '#EC5353',
            openingStatusOpenToday: '#FCBD46',

            inputText: '#25283D',
            inputTextActive: '#004EB6',
            inputTextDisabled: '#727588',
            inputTextHovered: '#25283D',
            inputTextInverted: '#FFFFFF',
            inputPlaceholder: '#7892BC',
            inputPlaceholderActive: '#3967B2',
            inputPlaceholderDisabled: '#AFBBCF',
            inputPlaceholderHovered: '#5C81BE',
            inputBackground: '#FFFFFF',
            inputBackgroundActive: '#004EB6',
            inputBackgroundDisabled: '#FFFFFF',
            inputBackgroundHovered: '#F4FAFF',
            inputBorder: '#7892BC',
            inputBorderActive: '#004EB6',
            inputBorderDisabled: '#AFBBCF',
            inputBorderHovered: '#004EB6',
            inputError: '#EC5353',

            tableBackground: '#FFFFFF',
            tableBackgroundContrast: '#FAFAFA',
            tableBackgroundHeader: '#3967B2',
            tableText: '#25283D',
            tableTextHeader: '#FFFFFF',
            tableCross: '#A3ACBD',
            tableCrossHover: '#7892BC',
            tableCrossHoverBg: '#FAFAFA',

            labelLinkText: '#FFFFFF',
            labelLinkTextActive: '#FFFFFF',
            labelLinkTextDisabled: '#E3E3E3',
            labelLinkTextHovered: '#FFFFFF',
            labelLinkBackground: '#7892BC',
            labelLinkBackgroundActive: '#3967B2',
            labelLinkBackgroundDisabled: '#AFBBCF',
            labelLinkBackgroundHovered: '#3967B2',
            labelLinkBorder: '#7892BC',
            labelLinkBorderActive: '#3967B2',
            labelLinkBorderDisabled: '#AFBBCF',
            labelLinkBorderHovered: '#3967B2',

            imageOverlay: 'rgba(201, 201, 201, 0.5)',
            overlay: 'rgba(37, 40, 61, 0.5)',
            transparent: 'transparent',
        },
        fontFamily: {
            default: ['var(--font-inter)'],
            secondary: ['var(--font-raleway)'],
        },
        zIndex: {
            hidden: -1000,
            base: 0,
            flag: 10, // due to cypress tests
            above: 11,
            menu: 1010,
            overlay: 1030,
            cart: 6000,
            aboveOverlay: 10001,
            maximum: 10100,
        },
        extend: {
            lineHeight: {
                DEFAULT: 1.3,
            },
            fontSize: {
                clamp: 'clamp(16px, 4vw, 22px)',
                zero: [0, 0],
            },
            borderRadius: {
                DEFAULT: '0.1875rem',
            },
            keyframes: {
                fadeIn: {
                    '0%': { opacity: 0.25 },
                    '100%': { opacity: 1 },
                },
            },
            animation: {
                fadeIn: 'fadeIn 0.2s ease-in-out',
            },
            spacing: {
                5.5: '1.375rem',
            },
            aspectRatio: {
                '16/11': '16 / 11',
            },
        },
        plugins: [],
    },
};
