#!/bin/sh
set -e

# this file is an extension of the original entry-point from the PHP Docker image
# https://github.com/docker-library/php/blob/master/docker-php-entrypoint

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
    set -- php-fpm "$@"
fi

exec "$@"
