query SearchQuery($search: String!, $orderingMode: ProductOrderingModeEnum, $after: String) {
    articlesSearch(search: $search) {
        ...ListedArticleFragment
    }
    brandSearch(search: $search) {
        ...ListedBrandFragment
    }
    categoriesSearch(search: $search) {
        totalCount
        edges {
            node {
                ...ListedCategoryFragment
            }
        }
    }
    productsSearch: products(search: $search, orderingMode: $orderingMode, after: $after) {
        totalCount
        edges {
            node {
                ...ListedProductFragment
            }
        }
    }
}
