query SearchQuery($search: String!, $orderingMode: ProductOrderingModeEnum, $after: String, $filter: ProductFilter) {
    articlesSearch(search: $search) {
        ...SimpleArticleInterfaceFragment
    }
    brandSearch(search: $search) {
        ...ListedBrandFragment
    }
    categoriesSearch(search: $search) {
        ...ListedCategoryConnectionFragment
    }
    productsSearch: products(search: $search, orderingMode: $orderingMode, after: $after, filter: $filter) {
       ...ListedProductConnectionFragment
    }
}
