LanguageConstantQuery:
    type: object
    config:
        fields:
            languageConstants:
                type: '[LanguageConstant!]!'
                resolve: "@=resolver('languageConstants')"
                description: "Return user translated language constants for current domain locale"
