CartPaymentModificationsResult:
    type: object
    config:
        fields:
            paymentPriceChanged:
                type: "Payment"
            paymentUnavailable:
                type: "Boolean!"
