CartTransportModificationsResult:
    type: object
    config:
        fields:
            transportPriceChanged:
                type: "Transport"
            transportUnavailable:
                type: "Boolean!"
            transportWeightLimitExceeded:
                type: "Boolean!"
