resources:
    - ../../namespace.yaml
    - ../../job/migration.yaml
namespace: "{{PROJECT_NAME}}"
configMapGenerator:
    -   name: domains-urls
        files:
            - ../../../config/domains_urls.yaml
    -   name: parameters
        files:
            - ../../../config/parameters.yaml
