Mutation:
    type: object
    inherits:
        - 'MutationDecorator'
        - 'CartMutation'
        - 'PromoCodeMutation'
        - 'CustomerUserMutation'
        - 'PersonalDataMutation'
        - 'CustomerMutation'
        - 'ContactFormMutation'
        - 'PaymentMutation'
        - 'TransportMutation'
