export enum GtmPageType {
    homepage = 'homepage',
    category_detail = 'category detail',
    seo_category_detail = 'seo category detail',
    product_detail = 'product detail',
    cart = 'cart',
    transport_and_payment = 'transport and payment',
    contact_information = 'contact information',
    order_confirmation = 'order confirmation',
    search_results = 'search results',
    blog_category_detail = 'blog category detail',
    blog_article_detail = 'blog article detail',
    stores = 'stores',
    store_detail = 'store detail',
    flag_detail = 'flag detail',
    brand_detail = 'brand detail',
    article_detail = 'article detail',
    payment_fail = 'payment fail',
    payment_success = 'payment success',
    not_found = '404',
    user_consent = 'user consent',
    contact = 'contact',
    product_comparison = 'product comparison',
    other = 'other',
}
