export enum GtmProductListNameType {
    blog_article_detail = 'blog article detail',
    brand_detail = 'brand detail',
    category_detail = 'category detail',
    seo_category_detail = 'seo category detail',
    flag_detail = 'flag detail',
    product_detail_accessories = 'product detail accessories',
    product_detail_variants_table = 'product detail variant table',
    search_results = 'search results',
    homepage_promo_products = 'homepage promo products',
    cart = 'cart',
    product_comparison_page = 'product comparison page',
    product_detail = 'product detail',
    product_detail_related_products = 'product detail related products',
    autocomplete_search_results = 'autocomplete_search_results',
    wishlist = 'wishlist',
    other = 'other',
    bestsellers = 'bestsellers',
    last_visited_products = 'last visited products',
}
