fragment ComplaintOrderedItemFragment on OrderItem {
    uuid
    name
    quantity
    unit
    totalPrice {
        priceWithVat
    }
    relatedItems {
        __typename
        uuid
        name
        catnum
        quantity
        unit
        type
        mainImage {
            ...ImageFragment
        }
        unitPrice {
            ...PriceFragment
        }
        totalPrice {
            ...PriceFragment
        }
    }
    order {
        uuid
        number
        creationDate
    }
    product {
        isVisible
        slug
        mainImage {
            ...ImageFragment
        }
    }
}
