fragment ComplaintItemFragment on ComplaintItem {
    uuid
    quantity
    description
    orderItem {
        __typename
        uuid
        unit
        totalPrice {
            priceWithVat
        }
        relatedItems {
            ...OrderItemAdditionalServiceFragment
            deliveryDaysExtension
        }
    }
    files {
        ...FileFragment
    }
    product {
        fullName
        mainCategory {
            name
        }
        mainImage {
            ...ImageFragment
        }
        slug
        isVisible
    }
    catnum
    productName
}
