snc_redis:
    clients:
        apply_code_to_cart_rate_limiter:
            type: 'phpredis'
            alias: 'apply_code_to_cart_rate_limiter'
            dsn: 'redis://%env(REDIS_HOST)%'
            logging: false
            options:
                prefix: '%env(REDIS_PREFIX)%:%build-version%:rate_limiter:apply_code_to_cart:'
                connection_timeout: 2
                read_write_timeout: 5
        bestselling_products:
            type: 'phpredis'
            alias: 'bestselling_products'
            dsn: 'redis://%env(REDIS_HOST)%'
            logging: false
            options:
                prefix: '%env(REDIS_PREFIX)%:%build-version%:cache:bestselling_products:'
                connection_timeout: 2
                read_write_timeout: 5
        blog_article_export_queue:
            type: 'phpredis'
            alias: 'blog_article_export_queue'
            dsn: 'redis://%env(REDIS_HOST)%'
            logging: false
            options:
                serialization: 'json'
                prefix: '%env(REDIS_PREFIX)%:queue:blog_article_export:'
                connection_timeout: 2
                read_write_timeout: 5
        doctrine_query:
            type: 'phpredis'
            alias: 'doctrine_query'
            dsn: 'redis://%env(REDIS_HOST)%'
            logging: false
            options:
                prefix: '%env(REDIS_PREFIX)%:%build-version%:cache:doctrine:query:'
                connection_timeout: 2
                read_write_timeout: 5
        frontend_api_refresh_token:
            type: 'phpredis'
            alias: 'frontend_api_refresh_token'
            dsn: 'redis://%env(REDIS_HOST)%'
            logging: false
            options:
                prefix: '%env(REDIS_PREFIX)%:frontend_api_refresh_token:'
                connection_timeout: 2
                read_write_timeout: 5
        # client is used exclusively for cleaning old versions of redis caches and should not be used for anything else
        global:
            type: 'phpredis'
            alias: 'global'
            dsn: 'redis://%env(REDIS_HOST)%'
            logging: false
            options:
                prefix: '%env(REDIS_PREFIX)%:'
                connection_timeout: 2
                read_write_timeout: 5
        image:
            type: 'phpredis'
            alias: 'image'
            dsn: 'redis://%env(REDIS_HOST)%'
            logging: false
            options:
                prefix: '%env(REDIS_PREFIX)%:%build-version%:cache:image:'
                connection_timeout: 2
                read_write_timeout: 5
        main_friendly_url_slugs:
            type: 'phpredis'
            alias: 'main_friendly_url_slugs'
            dsn: 'redis://%env(REDIS_HOST)%'
            logging: false
            options:
                prefix: '%env(REDIS_PREFIX)%:%build-version%:cache:main_friendly_url_slugs:'
                connection_timeout: 2
                read_write_timeout: 5
        mcp_http_session:
            type: 'phpredis'
            alias: 'mcp_http_session'
            dsn: 'redis://%env(REDIS_HOST)%'
            logging: false
            options:
                prefix: '%env(REDIS_PREFIX)%:%build-version%:cache:mcp_http_session:'
                connection_timeout: 2
                read_write_timeout: 5
        mcp_oauth:
            type: 'phpredis'
            alias: 'mcp_oauth'
            dsn: 'redis://%env(REDIS_HOST)%'
            logging: false
            options:
                prefix: '%env(REDIS_PREFIX)%:mcp_oauth:'
                connection_timeout: 2
                read_write_timeout: 5
        mcp_rate_limiter:
            type: 'phpredis'
            alias: 'mcp_rate_limiter'
            dsn: 'redis://%env(REDIS_HOST)%'
            logging: false
            options:
                prefix: '%env(REDIS_PREFIX)%:%build-version%:rate_limiter:mcp:'
                connection_timeout: 2
                read_write_timeout: 5
        product_recalculation_queue:
            type: 'phpredis'
            alias: 'product_recalculation_queue'
            dsn: 'redis://%env(REDIS_HOST)%'
            logging: false
            options:
                prefix: '%env(REDIS_PREFIX)%:queue:recalculation:'
                connection_timeout: 2
                read_write_timeout: 5
        store_search_coordinates:
            type: 'phpredis'
            alias: 'store_search_coordinates'
            dsn: 'redis://%env(REDIS_HOST)%'
            logging: false
            options:
                prefix: '%env(REDIS_PREFIX)%:%build-version%:cache:store_search_coordinates:'
                connection_timeout: 2
                read_write_timeout: 5
        storefront_graphql_query:
            type: 'phpredis'
            alias: 'storefront_graphql_query'
            dsn: 'redis://%env(REDIS_HOST)%'
            logging: false
            options:
                prefix: '%env(REDIS_PREFIX)%:fe:'
                connection_timeout: 2
                read_write_timeout: 5
