ux_icons:
    aliases:
        arrow: 'tabler:caret-down-filled'
        arrow-back: 'tabler:arrow-back'
        arrow-down: 'tabler:arrow-big-down-filled'
        arrow-left: 'tabler:arrow-big-left-filled'
        arrow-right: 'tabler:arrow-big-right-filled'
        arrow-simple: 'tabler:arrow-right'
        arrow-strong: 'tabler:chevron-right'
        arrow-thin: 'tabler:chevron-compact-right'
        arrow-up: 'tabler:arrow-big-up-filled'
        brand-elastic: 'tabler:brand-elastic'
        calendar-3: 'tabler:calendar-week'
        cart: 'tabler:basket-filled'
        cart-off: 'tabler:basket-off'
        chart-piece: 'tabler:clipboard-data-filled'
        checked: 'tabler:check'
        checked-circle: 'tabler:circle-check'
        chevron-down: 'tabler:chevron-down'
        chevron-left: 'tabler:chevron-left'
        chevron-right: 'tabler:chevron-right'
        chevron-up: 'tabler:chevron-up'
        circle-cross: 'tabler:xbox-x-filled'
        circle-plus: 'tabler:circle-plus'
        circle-remove: 'tabler:circle-minus'
        company: 'tabler:building'
        crown: 'tabler:crown'
        delete: 'tabler:x'
        delete-thin: 'tabler:x'
        document-copy: 'tabler:clipboard-text-filled'
        dots: 'tabler:dots'
        double-arrow: 'tabler:chevrons-left'
        download: 'tabler:download'
        drag-handle: 'tabler:grip-vertical'
        duplicate: 'tabler:copy'
        exclamation-circle: 'tabler:exclamation-circle'
        file-all: 'tabler:file-text'
        file-excel: 'tabler:file-type-xls'
        file-image: 'tabler:photo'
        file-not-found: 'tabler:file-sad'
        file-pdf: 'tabler:file-type-pdf'
        file-word: 'tabler:file-type-doc'
        file-xml: 'tabler:file-type-xml'
        filter: 'tabler:filter-filled'
        flag: 'tabler:flag-3-filled'
        folder: 'tabler:folder-filled'
        forward-page: 'tabler:external-link'
        gear: 'tabler:settings-filled'
        house: 'tabler:home-filled'
        house-outline: 'tabler:home'
        id: 'tabler:id'
        info: 'tabler:info-circle-filled'
        info-outlined: 'tabler:info-circle'
        invisible: 'tabler:eye-off'
        letter: 'tabler:mail-filled'
        letter-outline: 'tabler:mail'
        light-bulb: 'tabler:bulb-filled'
        list-search: 'tabler:list-search'
        lock: 'tabler:lock'
        logout: 'tabler:logout'
        menu: 'tabler:menu-2'
        minus: 'tabler:minus'
        mood-confused: 'tabler:mood-confuzed'
        move: 'tabler:arrows-move'
        note: 'tabler:message-circle'
        notes-off: 'tabler:notes-off'
        pencil: 'tabler:edit'
        person-door-man: 'tabler:user-square'
        person-man: 'tabler:user'
        person-public: 'tabler:users'
        phone: 'tabler:phone'
        pin: 'tabler:pin'
        pinned: 'tabler:pinned-filled'
        plus: 'tabler:plus'
        power: 'tabler:power'
        print: 'tabler:printer'
        puzzle: 'tabler:puzzle-filled'
        question: 'tabler:question-mark'
        radius-bottom-left: 'tabler:radius-bottom-left'
        receipt-tax: 'tabler:receipt-tax'
        refund: 'tabler:credit-card-refund'
        revert: 'tabler:arrow-back-up'
        schedule: 'tabler:clock-filled'
        search: 'tabler:search'
        select-all: 'tabler:select-all'
        square-off: 'tabler:square-off'
        support: 'tabler:headset'
        tag: 'tabler:tag-filled'
        toc: 'tabler:menu-4'
        trash: 'tabler:trash-x-filled'
        trending-down: 'tabler:trending-down'
        trending-up: 'tabler:trending-up'
        unselect-all: 'tabler:deselect'
        upload: 'tabler:upload'
        user: 'tabler:user-circle'
        user-settings: 'tabler:user-cog'
        visible: 'tabler:eye'
        warning: 'tabler:alert-triangle'
    default_icon_attributes:
        class: icon
        fill: currentColor
        height: 20
        width: 20
