#!/bin/bash
set -e

tries_before_fail=100
messages_to_consume_count=${CONSUMER_RUNS_BEFORE_RESTART:-1000}

consumer_name=$1

if [[ -z ${consumer_name} ]]; then
    1>&2 echo "First argument had to be name of consumer to start"
    exit 1
fi

for ((i = 0; i < $[tries_before_fail]; i++)); do
    php bin/console shopsys:rabbitmq:check-availability >/dev/null 2>&1 && break
    1>&2 echo "Application is not yet ready - consumer sleeping"
    sleep 5
done

if [[ ${i} = ${tries_before_fail} ]]; then
    1>&2 echo "Number of maximum retries reached - failing"
    exit 1
fi

ENVIRONMENT="$(php bin/console about | grep Environment | sed 's/Environment//;s/ //g')"

# consumer in development and test enviroment processes only one message and then is started again so it loads new codebase every time
if [[ ${ENVIRONMENT} = prod ]]; then
    php bin/console rabbitmq:consumer -m ${messages_to_consume_count} ${consumer_name}
else
    for ((i = 0; i < $[messages_to_consume_count]; i++)); do
        php bin/console rabbitmq:consumer -m 1 ${consumer_name}
    done
fi
