CustomerMutation:
    type: object
    config:
        fields:
            DeleteDeliveryAddress:
                type: "[DeliveryAddress!]!"
                description: "Delete delivery address by Uuid"
                args:
                    deliveryAddressUuid:
                        type: Uuid!
                resolve: "@=mutation('deleteDeliveryAddress', [args])"
            EditDeliveryAddress:
                type: "[DeliveryAddress!]!"
                description: "Edit delivery address by Uuid"
                args:
                    input:
                        type: DeliveryAddressInput!
                        validation: cascade
                resolve: "@=mutation('editDeliveryAddress', [args])"
            SetDefaultDeliveryAddress:
                type: "CustomerUser!"
                description: "Set default delivery address by Uuid"
                args:
                    deliveryAddressUuid:
                        type: Uuid!
                        description: "Set delivery address by Uuid"
                resolve: "@=mutation('setDefaultDeliveryAddress', [args['deliveryAddressUuid']])"
