MainBlogCategoryDataDecorator:
    type: object
    decorator: true
    config:
        fields:
            mainBlogCategoryName:
                type: String
                description: "Name of the blog main category"
            mainBlogCategoryUrl:
                type: String
                description: "Absolute URL of the blog main category"
            mainBlogCategoryMainImage:
                type: "Image"
                description: "Main image of the blog main category"
