<?php

declare(strict_types=1);

namespace Shopsys\FrameworkBundle\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Override;
use Shopsys\MigrationBundle\Component\Doctrine\Migrations\AbstractMigration;

final class Version20260624080453 extends AbstractMigration
{
    #[Override]
    public function up(Schema $schema): void
    {
        $this->sql('
            CREATE TABLE blog_article_authors (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                uuid UUID NOT NULL,
                name VARCHAR(255) NOT NULL,
                PRIMARY KEY (id)
            )');
        $this->sql('CREATE UNIQUE INDEX UNIQ_D1271265D17F50A6 ON blog_article_authors (uuid)');
        $this->sql('
            CREATE TABLE blog_article_author_translations (
                job_title VARCHAR(255) DEFAULT NULL,
                description TEXT DEFAULT NULL,
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                locale VARCHAR(255) NOT NULL,
                translatable_id INT NOT NULL,
                PRIMARY KEY (id)
            )');
        $this->sql('CREATE INDEX IDX_7E503482C2AC5D3 ON blog_article_author_translations (translatable_id)');
        $this->sql('
            CREATE UNIQUE INDEX blog_article_author_translations_uniq_trans ON blog_article_author_translations (translatable_id, locale)');
        $this->sql('
            ALTER TABLE
                blog_article_author_translations
            ADD
                CONSTRAINT FK_7E503482C2AC5D3 FOREIGN KEY (translatable_id) REFERENCES blog_article_authors (id) ON DELETE CASCADE');
        $this->sql('ALTER TABLE blog_articles ADD blog_article_author_id INT DEFAULT NULL');
        $this->sql('
            ALTER TABLE
                blog_articles
            ADD
                CONSTRAINT FK_CB80154F655DE759 FOREIGN KEY (blog_article_author_id) REFERENCES blog_article_authors (id) ON DELETE
            SET
                NULL NOT DEFERRABLE');
        $this->sql('CREATE INDEX IDX_CB80154F655DE759 ON blog_articles (blog_article_author_id)');
    }
}
