<?php

declare(strict_types=1);

namespace Shopsys\FrameworkBundle\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Override;
use Shopsys\MigrationBundle\Component\Doctrine\Migrations\AbstractMigration;

final class Version20261009213142 extends AbstractMigration
{
    #[Override]
    public function up(Schema $schema): void
    {
        $this->sql('ALTER TABLE payment_prices DROP CONSTRAINT payment_prices_pkey');
        $this->sql('ALTER TABLE payment_prices ADD id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL');
        $this->sql('ALTER TABLE payment_prices ADD PRIMARY KEY (id)');
        $this->sql('CREATE UNIQUE INDEX unique_payment_price_on_domain ON payment_prices (payment_id, domain_id)');
    }
}
