<?php

declare(strict_types=1);

namespace Shopsys\FrameworkBundle\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Override;
use Shopsys\MigrationBundle\Component\Doctrine\Migrations\AbstractMigration;

final class Version20260722103707 extends AbstractMigration
{
    #[Override]
    public function up(Schema $schema): void
    {
        $this->sql('
            CREATE TABLE additional_services (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                uuid UUID NOT NULL,
                catnum VARCHAR(100) NOT NULL,
                zbozi_service_type VARCHAR(50) DEFAULT NULL,
                delivery_days_extension INT NOT NULL,
                position INT NOT NULL,
                PRIMARY KEY (id)
            )');
        $this->sql('CREATE UNIQUE INDEX UNIQ_C9E35DBFD17F50A6 ON additional_services (uuid)');
        $this->sql('CREATE UNIQUE INDEX UNIQ_C9E35DBF5CAFC31D ON additional_services (catnum)');
        $this->sql('
            CREATE TABLE additional_service_domains (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                domain_id INT NOT NULL,
                enabled BOOLEAN NOT NULL,
                show_in_feeds BOOLEAN NOT NULL,
                use_product_vat_rate BOOLEAN NOT NULL,
                price NUMERIC(20, 6) NOT NULL,
                additional_service_id INT NOT NULL,
                vat_id INT DEFAULT NULL,
                PRIMARY KEY (id)
            )');
        $this->sql('CREATE INDEX IDX_20BEF067F8E98E09 ON additional_service_domains (additional_service_id)');
        $this->sql('CREATE INDEX IDX_20BEF067B5B63A6B ON additional_service_domains (vat_id)');
        $this->sql('
            CREATE UNIQUE INDEX additional_service_domain ON additional_service_domains (
                additional_service_id, domain_id
            )');
        $this->sql('
            CREATE TABLE additional_service_translations (
                name VARCHAR(255) DEFAULT NULL,
                feed_name VARCHAR(128) DEFAULT NULL,
                zbozi_description VARCHAR(160) DEFAULT NULL,
                description TEXT DEFAULT NULL,
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                locale VARCHAR(255) NOT NULL,
                translatable_id INT NOT NULL,
                PRIMARY KEY (id)
            )');
        $this->sql('CREATE INDEX IDX_92927D5E2C2AC5D3 ON additional_service_translations (translatable_id)');
        $this->sql('
            CREATE UNIQUE INDEX additional_service_translations_uniq_trans ON additional_service_translations (translatable_id, locale)');
        $this->sql('
            ALTER TABLE
                additional_service_domains
            ADD
                CONSTRAINT FK_20BEF067F8E98E09 FOREIGN KEY (additional_service_id) REFERENCES additional_services (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->sql('
            ALTER TABLE
                additional_service_domains
            ADD
                CONSTRAINT FK_20BEF067B5B63A6B FOREIGN KEY (vat_id) REFERENCES vats (id) NOT DEFERRABLE');
        $this->sql('
            ALTER TABLE
                additional_service_translations
            ADD
                CONSTRAINT FK_92927D5E2C2AC5D3 FOREIGN KEY (translatable_id) REFERENCES additional_services (id) ON DELETE CASCADE');
    }
}
