<?php

declare(strict_types=1);

namespace Shopsys\FrameworkBundle\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Override;
use Shopsys\MigrationBundle\Component\Doctrine\Migrations\AbstractMigration;

final class Version20260816122444 extends AbstractMigration
{
    #[Override]
    public function up(Schema $schema): void
    {
        $this->sql('
            CREATE TABLE product_review_images (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                product_review_id INT NOT NULL,
                position INT NOT NULL,
                rejection_reason TEXT DEFAULT NULL,
                PRIMARY KEY (id)
            )');

        $this->sql('CREATE INDEX IDX_B084E558508E2016 ON product_review_images (product_review_id)');

        $this->sql('ALTER TABLE product_review_images ADD CONSTRAINT FK_B084E558508E2016 FOREIGN KEY (product_review_id) REFERENCES product_reviews (id) NOT DEFERRABLE');
    }
}
