<?php

declare(strict_types=1);

namespace Shopsys\FrameworkBundle\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Override;
use Shopsys\MigrationBundle\Component\Doctrine\Migrations\AbstractMigration;

final class Version20260710065853 extends AbstractMigration
{
    #[Override]
    public function up(Schema $schema): void
    {
        $this->sql('
            CREATE TABLE gift_vouchers (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                uuid UUID NOT NULL,
                code VARCHAR(20) NOT NULL,
                domain_id INT NOT NULL,
                value_with_vat NUMERIC(20, 6) NOT NULL,
                currency_code VARCHAR(3) NOT NULL,
                vat_percent NUMERIC(20, 6) NOT NULL,
                status VARCHAR(20) NOT NULL,
                activated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                valid_until TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                product_catnum VARCHAR(255) DEFAULT NULL,
                product_name VARCHAR(255) DEFAULT NULL,
                customer_email VARCHAR(255) DEFAULT NULL,
                redeemed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
                email_enqueued_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
                email_sent_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
                created_on_order_id INT DEFAULT NULL,
                redeemed_on_order_id INT DEFAULT NULL,
                PRIMARY KEY (id)
            )');
        $this->sql('CREATE UNIQUE INDEX UNIQ_D510E302D17F50A6 ON gift_vouchers (uuid)');
        $this->sql('CREATE UNIQUE INDEX UNIQ_D510E30277153098 ON gift_vouchers (code)');
        $this->sql('CREATE INDEX IDX_D510E30283A3CC50 ON gift_vouchers (created_on_order_id)');
        $this->sql('CREATE INDEX IDX_D510E3028509C2F ON gift_vouchers (redeemed_on_order_id)');
        $this->sql('
            ALTER TABLE
                gift_vouchers
            ADD
                CONSTRAINT FK_D510E30283A3CC50 FOREIGN KEY (created_on_order_id) REFERENCES orders (id) ON DELETE
            SET
                NULL NOT DEFERRABLE');
        $this->sql('
            ALTER TABLE
                gift_vouchers
            ADD
                CONSTRAINT FK_D510E3028509C2F FOREIGN KEY (redeemed_on_order_id) REFERENCES orders (id) ON DELETE
            SET
                NULL NOT DEFERRABLE');
        $this->sql('CREATE INDEX promo_codes_lower_code_idx ON promo_codes (LOWER(code))');
    }
}
