<?php

declare(strict_types=1);

namespace Shopsys\FrameworkBundle\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Override;
use Shopsys\MigrationBundle\Component\Doctrine\Migrations\AbstractMigration;

class Version20260302120000 extends AbstractMigration
{
    #[Override]
    public function up(Schema $schema): void
    {
        $this->convertSequencesToIdentityColumns();
        $this->removeDoctrineTypeComments();
    }

    // DBAL 4 uses identity columns instead of standalone sequences.
    // Convert all nextval()-based columns to GENERATED BY DEFAULT AS IDENTITY,
    // restart the identity at MAX(id) + 1, and drop the old sequence.
    private function convertSequencesToIdentityColumns(): void
    {
        $columns = $this->sqlQuery(
            "SELECT c.table_name, c.column_name,
                    pg_get_serial_sequence(c.table_schema || '.' || c.table_name, c.column_name) AS seq_name
             FROM information_schema.columns c
             WHERE c.table_schema = 'public'
               AND c.column_default LIKE 'nextval(%'",
        )->fetchAllAssociative();

        foreach ($columns as $column) {
            $table = $this->connection->quoteSingleIdentifier($column['table_name']);
            $col = $this->connection->quoteSingleIdentifier($column['column_name']);

            $this->sql(sprintf('ALTER TABLE %s ALTER COLUMN %s DROP DEFAULT', $table, $col));
            $this->sql(sprintf('ALTER TABLE %s ALTER COLUMN %s ADD GENERATED BY DEFAULT AS IDENTITY', $table, $col));

            $maxVal = (int)$this->sqlQuery(sprintf('SELECT COALESCE(MAX(%s), 0) FROM %s', $col, $table))->fetchOne();

            if ($maxVal > 0) {
                $this->sql(sprintf('ALTER TABLE %s ALTER COLUMN %s RESTART WITH %d', $table, $col, $maxVal + 1));
            }

            if ($column['seq_name'] !== null) {
                $this->sql(sprintf('DROP SEQUENCE IF EXISTS %s', $column['seq_name']));
            }
        }
    }

    // DBAL 4 no longer stores type metadata in SQL column comments (requiresSQLCommentHint() was removed).
    // Remove all leftover "(DC2Type:...)" comments so they don't cause schema diff noise.
    private function removeDoctrineTypeComments(): void
    {
        $columns = $this->sqlQuery(
            "SELECT c.relname AS table_name, a.attname AS column_name
             FROM pg_description d
             JOIN pg_class c ON c.oid = d.objoid
             JOIN pg_attribute a ON a.attrelid = c.oid AND a.attnum = d.objsubid
             JOIN pg_namespace n ON n.oid = c.relnamespace
             WHERE n.nspname = 'public'
               AND d.objsubid > 0
               AND d.description LIKE '(DC2Type:%)'",
        )->fetchAllAssociative();

        foreach ($columns as $column) {
            $table = $this->connection->quoteSingleIdentifier($column['table_name']);
            $col = $this->connection->quoteSingleIdentifier($column['column_name']);

            $this->sql(sprintf('COMMENT ON COLUMN %s.%s IS NULL', $table, $col));
        }
    }
}
