<?php

declare(strict_types=1);

namespace Shopsys\FrameworkBundle\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Override;
use Shopsys\MigrationBundle\Component\Doctrine\Migrations\AbstractMigration;

final class Version20260904130000 extends AbstractMigration implements DomainAwareInterface
{
    use MultidomainMigrationTrait;

    #[Override]
    public function up(Schema $schema): void
    {
        $this->sql('
            CREATE TABLE flag_domains (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                flag_id INT NOT NULL,
                domain_id INT NOT NULL,
                seo_title TEXT DEFAULT NULL,
                seo_meta_description TEXT DEFAULT NULL,
                seo_h1 TEXT DEFAULT NULL,
                seo_meta_robots VARCHAR(30) DEFAULT NULL,
                seo_canonical_url TEXT DEFAULT NULL,
                PRIMARY KEY(id)
            )');
        $this->sql('CREATE INDEX IDX_7D4209D2919FE4E5 ON flag_domains (flag_id)');
        $this->sql('CREATE UNIQUE INDEX flag_domain ON flag_domains (flag_id, domain_id)');
        $this->sql('
            ALTER TABLE
                flag_domains
            ADD
                CONSTRAINT FK_7D4209D2919FE4E5 FOREIGN KEY (flag_id) REFERENCES flags (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');

        foreach ($this->getAllDomainIds() as $domainId) {
            $this->sql(
                'INSERT INTO flag_domains (flag_id, domain_id) SELECT id, :domainId FROM flags',
                ['domainId' => $domainId],
            );
        }
    }
}
