<?php

declare(strict_types=1);

namespace Shopsys\FrameworkBundle\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Override;
use Shopsys\MigrationBundle\Component\Doctrine\Migrations\AbstractMigration;

final class Version20260728123217 extends AbstractMigration
{
    #[Override]
    public function up(Schema $schema): void
    {
        $this->sql('
            CREATE TABLE product_reviews (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                uuid UUID NOT NULL,
                domain_id INT NOT NULL,
                catnum VARCHAR(100) NOT NULL,
                product_name VARCHAR(255) NOT NULL,
                first_name VARCHAR(100) NOT NULL,
                last_name VARCHAR(100) NOT NULL,
                email VARCHAR(255) NOT NULL,
                is_anonymous BOOLEAN NOT NULL,
                rating SMALLINT NOT NULL,
                text TEXT DEFAULT NULL,
                ip_address VARCHAR(45) NOT NULL,
                is_verified_purchase BOOLEAN NOT NULL,
                status VARCHAR(20) NOT NULL,
                rejection_reason TEXT DEFAULT NULL,
                created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                response_text TEXT DEFAULT NULL,
                response_created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
                product_id INT DEFAULT NULL,
                order_item_id INT DEFAULT NULL,
                customer_user_id INT DEFAULT NULL,
                PRIMARY KEY (id)
            )');

        $this->sql('CREATE INDEX IDX_B8A9F0BF4584665A ON product_reviews (product_id)');
        $this->sql('CREATE INDEX IDX_B8A9F0BFE415FB15 ON product_reviews (order_item_id)');
        $this->sql('CREATE INDEX IDX_B8A9F0BFBBB3772B ON product_reviews (customer_user_id)');
        $this->sql('CREATE UNIQUE INDEX UNIQ_B8A9F0BFD17F50A6 ON product_reviews (uuid)');
        $this->sql('ALTER TABLE product_reviews ADD CONSTRAINT UNIQ_B8A9F0BFBBB3772B4584665A115F0EE5 UNIQUE (customer_user_id, product_id, domain_id)');

        $this->sql('CREATE INDEX IDX_B8A9F0BF115F0EE57B00651C ON product_reviews (domain_id, status)');
        $this->sql('CREATE INDEX IDX_B8A9F0BF4584665A115F0EE57B00651C ON product_reviews (product_id, domain_id, status)');

        $this->sql('ALTER TABLE product_reviews ADD CONSTRAINT FK_B8A9F0BF4584665A FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->sql('ALTER TABLE product_reviews ADD CONSTRAINT FK_B8A9F0BFE415FB15 FOREIGN KEY (order_item_id) REFERENCES order_items (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->sql('ALTER TABLE product_reviews ADD CONSTRAINT FK_B8A9F0BFBBB3772B FOREIGN KEY (customer_user_id) REFERENCES customer_users (id) ON DELETE SET NULL NOT DEFERRABLE');
    }
}
