<?php

declare(strict_types=1);

namespace Shopsys\FrameworkBundle\Migrations;

use Doctrine\DBAL\Schema\Schema;
use InvalidArgumentException;
use Override;
use Ramsey\Uuid\Uuid;
use Shopsys\MigrationBundle\Component\Doctrine\Migrations\AbstractMigration;

final class Version20260617120000 extends AbstractMigration implements DomainAwareInterface
{
    use MultidomainMigrationTrait;

    #[Override]
    public function up(Schema $schema): void
    {
        $this->sql('
            CREATE TABLE transport_groups (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                uuid UUID NOT NULL,
                position INT NOT NULL,
                PRIMARY KEY(id)
            )');
        $this->sql('CREATE UNIQUE INDEX UNIQ_43964CF9D17F50A6 ON transport_groups (uuid)');
        $this->sql('
            CREATE TABLE transport_groups_translations (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                translatable_id INT NOT NULL,
                name VARCHAR(255) NOT NULL,
                locale VARCHAR(255) NOT NULL,
                PRIMARY KEY(id)
            )');
        $this->sql('CREATE INDEX IDX_70A196902C2AC5D3 ON transport_groups_translations (translatable_id)');
        $this->sql('CREATE UNIQUE INDEX transport_groups_translations_uniq_trans ON transport_groups_translations (translatable_id, locale)');
        $this->sql('
            ALTER TABLE
                transport_groups_translations
            ADD
                CONSTRAINT FK_B0C9E9CA2C2AC5D3 FOREIGN KEY (translatable_id) REFERENCES transport_groups (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->sql('ALTER TABLE transports ADD transport_group_id INT DEFAULT NULL');
        $this->sql('CREATE INDEX IDX_C7BE69E5347ACC0D ON transports (transport_group_id)');
        $this->sql('
            ALTER TABLE
                transports
            ADD
                CONSTRAINT FK_22955E1754187AF3 FOREIGN KEY (transport_group_id) REFERENCES transport_groups (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->createDefaultTransportGroup(0, 'delivery_to_address');
        $this->createDefaultTransportGroup(1, 'pickup_point');
    }

    private function createDefaultTransportGroup(int $position, string $key): void
    {
        $this->sql('INSERT INTO transport_groups (uuid, position) VALUES (:uuid, :position)', [
            'uuid' => Uuid::uuid4()->toString(),
            'position' => $position,
        ]);
        $transportGroupId = $this->connection->lastInsertId();

        foreach ($this->getAllLocales() as $locale) {
            $this->sql(
                'INSERT INTO transport_groups_translations (translatable_id, name, locale) VALUES (:transportGroupId, :name, :locale)',
                [
                    'transportGroupId' => $transportGroupId,
                    'name' => $this->getDefaultTransportGroupName($key, $locale),
                    'locale' => $locale,
                ],
            );
        }
    }

    private function getDefaultTransportGroupName(string $key, string $locale): string
    {
        return match ($key) {
            'delivery_to_address' => t('Delivery to address', locale: $locale),
            'pickup_point' => t('Pickup point', locale: $locale),
            default => throw new InvalidArgumentException(sprintf('Unknown transport group key "%s".', $key)),
        };
    }
}
