<?php

declare(strict_types=1);

namespace Shopsys\FrameworkBundle\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Override;
use Shopsys\MigrationBundle\Component\Doctrine\Migrations\AbstractMigration;

final class Version20260312111807 extends AbstractMigration
{
    #[Override]
    public function up(Schema $schema): void
    {
        $this->createPhonePrefixesTable();

        $this->updateOrdersTable();
        $this->updateDeliveryAddressesTable();
        $this->updateCustomerUsersTable();
    }

    private function createPhonePrefixesTable(): void
    {
        $this->sql('CREATE TABLE phone_prefixes (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            domain_id INT NOT NULL,
            code VARCHAR(2) NOT NULL,
            is_default BOOLEAN NOT NULL,
            PRIMARY KEY(id)
        )');

        $this->sql('CREATE UNIQUE INDEX phone_prefixes_domain_code ON phone_prefixes (domain_id, code)');
        $this->sql('CREATE UNIQUE INDEX phone_prefixes_domain_default ON phone_prefixes (domain_id) WHERE is_default = true');
    }

    private function updateOrdersTable(): void
    {
        $this->sql('ALTER TABLE orders RENAME COLUMN telephone TO telephone_number');
        $this->sql('ALTER TABLE orders ADD telephone_prefix VARCHAR(10) DEFAULT NULL');
        $this->sql('ALTER TABLE orders ADD telephone_prefix_country_code VARCHAR(2) DEFAULT NULL');

        $this->sql('ALTER TABLE orders RENAME COLUMN delivery_telephone TO delivery_telephone_number');
        $this->sql('ALTER TABLE orders ADD delivery_telephone_prefix VARCHAR(10) DEFAULT NULL');
        $this->sql('ALTER TABLE orders ADD delivery_telephone_prefix_country_code VARCHAR(2) DEFAULT NULL');

        $this->sql('CREATE INDEX orders_telephone_trgm_idx ON orders USING gin (normalized(COALESCE(telephone_prefix, \'\')::text || COALESCE(telephone_number, \'\')::text) gin_trgm_ops)');
    }

    private function updateDeliveryAddressesTable(): void
    {
        $this->sql('ALTER TABLE delivery_addresses RENAME COLUMN telephone TO telephone_number');
        $this->sql('ALTER TABLE delivery_addresses ADD telephone_prefix VARCHAR(10) DEFAULT NULL');
        $this->sql('ALTER TABLE delivery_addresses ADD telephone_prefix_country_code VARCHAR(2) DEFAULT NULL');
    }

    private function updateCustomerUsersTable(): void
    {
        $this->sql('ALTER TABLE customer_users RENAME COLUMN telephone TO telephone_number');
        $this->sql('ALTER TABLE customer_users ADD telephone_prefix VARCHAR(10) DEFAULT NULL');
        $this->sql('ALTER TABLE customer_users ADD telephone_prefix_country_code VARCHAR(2) DEFAULT NULL');

        $this->sql('DROP INDEX IF EXISTS customer_users_telephone_trgm_idx');
        $this->sql('CREATE INDEX customer_users_telephone_trgm_idx ON customer_users USING gin (normalized(COALESCE(telephone_prefix, \'\')::text || COALESCE(telephone_number, \'\')::text) gin_trgm_ops)');
    }
}
