<?php

declare(strict_types=1);

namespace Shopsys\FrameworkBundle\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Override;
use Shopsys\MigrationBundle\Component\Doctrine\Migrations\AbstractMigration;

class Version20260312111807 extends AbstractMigration
{
    #[Override]
    public function up(Schema $schema): void
    {
        $this->createPhonePrefixesTable();
    }

    private function createPhonePrefixesTable(): void
    {
        $this->sql('CREATE TABLE phone_prefixes (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            domain_id INT NOT NULL,
            code VARCHAR(2) NOT NULL,
            is_default BOOLEAN NOT NULL,
            PRIMARY KEY(id)
        )');

        $this->sql('CREATE UNIQUE INDEX phone_prefixes_domain_code ON phone_prefixes (domain_id, code)');
        $this->sql('CREATE UNIQUE INDEX phone_prefixes_domain_default ON phone_prefixes (domain_id) WHERE is_default = true');
    }
}
