<?php

declare(strict_types=1);

namespace Shopsys\FrameworkBundle\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Override;
use Shopsys\MigrationBundle\Component\Doctrine\Migrations\AbstractMigration;

final class Version20260907130000 extends AbstractMigration
{
    #[Override]
    public function up(Schema $schema): void
    {
        $this->sql('ALTER TABLE articles ADD publish_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->sql('ALTER TABLE articles ADD modified_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->sql('ALTER TABLE blog_articles ADD modified_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');

        $this->sql('CREATE TABLE organizations (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, domain_id INT NOT NULL, name TEXT DEFAULT NULL, company_tax_number TEXT DEFAULT NULL, company_number TEXT DEFAULT NULL, description TEXT DEFAULT NULL, street TEXT DEFAULT NULL, city TEXT DEFAULT NULL, postcode TEXT DEFAULT NULL, country TEXT DEFAULT NULL, PRIMARY KEY(id))');
        $this->sql('CREATE UNIQUE INDEX UNIQ_427C1C7F115F0EE5 ON organizations (domain_id)');
    }
}
