mutation CreateOrder(
    $cartUuid: Uuid
    $firstName: String!
    $lastName: String!
    $email: String!
    $telephone: String!
    $onCompanyBehalf: Boolean!
    $street: String!
    $city: String!
    $postcode: String!
    $country: String!
    $differentDeliveryAddress: Boolean!
) {
    CreateOrder(
        input: {
            cartUuid: $cartUuid
            firstName: $firstName
            lastName: $lastName
            email: $email
            telephone: $telephone
            onCompanyBehalf: $onCompanyBehalf
            street: $street
            city: $city
            postcode: $postcode
            country: $country
            differentDeliveryAddress: $differentDeliveryAddress
        }
    ) {
        uuid
        transport {
            name
        }
        payment {
            name
        }
        status
        totalPrice {
            priceWithVat
            priceWithoutVat
            vatAmount
        }
        items {
            name
            unitPrice {
                priceWithVat
                priceWithoutVat
                vatAmount
            }
            totalPrice {
                priceWithVat
                priceWithoutVat
                vatAmount
            }
            quantity
            vatRate
            unit
        }
        firstName
        lastName
        email
        telephone
        companyName
        companyNumber
        companyTaxNumber
        street
        city
        postcode
        country {
            code
        }
        differentDeliveryAddress
        deliveryFirstName
        deliveryLastName
        deliveryCompanyName
        deliveryTelephone
        deliveryStreet
        deliveryCity
        deliveryPostcode
        deliveryCountry {
            code
        }
        note
    }
}
