SliderItem:
    type: object
    config:
        fields:
            uuid:
                type: "Uuid!"
                description: "UUID"
            name:
                type: "String!"
                description: "Slider name"
            link:
                type: "String!"
                description: "Target link"
            extendedText:
                type: "String"
                description: "Text below slider"
            extendedTextLink:
                type: "String"
                description: "Target link of text below slider"
            gtmId:
                type: "String!"
                description: "GTM ID"
            gtmCreative:
                type: "String"
                description: "GTM creative"
            images:
                type: "[Image!]!"
                description: "Slider item images"
                resolve: '@=resolver("sliderItemImageResolver", [value, args["type"], args["sizes"]])'
                args:
                    type:
                        type: "String"
                        defaultValue: null
                    sizes:
                        type: "[String!]"
                        defaultValue: null
