overblog_graphql:
    definitions:
        schema:
            query: Query
            mutation: Mutation
        mappings:
            types:
                -   type: yaml
                    dir: "%shopsys.root_dir%/config/graphql/types"
        builders:
            args:
                -   alias: "PaginatorArgumentsBuilder"
                    class: Shopsys\FrontendApiBundle\Component\Arguments\PaginatorArgumentsBuilder
                -   alias: "BlogArticlePaginatorArgumentsBuilder"
                    class: App\FrontendApi\Model\BlogArticle\BlogArticlePaginatorArgumentsBuilder
    security:
        handle_cors: true
        query_max_complexity: 1000
    services:
        promise_adapter: "webonyx_graphql.sync_promise_adapter"

overblog_dataloader:
    defaults:
        promise_adapter: "overblog_dataloader.webonyx_graphql_sync_promise_adapter"
    loaders:
        productsVisibleByIdsBatchLoader:
            alias: "products_visible_by_ids_batch_loader"
            batch_load_fn: "@App\\FrontendApi\\Model\\Product\\ProductsBatchLoader:loadVisibleByIds"
        productsByEntitiesBatchLoader:
            alias: "products_by_entities_batch_loader"
            batch_load_fn: "@App\\FrontendApi\\Model\\Product\\ProductsBatchLoader:loadByEntities"
