FROM nginx:1.29.3

# Download nginx.conf directly from GitHub (workaround for Apple Container build context)
RUN wget -O /etc/nginx/conf.d/default.conf \
    https://raw.githubusercontent.com/shopsys/shopsys/HEAD/project-base/docker/nginx/nginx.conf

RUN wget -O /docker-entrypoint.d/12-set-env-variables.envsh \
    https://raw.githubusercontent.com/shopsys/shopsys/HEAD/project-base/docker/nginx/12-set-env-variables.envsh
