on: [push]
concurrency:
    group: ${{ github.ref }}
    cancel-in-progress: true
name: "Docker build"
jobs:
    build-whole-application:
        name: Build application and run standards checks and tests
        runs-on: ubuntu-22.04
        steps:
            -   name: Sleep for 15 seconds to ensure that split packages has been promoted to packagist.org
                run: sleep 15s
                shell: bash
            -   name: GIT checkout branch - ${{ github.ref }}
                uses: actions/checkout@v6
                with:
                    ref: ${{ github.ref }}
            -   name: Configure application
                run: echo 1 | ./scripts/configure.sh
            -   name: Install composer dependencies
                run: docker compose exec -T php-fpm composer install
            -   name: Build application
                run: docker compose exec -T php-fpm php phing db-create test-db-create frontend-api-generate-new-keys build-demo-dev-quick
            -   name: Check standards
                run: docker compose exec -T php-fpm php phing standards
            -   name: Run tests
                run: docker compose exec -T php-fpm php phing tests
            -   name: Run acceptance tests
                run: docker compose exec -T php-fpm php phing tests-acceptance
            -   name: PHP-FPM container logs
                if: ${{ failure() }}
                run: docker compose logs php-fpm
            -   name: Copy Codeception logs from container
                if: ${{ failure() }}
                run: docker cp shopsys-framework-php-fpm:/var/www/html/var/log ./app/var/log
            -   name: Upload Codeception logs to artifacts
                if: ${{ failure() }}
                uses: actions/upload-artifact@v7
                with:
                    name: acceptance-logs
                    path: ./app/var/log

            -   name: Build Storefront part of application
                run: |
                    docker compose cp php-fpm:/var/www/html/schema.graphql schema.graphql
                    docker compose cp ./schema.graphql storefront:/home/node/app/schema.graphql
                    docker compose exec storefront pnpm install --frozen-lockfile
            -   name: Check Storefront standards
                run: docker compose exec storefront pnpm run check
            -   name: Check unused code with Knip
                run: docker compose exec storefront pnpm run knip
            -   name: Run storefront unit tests
                run: docker compose exec storefront pnpm test--no-watch
            -   name: Switch storefront to production mode
                run: |
                    docker compose down storefront
                    docker compose up -d --wait storefront-cypress
            -   name: Run Cypress tests
                run: docker compose run -e TEST_LOCALE=en -e B2B_DOMAIN_ID=2 -e B2B_BASE_URL=http://127.0.0.2:8000 cypress
            -   name: Upload Cypress videos to artifacts
                if: ${{ failure() }}
                uses: actions/upload-artifact@v7
                with:
                    name: cypress-videos
                    path: ./storefront/cypress/videos
            -   name: Upload Cypress screenshots to artifacts
                if: ${{ failure() }}
                uses: actions/upload-artifact@v7
                with:
                    name: cypress-screenshots
                    path: ./storefront/cypress/screenshots
            -   name: Upload Cypress snapshot diffs to artifacts
                if: ${{ failure() }}
                uses: actions/upload-artifact@v7
                with:
                    name: cypress-snapshot-diffs
                    path: ./storefront/cypress/snapshotDiffs
            -   name: PHP-FPM container logs
                if: ${{ failure() }}
                run: docker compose logs php-fpm
            -   name: Nginx container logs
                if: ${{ failure() }}
                run: docker compose logs webserver
            -   name: Storefront container logs
                if: ${{ failure() }}
                run: docker compose logs storefront
            -   name: Cypress container logs
                if: ${{ failure() }}
                run: docker compose logs cypress
    build-whole-application-for-single-domain:
        name: Build application and run standards checks and tests on single domain
        runs-on: ubuntu-22.04
        steps:
            -   name: Sleep for 15 seconds to ensure that split packages has been promoted to packagist.org
                run: sleep 15s
                shell: bash
            -   name: GIT checkout branch - ${{ github.ref }}
                uses: actions/checkout@v6
                with:
                    ref: ${{ github.ref }}
            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: '8.5'
            -   name: Download Shopsys CLI
                run: |
                    CLI_VERSION=$(grep '"shopsys/framework"' app/composer.json | grep -oE '[0-9]+\.[0-9]+' | head -1)
                    echo "CLI version: $CLI_VERSION"
                    gh release download "$CLI_VERSION" --repo shopsys/cli --pattern 'shopsys.phar'
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            -   name: Configure project for single domain
                run: php shopsys.phar configure . --config=.github/single-domain-config.yaml
            -   name: Configure application
                run: echo 1 | ./scripts/configure.sh
            -   name: Install composer dependencies
                run: docker compose exec -T php-fpm composer install
            -   name: Build application
                run: docker compose exec -T php-fpm php phing db-create test-db-create frontend-api-generate-new-keys build-demo-dev-quick
            -   name: Check standards
                run: docker compose exec -T php-fpm php phing standards
            -   name: Run tests
                run: docker compose exec -T php-fpm php phing tests
            -   name: Run acceptance tests
                run: docker compose exec -T php-fpm php phing tests-acceptance
            -   name: PHP-FPM container logs
                if: ${{ failure() }}
                run: docker compose logs php-fpm
            -   name: Copy Codeception logs from container
                if: ${{ failure() }}
                run: docker cp shopsys-framework-php-fpm:/var/www/html/var/log ./app/var/log
            -   name: Upload Codeception logs to artifacts
                if: ${{ failure() }}
                uses: actions/upload-artifact@v7
                with:
                    name: acceptance-logs
                    path: ./app/var/log

            -   name: Build Storefront part of application
                run: |
                    docker compose cp php-fpm:/var/www/html/schema.graphql schema.graphql
                    docker compose cp ./schema.graphql storefront:/home/node/app/schema.graphql
                    docker compose exec storefront pnpm install --frozen-lockfile
            -   name: Check Storefront standards
                run: docker compose exec storefront pnpm run check
            -   name: Check unused code with Knip
                run: docker compose exec storefront pnpm run knip
            -   name: Run storefront unit tests
                run: docker compose exec storefront pnpm test--no-watch
            -   name: Switch storefront to production mode
                run: |
                    docker compose down storefront
                    docker compose up -d --wait storefront-cypress
            -   name: Run Cypress tests
                run: docker compose run -e TEST_LOCALE=en cypress
            -   name: Upload Cypress videos to artifacts
                if: ${{ failure() }}
                uses: actions/upload-artifact@v7
                with:
                    name: cypress-videos
                    path: ./storefront/cypress/videos
            -   name: Upload Cypress screenshots to artifacts
                if: ${{ failure() }}
                uses: actions/upload-artifact@v7
                with:
                    name: cypress-screenshots
                    path: ./storefront/cypress/screenshots
            -   name: Upload Cypress snapshot diffs to artifacts
                if: ${{ failure() }}
                uses: actions/upload-artifact@v7
                with:
                    name: cypress-snapshot-diffs
                    path: ./storefront/cypress/snapshotDiffs
            -   name: PHP-FPM container logs
                if: ${{ failure() }}
                run: docker compose logs php-fpm
            -   name: Nginx container logs
                if: ${{ failure() }}
                run: docker compose logs webserver
            -   name: Storefront container logs
                if: ${{ failure() }}
                run: docker compose logs storefront
            -   name: Cypress container logs
                if: ${{ failure() }}
                run: docker compose logs cypress
