SliderItem:
    type: object
    inherits:
        - 'SliderItemDecorator'
    config:
        fields:
            id:
                type: "Int!"
                description: "ID"
            uuid:
                type: "Uuid!"
                description: "UUID"
            gtmId:
                type: "String!"
                description: "GTM ID"
            gtmCreative:
                type: "String"
                description: "GTM creative"
