AddProductResult:
    type: object
    config:
        fields:
            cartItem:
                type: CartItem!
            notOnStockQuantity:
                type: Int!
            overLimitQuantity:
                type: Int
            isQuantityOverLimit:
                type: Boolean
            isNew:
                type: Boolean!
            addedQuantity:
                type: Int!
