services:
    _defaults:
        autoconfigure: true
        autowire: true
        public: false

    Shopsys\AdministrationBundle\:
        exclude:
            - '../src/DependencyInjection/'
        resource: '../src/'
