CartInput:
    type: input-object
    config:
        validation:
            -   App\FrontendApi\Model\Component\Constraints\AppPaymentTransportRelation: ~
        fields:
            cartUuid:
                type: "Uuid"
                defaultValue: null
                description: "Cart identifier, new cart will be created if not provided and customer is not logged in"
            payment:
                type: "PaymentInput"
                defaultValue: null
                description: "Represents a payment in order"
