query BrandQuery($uuid: Uuid!) {
    brand(uuid: $uuid) {
        name
        slug
        description
        link
        seo {
            title
            metaDescription
            h1
            metaRobots
            canonicalUrl
        }
        products (first: 5) {
            orderingMode
            edges {
                node {
                    name
                }
            }
        }
        images {
            url
            name
        }
        breadcrumb {
            name
            slug
        }
    }
}
