resources:
    - ../../cron/php-fpm-cron-executor-default.yaml
    - ../../deployments/redis.yaml
    - ../../deployments/smtp-server.yaml
    - ../../deployments/webserver-php-fpm.yaml
    - ../../services/redis.yaml
    - ../../services/smtp-server.yaml
    - ../../services/webserver-php-fpm.yaml
    - ../../ingress.yaml
    - ../../namespace.yaml
    - ../../configmap/nginx.yaml
    - ../../configmap/redis-health.yaml
namespace: "{{PROJECT_NAME}}"
configMapGenerator:
    -   name: domains-urls
        files:
            - ../../../config/domains_urls.yml
    -   name: parameters
        files:
            - ../../../config/parameters.yml
    -   name: nginx-configuration
        files:
            - ../../../docker/nginx/s3/nginx.conf
