on:
    schedule:
        -   cron: '0 3 * * *'
    workflow_dispatch:
name: Rebuild Docker images
jobs:
    rebuild-elasticsearch-images:
        name: Rebuild ${{ matrix.branches }} branch Elasticsearch Docker images in GitHub Container Registry - with JavaScript Storefront
        runs-on: ubuntu-22.04
        strategy:
            matrix:
                branches: ['18.0', '19.0']
            fail-fast: false
        permissions:
            contents: read
            packages: write
        steps:
            -   name: GIT checkout branch - refs/heads/${{ matrix.branches }}
                uses: actions/checkout@v6
                with:
                    ref: refs/heads/${{ matrix.branches }}
            -   name: Login to GitHub Container Registry
                uses: docker/login-action@v4
                with:
                    registry: ghcr.io
                    username: ${{ github.actor }}
                    password: ${{ secrets.GITHUB_TOKEN }}
            -   name: Build Elasticsearch image and push it to GitHub Container Registry
                run: |
                    DOCKER_ELASTICSEARCH_IMAGE_TAG=github-action-`find project-base/app/docker/elasticsearch -type f -exec stat -c "%a %n" {} \; -exec cat {} \; | md5sum | awk '{ print $1 }'`
                    DOCKER_ELASTICSEARCH_REPOSITORY_TAG=ghcr.io/${{ github.repository_owner }}/elasticsearch:${DOCKER_ELASTICSEARCH_IMAGE_TAG}
                    .github/build-elasticsearch-image.sh ${DOCKER_ELASTICSEARCH_REPOSITORY_TAG}
                    docker image push ${DOCKER_ELASTICSEARCH_REPOSITORY_TAG}
