OrderWithdrawalRequestDecorator:
    type: object
    decorator: true
    config:
        fields:
            firstName:
                type: "String!"
                description: "First name for withdrawal request contact"
            lastName:
                type: "String!"
                description: "Last name for withdrawal request contact"
            telephone:
                type: "String"
                description: "Formatted telephone number for withdrawal request contact"
            telephoneData:
                type: "PhoneData"
                description: "Telephone number data split into country code, prefix, and number"
            email:
                type: "String!"
                description: "Email address for withdrawal request contact"
            note:
                type: "String"
                description: "Additional notes or instructions for withdrawal"
            requestedAt:
                type: "DateTime!"
                description: "Date and time when the withdrawal was requested by customer"
            confirmed:
                type: "Boolean!"
                description: "Whether the withdrawal request has been confirmed, requests of guest orders await confirmation via the email link"
